/* u8g2 official font: u8g2_font_squeezed_b6_tr (809 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_squeezed_b6_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_squeezed_b6_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_squeezed_b6_tr', font)
 */
const u8g2_font_squeezed_b6_tr = "XwACAwQDAQQFCAcA/wb/BgABBQIVAw0gBYA4ASEH4jg5QgEiB6VskSgBIwnXiFNdqksFJAv2d5UPmT5kEQAlCuZ4EWU1JCsFJgvmeBslcZQqsQAnBaI8ISgH40ijNAUpCONIESUVBSoJ1WmRpKmaFCsItFqTKAkALAWiNyEtBZNLGS4FojghLwnkWFWJkigCMAnlWJskLmkCMQbjSKt0MgjkWJlFSUkzCORYmWuxAjQI5WiRqFsDNQjkWDFnsQI2C+Vom2RKoqQJADcJ5FghJVELADgL5WibVJNESRMAOQrlaJtUNCVNADoGsjkRBTsH0jeRIQI8BrNKIwU9BrNKmQc+B7NKESkAPwrkWJklUYYlAEAK5nijRKoNUgBBCeVom6RDYglCCuVooSRLoiwAQwfkWCu1B0QJ5WihJC4LAEUI40ipKmkARgjjSKkqFQBHCuVom+SLkiYASAnlaJGoQ2IJSQbiODkKSgbjSNNVSwrlaJGskZIoAUwH40iRdA1NC+eIkaujimhaAE4K5ngRq2MqSQFPCeVomyQuaQJQCeVooSRLVgNRCOZ4GyX9LFIJ5WihJEtiCVMI40ijRIkCVAjkWKFEXQBVB+VokXgdVgnmeBE5JVoEVw7omJEhGqIhSjomUQJYC+VokShpnCRKAFkM5ngRSYmWIRkSAVoI5FghJUskWwfjSKm0BlwJ5FgRZVEWBV0H40iZtApeBqRckwhfBZNIGWAGo0wRBWEIxWizKIkAYgrlaJFlSqIsAGMHxFgr5QFkCOVoV1mURGUIxWibpHoCZgjjSKMqFQBnCNVnsyTyAmgJ5WiRZUpiCWkH4jgRjwBqCfNHkyEtCgBrCeVokVWWRAlsBuI4OQptCciYuVSURCluCMVooSSWAG8JxWibJEqaAHAJ1WehJMqSAXEI1WezKIkWcgjFaJEsWQZzB8NIIykAdAjjSJGkShR1B8VokVgHdgjFaJFY0gR3C8iYkSFKolQWAHgIxWiRpHFSeQrVZ5EoiZwmAHoHw0iZqAF7CORYlaRRLXwG4jg5Cn0K5FiRxUmURAB+CKZ8kygJAAAAAAT//wA=";
export { u8g2_font_squeezed_b6_tr };
export default u8g2_font_squeezed_b6_tr;
