/* u8g2 official font: u8g2_font_open_iconic_text_2x_t (752 bytes, 32 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_text_2x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_text_2x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_text_2x_t', font)
 */
const u8g2_font_open_iconic_text_2x_t = "IAAEBAUFBAQGEBAAABAAEAAAEwAAAtRAE9ChwvCBeIi4h+jBA/EQcQIAQRXQocLwgXhIGLGH7MED8ZAwYgQAQhPQocLwgXjIGLGH5MED8ZAxYkMgECLCwKhRmUL0ptCqNqTIECNCjAgxIsRIlCLxog0ARCSQocIqWpwoEWJEiREiSowIUaJISSFGlBAxosSIECVOtFAARSLOocJBiIQRJJIQkeRBCFZCBAoRxeJBEEmISILEBCESAEYM8GHC8P8HrIeLD0cVECLC8IF4SJSph9MHD8RDwsSJAEgakKHCxKYJJULISGFsESMSxoaQkYQSMY0YSRVw4cJgiB+tKkGMyLgxAgWFDAUAShNwocIVMpBAMeOGECNRahE/MksXkKHCJFAIMRLjxggUI1CQQEGG+JEBTBiQocJgiB8ZEihIoBiBYsaNIEZEoCAATQ+QoMNAhAgSIkiIIKEAThbQocLgxD1EytRD+OCBeEhkJkQyAE8fzqHCYISJEWGChAkSJkiYII2ECRImSJggYUKMMDFQGBAhw0KIjBETQ4wUolERIyOMmCFEBABRGQgywiWKECmhZIxIJmqUqFHChAgxQwIAUhgOIsKkHVGSJUmWJEqyJMmSRMkpUgQAUxXQocLwgXhIHjwQD8mDB+Ih4gQAVBbQocLwgXhIHjwQD8mDB+IhYcQIAFUV0KHC8IF4SB48EA/JgwfiIWPEAFYQECLChBBHD/4HiBDiCABXCJCgw/AHBFgQECLCRpiePfgBMcL0DABZFwoywmIGxaBiAqUTN2w6geJBCxQEAFoUECLC8AERN27asBlGhNiD/4ECWxMQIsLwASFCo0gFI0z/FCEiAFwiDiLCQkgQIUGEBBESREgQIUGEBBESREhQkVEIy0PyoAFdGdChwkAQT4ggIYKECBIiSIggoR6SBw8EXhjQocJAEBMiSKiH5MED8ZBQgoQIQoQEXxnQocLwgXhIKEFCBAkRJESQEEFCBCEOCQAAAAT//wA=";
export { u8g2_font_open_iconic_text_2x_t };
export default u8g2_font_open_iconic_text_2x_t;
