/* u8g2 official font: u8g2_font_open_iconic_other_4x_t (540 bytes, 8 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_other_4x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_other_4x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_other_4x_t', font)
 */
const u8g2_font_open_iconic_other_4x_t = "CAAFBQYGBAQHICAAABwAHAAAKgAAAgBAKpTHCV7BDKQQR5D0CmdqR3vIqzzkKQ95taMZznDFIyABhzhEQQYzWABBQCCGDGZIdaDUqIUYJBnMOIYzigENUshiFGUgQykEUQpRFEIQxCFEKIhDEgIRhEAEIRAhEARh0ZHOZKqCjQYAQkAciAgmBCMMgpChGEUoRgkMwSNMUIwiFKMMBCGGYAQiGIEIRiCCEYhYBZrSlCQFsaIiU5FKZCBbVKQyEUtQAEM5HIcMBgQhEYSQCEJIBCFkH2wShEQQQiIIIRGEkH2wSRASQQiJIIREEEL2wSZBSAQhJIIQEkEIGURJIIgIBghBCEQQAhGEQAQhEEEIRBACEYRABPXBERSBCEIgghCIIAQiCIEIQiCCEIigPjiCIhBBCEQQAhGEQAQhEEEIRBACERRFEyCICAYMwv9DzAd/iEH4f4gBRlcciAjG5CBBCEgQAhKEgAQhIEEISBACEoSABCEQQUiIICREEBIiCAkRhIQIQkIEISGCEAQhJIIQEkEIiSCERBBCIgghEYSQCEJIBCEkghASQQiJIIQMR2ggiAhmSHWg1KiFGCQZzDiGM4oBDVIYwxSjKEopBFGYQgiCOIQIBSmRhBSmIAghEEEQQiCCIIRABEEIgQiCkMIUJCFlgSAOIQRRmEKIoiilGIUxTEEMaBTDGcdgRkIMsqgmQaciDAAAAAAE//8A";
export { u8g2_font_open_iconic_other_4x_t };
export default u8g2_font_open_iconic_other_4x_t;
