/* u8g2 official font: u8g2_font_oskool_tr (1021 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_oskool_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_oskool_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_oskool_tr', font)
 */
const u8g2_font_oskool_tr = "XwACAgQEAgQFCwv+/gcAB/4BSAKsA+EgBQBiBSEIciMtjREFIgc0ckVdASMLZuIttsaKaQwpJA61mj2jLKtapzl0RhElD3miVqvSzFTSqDLHRgomDHbiVccqW2mmkQInBjLybAgoCZMaNcXkmQMpCpMaJceoXCUAKgpW5i1mOdZIUisMZqE9wzimRhpJACwHMplsJAAtBiWq5QUuBSLibC8JdaJdap1NDTANdyJeo1gnPfKIUwMxCHLibKUxAjIKdaJV1ii6hwAzDHbiVccMs8Yjjgk0DXbiHWWkU6zG1kgBNQt1onXlDDeaagQ2DHbiXceU4ZQjmgA3CXSjZeRYOgE4C3biVce2lCOaADkKdGJNRZmmMgE6B1LiLMMBOwhimSzDkQA8ClbmHUkbjQwHPQg0amVkNAI+ClbmRWMN19QIPwp1om3lWmpSAkAUmpl+aJRhecW4Ylwxjah0Zo0FQQx24lXH1hhyxBEFQgx24m3EnPJY+lgAQwl1olVW2T0ERAp24m3EnPLHAkUMdaJtpIzySFoPAUYLdaJtpIzySNoGRwx24nWkDDNSQx8LSAx24i32GkOOOKIASQdy4qwaB0oJlBlVl55JAksMduItp1jFraJMOkwKdaIto4yyewhND3miVunYS8OR4chwZChOEXhiLqOoY4pJxRHTyEMjAU8MdyJ2lznpkUeWE1ANduJtxJzyuJFGGgFRDYcedpc56ZFHPDIWUgx24m3EnPK4okw6Uwt1olVWGWp4KABUCnWiZciMsicAVQx24i32kiOOOIYAVgx1oi2mmOKVVJoAVxF5oi7DGtYwaThiHDGONQJYDXciLsdcZZiRe2QBWQp1oiXrVGcnAFoMduJtaJhRRtlGY1sJlFpt5dJzBFwMdaJFI61RRlojAV0IkxpltlxDXgdEbrVaMl8GJZ7lBWAHMjMljQBhClbiVcc0hhxRYgpW4m3EPJYeC2MJVaJVxq2HAGQJVuJtxPxYAGUKVaJtpDySHgJmClWibaQ8ktYAZwtW4nWkjNTQYwRoClbiLbbGkCMKaQdS4iyNEWoJdNhUR2eSAGsKVaItpmqqJANsCVWiLaNsDwFtDVmiVulYyTgyHBkKbgxXIi5HmVQacWgBbwpXInZXemQ5AXALVuJtxDyWRhoBcQtnHnZXesQjYwFyClbibcQ8looGcwpVonVlqORQAHQIVaJlyOwEdQpW4i225IhjCHYKVaItpriSShN3DlmiLsMaJhlHjGONAHgKVyIuVxlm5BZ5CVWiJac6mwB6CVWibeRoDwF7DpbaXWeYYdZYI400HHwIkt6sNQ4BfQ+W2k3jDDPMWGqkkdwAfgk3Kk6jJPMCAAAABP//AA==";
export { u8g2_font_oskool_tr };
export default u8g2_font_oskool_tr;
