/* u8g2 official font: u8g2_font_tenthinguys_tu (752 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_tenthinguys_tu.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tenthinguys_tu.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tenthinguys_tu', font)
 */
const u8g2_font_tenthinguys_tu = "QAADBAQEAwQFCg0A/Qn9CQABcwAAAtQgBQDECiEIk0SKhzEDIgpHbIwRKyNSACMQmMQcIZGHECF5eQgREgEkEai8PEGTE2lHZyIiJ4ZiACUPmMSMsZEgEzK6GIWMDSYLZtYsQSEmQSEAJwhE9AoWEQAoCpdEzDEiGmkcKQuXRIxBOtE2CAAqDndMDLGSkbKxkpEyASsLZswrQSEmQSEALAgzPBoREgAtBibcCwYuBjLECQMvEorEfRDx4RGxoZHB4nGQYAAwCpjEjAciOz0QMQeTRIoHBjINmMSME9QRl9HRhwAzDZjEjBNUFdTRhxEANAqYxIwhSw+kczUNmMSMB9IT1NGHEQA2DZjEnIfRkyWjFRMANwmYxIyH0PkBOA6YxByTpRGTJaMVEwA5DpjEHJMlo5XTkRMTADoHcsQJIwM7CoM8GhlFREgAPA2WxEuxIZKVIrJBAT0HVtQLZgY+DpbEC8ExopIVojFBAD8PmMQck6XRIaNywNExAEAPmURdpBOjkWkiMopgAUEMmMQckyWjhyNLA0IOmMSMkyUjlSGjhxEAQwqXRJyHwDmeGEQLmMSMkyU7PYwARQyXRIwHQROTwUEHRg2XRIwHwUETk8GJAEcLmMSch9FJllYOSAuYxIwhSw9HNg1JCZVEC5WhuShKC5jE3LkaGa2YAEsNmMSMISsrRiOTLA1MCZdEjMH56ABNDZrEjcGjBxYRQxsHTgyYxIyhk4eTI5sGTwuYxByTJTutmABQDZjEjJMlo4eR0akAUQuovByTJTspHQtSDZjEjJMlo4eRIUsDUw2XRJyHQCPDwYcQAFQKl0QMp8H5BABVC5jEjCH7tGICAFYMmMSMIfsyYlQGAFcOmsSNQVtETEQeHo4IWA6YxIwhSyNmZCZDlgZZDplEjTGzE5Kz0uHZAFoLmMSMh0AyOj4EWwiVRIumOSlcDJlEveFpD2zD0wBdCJVEC6U5NV4INvQrMRIDXwcorIyHAAAAAAT//wA=";
export { u8g2_font_tenthinguys_tu };
export default u8g2_font_tenthinguys_tu;
