/* u8g2 official font: u8g2_font_streamline_phone_t (734 bytes, 11 glyphs)
 * Converted verbatim from u8g2_font_streamline_phone_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_phone_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_phone_t', font)
 */
const u8g2_font_streamline_phone_t = "CwADAgUFBAMGFRUAABUAFQAAAAAAAsIwNawy6+RYkkNJDg0HJceUYVCUcFGyIVGiQVGSYVGGQdExJZISbciUSEp0TPGOKd6xZDgkADFAtSJrDR+0nKSkw6Ap4hI5JsOkiTkiirkqxsZUF0MpFTMtFSMxldXUnIp6qulIKknDoCrSMMhDTktyWjZ8kAAyRrUi6wzvyKBEg54NW56jeY7mOZrnaB6JUp6jeU7O0UHLhmkYohyLpiSHtGyH1iGHhmzQoXXIIS3bsWhKhkM0DNlwiAYNMy11YmumdSisg1md/zR8zSlZTktyqjwM8TDow4M+DMmgQ8NOzklZTmmn7ZQVNE21ImsNH7ScpKRDrohVSStltkyJRClUElXKEVkKFV3KIh2RskQTpVDOpEyJpEiKtFIiJZZSkmiSEiUVSYtyxBLm0JANOZbktGz4IAE1QrMm6w05HuZoFuVgpuRYqORYnmOpDtbhMIfDHA7TQQvDYYjCLJqSNNGyfR1CZciGJFPWJYu0TIqjKRyyYcjhQQM2NnNm6+zgktN0mjQ8RFnnZBiSclIrLwc5WTpnyVJOliyJh4c4a04qSzlLaqXhIdJpOi3ZwQU3O7Ui62M5OYfHcM0pYU4Jo+WUV3IsSe5oluNZ0jotWRKtWbLk3JY7ltSSPFoqU5hTwpySjuEO5+QcAzhEE+brk3RSolMSHZQSHUuURMcSJZGlREnUREmURE2URElMiZIoyaIkSqIki5IoiZIsSqIkSrIoiZIoyaIkSqIkNhcAOVG0IusOhxwakmjIkWiYciTHwizHKlGORVmSY0kW5ViUZFEYZUmURVmUJVEYJVmUY1GS5VglSiIpibIkMiVZlGNRkuVYMcdyJMdyZHiHhkMKOkO0IusND2qOZzkpCYdDqOVYpuVYZUfnIRpyLGqHpCHSc7Q6pGG3MJLCKEyGJIzCZEjCKIykMErDNIqHOMvxdHjQAAAAAAT//wA=";
export { u8g2_font_streamline_phone_t };
export default u8g2_font_streamline_phone_t;
