/* u8g2 official font: u8g2_font_pixelle_micro_tr (704 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_pixelle_micro_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_pixelle_micro_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_pixelle_micro_tr', font)
 */
const u8g2_font_pixelle_micro_tr = "XwACAgMDAQQEBgj//gX+Bv8A4gHNAqQgBEBMIQZpVFYAIgbTZZIKIwpt9KqhqqEqACQJ++PSiEdKACUGZGxiDyYJbOxkVCqpACcF0VUEKAf621RnACkI+ltiaikAKgZj5NJqKwdb5NJKACwF0VMELQXLZAYuBUlUAi8Ic2SrmGIEMAhr5KqhKgAxBmtkZGsyB2vkmikNMwdrZHTKCzQIa2SSGrEANQdrZEa8ADYHa+Sq1QI3CGtkZoopAjgGa+T6BTkHa+RaqwI6BllUUgA7BuFTkgA8BlrcZAA9Bltk9gA+BlpcogI/CGvkmikmAEALdfRWVkmNDEcAQQhr5KqhVABCCGtkVFppAUMIa+QqmSoARAhrZFSyFgBFB2tkRlRxRghrZEZUMQJHCGvkKpmSAEgIa2SSGkoFSQdrZFasBkoHa2RLVQFLCGtkklpJBUwGa2Ric00Ia2TSGEoFTghrZNI4VABPB2vkKqsCUAhrZFRaMQJRCGvkKjWSAFIIa2RUWkkFUwdr5HYeAVQHa2RWbAFVB2tkkqsCVghrZJJVJgBXCGtkkhpDBVgIa2SSaqkAWQhrZJIqKwBaB2tkZioHWwf6W1aXAFwIc2RijjkGXQf6W1TXAF4F0+UaXwVLZAZgBVFWBGEGW+RWEmIIa2RiVGkBYwZb5LYAZAdrZKuVBGUGW+SGEmYHatzUSgBnCGvjVloVAGgIa2RiVEkFaQZpVNIAagg7WzMsVQVrB3NkYmsVbAVxVA5tB110VEsVbgdbZFRSAW8GW+S6AHAIa2NUWjECcQdr41aSBXIHW2RUkgBzB1vkVFIAdAhr5GJaMQF1B1tkkqoAdgdbZFKZAHcJXXRSUmklAHgGW2RSB3kIa2OSSqsCegZbZFYaewn7Y1NMOeYAfAb5U44AfQn7Y3LMKaYIfgfU7JJKAAAAAAT//wA=";
export { u8g2_font_pixelle_micro_tr };
export default u8g2_font_pixelle_micro_tr;
