/* u8g2 official font: u8g2_font_tinyunicode_tr (765 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_tinyunicode_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tinyunicode_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tinyunicode_tr', font)
 */
const u8g2_font_tinyunicode_tr = "XwACAgMDAQQFBwgA/gX+Bv8A9wHxAuEgBUCsACEGaZSsACIGU6YkFSMJbbSm1lCdACQJ9KvlodHQCSUIa6SkmMoUJglttMkMlYwqJwVRlggoB/qbqc4AKQj6m8TUUgAqBtulpA4rB9ukpZUALAbSmykALQVLpQwuBUmUBC8Ha6RWZQQwCGysqWgmBTEGapytBjIIbKyp2BwBMwlsrGyU9kgANAlsrEZVjZgANQlsrAy90UgANglsrKm8YlIANwhsrIwc6wg4CWysqZhUTAo5CWysqZh2UgA6BlmUpAA7BuKbZQU8BtqcyQA9CNysjIxGAD4G2pxEBT8JbKxslDSOAEAO/8OOmJFUqpIzUyMBQQhsrKk4pgxCCWysrDhSHAlDBmukzVpECGysrGiOBEUIa6SMqOIARghrpIw4YgRHCGysjZxmGkgIbKxEOaYMSQdrpKxYDUoIbKztLJMCSwlsrESVZCoDTAdrpMTmAE0JbbTktZLWAU4IbKzEpaYMTwhsrKloJgVQCWysrDhSzgBRCfSrqWgmjQJSCWysrChHigFTCWysjYw0GglUB2ukrNgCVQhsrERnUgBWCGysRKsZAVcJbbRkK6kuAFgJbKxEmVSUAVkJbKxEmXZSAFoHa6TMVA5bB/KbrJYAXAdrpMRcBl0H8puo1gBeBdOlNV8GzbMMAWAG0p3EAGEIZKyNKNMAYglsrOQV5UgAYwZjpM0sZAhsrKcRZRplCGSsqTSyAmYIa6SptGICZwl0q40o004KaAhsrOQVzQBpBmmUpAFqCHqb5VQpAGsJbKzkqNKKAWwGaZQMAW0JZbSMVKmkCm4HZKysaAZvCGSsqSiTAnAJdKusKEfKGXEIdKuNKNMucghjpKQVIwBzCGSsDY2GAnQIa6SlFaMAdQdkrEQzDXYIZKxEK0YAdwlltGSVVBcAeAdjpKQyFXkJdKtEM+2RAHoIZKyMWI4Aewn7o6mYcowCfAZplAwBfQn7o8g6xaQAfgjdtEWVZAIAAAAE//8A";
export { u8g2_font_tinyunicode_tr };
export default u8g2_font_tinyunicode_tr;
