/* u8g2 official font: u8g2_font_3x5im_mr (866 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_3x5im_mr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_3x5im_mr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_3x5im_mr', font)
 */
const u8g2_font_3x5im_mr = "XwICAgMEAQIEBAkA/gX+BQABKgJEA0YgBszw/B8hCczwdJvKLAAiCMzwZGrzAyMKzPBkSqtaNQMkCczwdFxazUwlCszwZMqxTpkBJgrM8LTSqtQZAicIzPB0zS8AKArM8HTMNcosACkKzPB0RrnMLAAqCczwZIpV5gkrCczwXHFmTgAsCMzw/BUzBS0IzPC8Nk8ALgjM8PyVWQAvCszwrCijzEwAMAjM8OTqazMxCMzwdNTlZjIJzPDkTitvBjMJzPDkjjptBjQJzPCsqKqdGTUJzPDkyjttBjYJzPCkzKvaDDcKzPDkjjJnFgA4Cczw5KpWtRk5Cczw5Kp21Aw6CczwXJnKnAA7CczwPDMVMwU8CszwrFijjDIDPQnM8OwNNxcAPgrM8GRGGcWaCT8KzPDkjhpnFgBACszw5Maq2nABQQnM8OSqVjcDQgrM8OSqZEqbAUMIzPDkyvVmRAnM8KRMvTQLRQnM8OTKMm8GRgrM8OTKMmcmAEcJzPDkyqm1GUgJzPBkaq1uBkkIzPDkzOVmSgnM8KxcVZsBSwnM8GRqydRmTAjM8GRubwZNCczwZEpXNwNOCMzw5OpvBk8IzPDk6mszUArM8OSqVs5MAFEJzPDk6pqaAVIJzPDkqmRqM1MJzPDkyjttBlQJzPDkzG0WAFUIzPBk6tdmVgnM8GTqNTMLVwnM8GRqXTUDWAnM8GRqVm0GWQrM8GRqzZxZAFoJzPDkjkpuBlsJzPCkzLVmAVwJzPBk1llnBl0IzPC0bmoGXgjM8HRMmR9fCMzw/GtDAGAIzDAZZf4DYQjM8DxVtRliCczwZM6r2gxjCMzwvFbeDGQJzPCsnFa1GWUIzPC8ltwMZgrM8LSMM2cWAGcJzPC8VrWjAmgJzPBkzqubAWkJzPB0pnLNAmoJzPB0pnJTAmsKzPBkrpJMmQFsB8zwdLdmbQjM8LyumgFuCMzwvFY3A28IzPC8VrUZcAnM8LxWtXIGcQnM8LxWtSsAcgnM8LxWzkwAcwjM8Lzk1Ax0CczwdDlzZgF1CMzwvLo2A3YIzPC8OjMLdwjM8LyqmwF4CMzwvMoqM3kJzPC8unZUAHoIzPC8ZtwMewnM8LSMOmsGfAfM8HQ/AX0KzPCkzjJqFgB+CMzwnGllHgAAAAT//wA=";
export { u8g2_font_3x5im_mr };
export default u8g2_font_3x5im_mr;
