/* u8g2 official font: u8g2_font_baby_tr (770 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_baby_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_baby_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_baby_tr', font)
 */
const u8g2_font_baby_tr = "XwACAgMDAgQEBgn//gX+Bv8A+AH2AuYgBYCoACEG8biMFCIGm8wkKyMKrehVQ1VDVQAkCLvHxZ1nAiUIrejIlaspJgq16OWUq1iqACcFmawMKAe6t6nOACkIurfE1FIAKgaby6QOKwfb2aWVACwGmrYoBS0Fi8oMLgWJqAQvCLPHVjHFCDAHq8hVVgUxBqq4rQYyCKzYqdgcATMJrNhslDQaCTQIrNhEM+0ANQms2Ay90UgANgms2Km8YlIANwis2Iwc2wA4CazYqZhUTAo5CazYqZh2UgA6Btm4pAA7B6q25aQAPAms2CeVkUYBPQabyewBPgms2GSkUVIZPwm02KnYpiIAQAq16K2skpXhAkEIrNipKMcMQgms2Kw4UhwJQwms2KmoY1IARAis2KxojgRFCKzYDL3yCEYIrNgMvXIGRwms2KmcZlIASAis2EQ5pgxJB6vIrFgNSgis2O0skwJLCKzYRHOkGEwHq8jE5gBNCq3oqJVUUkkHTgis2ES51AxPCKzYqWgmBVAJrNisKEfKAFEJrNipKFMaCVIJrNisKEeKAVMHq8jtvABUB6vIrNgCVQis2ERnUgBWCq3o5FSmmHIEVwit6GRXFwBYCKzYRDOpGFkJtNdEM+2kAFoIrNiM2B4BWwe6t6wuAVwIs8fEHHMMXQe6t6iuAV4Fk8w1XwaM14wAYAaSvcQAYQik2Kko0wBiCazY5BVlUgBjBqPIzSxkCazYpxFlUgBlCKTYqajiAGYIrNipqGUGZwm01qko004KaAis2OQVzQBpBqmopAFqCHu2ZthcAGsIq8jEtJIKbAapqAwBbQil6KiWSjpuB6TYrGgGbwik2KkokwJwCbTWqShHyhlxCLTWqSjTLnIIpNisqDMAcwik2K2M0gJ0CKvIpRUrAHUHpNhEMw12CKTYRDMpAHcJpehklVQXAHgIpNhEmVQMeQm01kQz7aQAegik2IxYjgB7CbvHpphyzAF8BrmnHAF9CbvH5JhTTBF+CJ3p5VQnAAAAAAT//wA=";
export { u8g2_font_baby_tr };
export default u8g2_font_baby_tr;
