/* u8g2 official font: u8g2_font_NokiaSmallBold_tr (861 bytes, 88 glyphs)
 * Converted verbatim from u8g2_font_NokiaSmallBold_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_NokiaSmallBold_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_NokiaSmallBold_tr', font)
 */
const u8g2_font_NokiaSmallBold_tr = "WAACAwQEAgQFCAgA/wf/B/8BNgJOA0EgBQDiBCEHcuLkGAUiByM2JZICIwt1oi11TKljSgEkDIWeLWlFJBWZUQQlD3biRYzUUAzJUAypQgEmDHbibZTEkZqqVQAnBiG2RAAoCYMeNYp0xgEpCoMeJQ4lrSQAKgt1ojUVWZOVDAErC1WmNYbCMoZCACwGMt6MAi0GFG6FAC4GIuKEAC8KcyI1JUVSGAIwCnWibZJ4SRMAMQdzY63SAzILdaKFhmRpkuUCMwx1ooWGZGmGZAsANAl1ol2covFWNQx1ooWKIRqSZQsANgt1om2SKYklTQA3CnWipRZlUVYCOAx1om2SKGmSKGkCOQt1om2SWBItTQA6BlLihCQ7B2LehKYAPAl0Yj2U1OoAPQc0ZoWGCD4JdGIl1lLGAD8LdaKFhkS1jBQBQAx24o0Sj+mIZJACQQp1om2SWIdECUIKdaKFkiyJZQFDCHWizdYNEUQJdaKFknhZAEUJdaLlpmR1AUYJdaLlpmRtAEcKdaJtklUsiQBICnWiRaIOiUsASQZy4uQBSgh0YlXPCgBLDHbiRaQkciYlpQBMCHRiRdSTAE0MdyImBufqqCKaFk4LduIlJqtjKukATwp24o0SeUoUAFAKdaKFkliWLANRCobejRJ5TTQoUgp1ooWSWBalAFMJdGKtlJUVAFQPduLFlCEZkiEZkiERAFUJdaJF4kuaAFYMduJFZEokLUMiAFcNdyJGZkWHVEqiJAFYDHbiRSQlWqZEUgBZDnbiRSQlWoZkSIZEAFoJdaKlFqelXFwJcyIlDMVQTF8GFt7FAGEJVaJthiRLImIKdaJFlimJZQFjB1RirVQPZAl1ol1lsSQCZQpVom2SDhmaAGYIcyKNqrQAZwplns2iJFqaAGgKdaJFlimJSwBpB3LiRDwGagmDHk2GdFEAawp1okVWWSOlAGwGcuLkAW0LWGLmUlESJVEKbghVooWSuARvCVWibZJY0gRwCmWehZIoS5YBcQllns2iJFoBcghUYkU6lQBzCFRirSQrAHQJcyJFkiqlAHUIVaJF4pIIdgpVokWipHEOAXcMVyJGpiIqkkpJAngKVaJFoqRJogR5CmWeRWJJtDQBegdVoqXULn4HdaLF1m0AAAAE//8A";
export { u8g2_font_NokiaSmallBold_tr };
export default u8g2_font_NokiaSmallBold_tr;
