/* u8g2 official font: u8g2_font_courR08_tr (965 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_courR08_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_courR08_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_courR08_tr', font)
 */
const u8g2_font_courR08_tr = "XwACAgMEAwQEBgoA/gb+B/4BMAJ0A6kgBQCmAyEHOaMzVAAiB5uyk6wAIw7FnlemNFSZ0lBlSgAkDMSeG0dGGsmkEwAlDT6is1OcWacRU1YAJgs2oqsz1DHpuAInBRmzMygKS5ubYop1zAEpCsuak2OOVUwRKgklrhuVzCkBKwotpptRHDKjCCwHmpqXFAAtBoyuMwIuBRGjIy8RTp4PM8oow4wyzCjDjDIEMAm8oqeiZ1IAMQi8opt21wgyCbyip2KO7REzC7yip2JOGsmkADQMPaKfZSrT0BklADUKvKIzdN4ojwQ2CryiN3JeUSYFNwq8ojNkjjnmCDgLvKKnokwqyqQAOQq8oqeiTDuPBDoGKaOjBDsHsppXJwU8B6umm+oCPQicqjMyGgE+Byunk6sSPwm0oqdim4oAQAxGnjuzHKnPlfECQQs2ordRWY5YSQFCCzWiM2I1qzgUAEMJtKKnoi6TAkQMNaIzYhVTTHEoAEULNaIzVEwzozgGRgs1ojNUTDPFPAFHCrSip6JOMykASAs2oiNVjCN2SQFJDLWiM2RGGWUUhwBKC7WiN3JGZYpRAksMNqKjZMoa1THNAEwLtaKzM8ooozgGTQq1opPXSirpJU4MNqKjVowqJlnJBE8JtKKnojMpAFAKtaIzYhXTzBNRCbyep6IzyQFSCzaiM3Js7phmAFMKtKI3MtJIjgRUCzWic5UZZZQXAFUJNqIjVey3BFYNNqKjRo4pp5wyygBXDDaio0ZOfaacIgBYC7Wio1SdUU7JAFkKtaKjdqozygtaCLSiM2TnEFsHSpuz+hJcD82ek1GGGWWYUYYZZRhdB0qbo/oaXgedsptTHV8FDppzYAaSuhMDYQotoqdhXDGqAGIMPaKjUUaziikOBWMJrKKnoo5JAWQMvaKrUVwxxRSjCmUKrKKn4kgxKQBmCryiq+JIuRwBZwy9mmemmGLcKE0AaAs+oqNhhjv2WgJpDL2im0mNMsooDgFqCMuam2fnAmsMPaKjUUZJlTolA2wNvaKnUUYZZZRRHAJtCS6io2LqvwRuCS6ik3TstQRvCayip6KZFABwDD2ak2QVU0wzjwRxC72aZ6aYYtwoD3ILraKTVkYZ5ZEAcwqsojcy0mgkAHQNvaKXUR4xo4xiVAB1CC6io2TfKnYMLqIjVY4pp4wiAHcLLqKT0uqZcooAeAktoqNUXSUDeQw9mqNUTDHFqKMGegisojNicwh7CUubm2KVYx18Bkmb8wB9Ckubk2OdYhUBfgeUrpdUAgAAAAT//wA=";
export { u8g2_font_courR08_tr };
export default u8g2_font_courR08_tr;
