/* u8g2 official font: u8g2_font_streamline_interface_essential_id_t (701 bytes, 10 glyphs)
 * Converted verbatim from u8g2_font_streamline_interface_essential_id_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_interface_essential_id_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_interface_essential_id_t', font)
 */
const u8g2_font_streamline_interface_essential_id_t = "CgADAwUFAwIGFRUAABUAFQAAAAAAAqEwR7XS2rF0aCwdEkeJBotxkFQOjIOiolgtJAyd4jG1cCwai0li0VhElhoLx6KxeKwWFKWGQlK5HCiVg4LFaBwlDomlQ2PJADE4lfJas9osjhaJo8pR5ajheBwaS0eKw+KgOEgOi0PkwLgcJIfEMcfj4Gg8XpejylEjcbTYrDYCMkex2rp3tHBMIg9JRSmxWSQpDgoJo6GUNFEkIkmNpEhikWyS3GKSfAvFUlIkSaNIRBIHRkRpoZS0WSQUB4lisTpIHgeNpAAzSLXS+pA6XCqHyUHyODgaPKYdZGkHWih0MEViB5uIThLNQSPRJBoZiSbRyCgSmYMmodCmWIRKCYYkFVE0Do7LQXKYVA6vQwA0RrXS+pA6XCqHyUHyODgaPKYdZGkHWih2oEWCB6K6UBgHBYWRaCQojEQjwUgsDoqFgqFRMBaMBlOr6eC4HCSHSeXwOgQANT2x2rp3iFwoOklCNpHkGpFcI5JrRHKNSK4RyTUiiV4k0YskepFELxktoUjQEovEKtGIhBIPjeIgmRw6BzY+tdL6kDr8IIdJLvLYLRqtBqPVWDTTKB6a2EGHOuhQB1HuIModRImM4qFRNFu0GoxW025xyUUOO8jhdQgAN0e10roHOigOjMfB0bA8FpaII+FIZnEkRSqO5CiO5CiT5FEUkuQoisWDsmAoURgHBaWhjNKYLBiJhoOxqDEaB8fjwDjoQAU4SbXSugc66GCXA6WSA0UmcVGppFQolZQKpZJlQqlkmVAqWSaUkCTLhBKLTyjCUGhCmYMmTEkTNtlEhTyRSQ4UqRwoP9hBByoAOUCu3jqHSiVks8mhIqFIEodEJKGIKCILxkQhUUgUCQVFkVAkJIoEQ9JIkigYlCVKQrOIJA6JiIQiOfRwiBwqAAAAAAT//wA=";
export { u8g2_font_streamline_interface_essential_id_t };
export default u8g2_font_streamline_interface_essential_id_t;
