/* u8g2 official font: u8g2_font_4x6_mr (791 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_4x6_mr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_4x6_mr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_4x6_mr', font)
 */
const u8g2_font_4x6_mr = "XwIDAgMDAQEEBAYA/wX/Bf8BBQIIAvsgBnR8NgAhB3ScrB4DIgd0jKSdBiMLdIwkGZRkUFIAJAl0nGgRkykCJQh0jDSqpgAmCnScKIkqURICJwd0nCwnAigHdKxaYwIpCHSMMGvKACoJdIwkiqZKCisIdJwsmrIYLAd0fFqUAS0HdHxkhwEuBnR8WgwvCHSsLKrlADAJdJwoSZZSDDEIdJxIK60AMgl0nCjJomgFMwh0jC0KExk0CHSMpGWrAjUIdIwlExMZNgl0HCWTkigGNwh0jC2q5QA4CXQcpVRJZAA5CXScKIm0RAY6B3TcHIwBOwh03ByMMgA8B3SsxioAPQd0zHWHAD4HdIywVAc/CHQMMcpjAEAHdBylRxVBCXScKEmWrgBCCnQMKUmkJJEBQwl0nCipJVEMRAh0DCnpRQZFCHSMJZOyFUYIdIwlk7IcRwl0HCVLmlQASAh0jKRl6QpJCHSMKSutAEoIdKysUooBSwl0jKRFSloBTAd0jKxtBU0IdIwkuXQFTgh0rKSytANPCHScKOkpBlAJdAwpSaQsB1EJdJwo6SlMAFIJdAwpSaSkFVMIdBwlrMgAVAd0jClrBlUIdIykX1YAVgh0jKSXKQZXCHSMpOVSBVgIdIykqdIKWQh0jKQpKwNaCHSMLaqtAFsIdBwpq6kAXAh0jCyspQBdB3QMrUkGXgh0nCjJaQBfBnR88gJgB3ScMKcBYQd0XKWTCmIJdIxMSlpkAGMIdFwlC1UAZAh0rEjppAJlCHTcKEk0FWYIdKzSlMUAZwl0XKWkJRIAaAh0jExKegVpCHScWItWAGoIdKw8q0gAawl0jCxJpKQVbAd0DK1pBW0IdMwkWboCbgd0TCnpFW8IdNwoaYoBcAl0TClJpCwDcQh0XKWTlgByCHTMJJGyHHMIdFxFTGQAdAh0nGjKwhR1B3TMpCcVdgd0zKSnGHcIdMykZakCeAl0zCTKoiQFeQl0zKRJSyQAegh0zC2KVgB7CHSsklZMAHwHdJysMwB9CXSMMJOyKAN+CHScRMlpAAAAAAT//wA=";
export { u8g2_font_4x6_mr };
export default u8g2_font_4x6_mr;
