/* u8g2 official font: u8g2_font_sirclivethebold_tr (859 bytes, 86 glyphs)
 * Converted verbatim from u8g2_font_sirclivethebold_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_sirclivethebold_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_sirclivethebold_tr', font)
 */
const u8g2_font_sirclivethebold_tr = "VgADBAQEAgQFDQoA/gf+BQABGAJGAz8gBQBiBSEHcuOEkgAiCCM3RYhIACMSe+JOeFB4yEp4yEp4UHgIACQNeZ9moFpgYphiIAAlFnsjB0loUEgoSThYOFgIaUhQaAgBJg5Zo0ZRSFgIUkhwSAIoCFLjxEgUASkIUuOESJQBKw1Zo2Y4SGBiOEggACwGIt8EAS0GGatGAi4GEuOEAC8KhaPVUGA8DQEwCFmjxirVBTEGUuOEAjIIWaNGensCMwlZo0a6mPkCNAlZo4Yo6boENQhZo8Z6+gI2CFmjxvrqAjcHWaNGuhw4CFmjxmrrAjkIWaPG6voCOgdRo0RYADsHYt+EMAE9CFmjRjrMCT8OeaNGOkg4yDq0cBAAQBWdWoc7oEiKOFCISIpIeIgIO6ADQQp5o8YqaStVAUIMeaMGiihpK6kKAEMIeaPGutwTRAp5owaKKF1VAEUKeaPGuvi6eAJGCnmjxrr4unQARwp5o8a6FORhBUgKeaOGKNVWqgJJBnLjhANKCnmjRqK43MwASw55o4Yo1TYhMSExIQBMCHmjhri8J00SeaPGUhBREFEQURBREFGQAE4IeaPGKr0KTwh5o8YqXRdQCnmjxippu3QAUQt5o8YqJREyQwZSDnmjxippm5CYkJgQAFMKeaPGuni6+AJUCXhjBpqwvAFVCHmjhii9LlYKeaOGKK3rQAlXD3mjhiilIKIgoiCioAVYDHmjhihVkRNRqgJZC3mjhijVRXFpAFoKeaNGuni7eAJbCILjxEi8CFwIhaPFYHwcXQiC44RIvAxfBhmjRgJhCFmjRnrrAmIKeaOGuPgq1QVjCFmjxrr0BGQJeaO+eCvVBWUIWaPGansCZglZo8b6ujgAZwl5m8Yq1fUFaAp5o4a4+CqtAmkHcuOEkAJqCZMbjaCIXAprDHmjhrj4apuQGAFsBnLjhANtDlmjxlIQURBREFGQAG4IWaPGKq0CbwhZo8Yq1QVwCnmbxirVdnEAcQl5m8Yq1XUJcghZo8a67ABzCFmjxnr6AnQKeaOGuPi69AR1CFmjhiitC3YKWaOGKOk6UAJ3DlmjhlAQURBREFHQAngMWaOGKKnIiSipAHkJeZuGKK3rC3oIWaNGensCfAZxo8QBAAAABP//AA==";
export { u8g2_font_sirclivethebold_tr };
export default u8g2_font_sirclivethebold_tr;
