/* u8g2 official font: u8g2_font_amstrad_cpc_extended_8u (816 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_amstrad_cpc_extended_8u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_amstrad_cpc_extended_8u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_amstrad_cpc_extended_8u', font)
 */
const u8g2_font_amstrad_cpc_extended_8u = "QAMDAwQEAQEFCAcAAAgACAEBfgAAAxQgB4jj418AIQqI44l1h8uBACIKiOOoSWQSOT4jD4jjqElEp9JJIpPIYQAkDojjSUsRKVUSqsqBACUOiONDZBKRVJNEJgcBJg6IYw0lwhWVkdpEDgInCYjjidXxBQAoCohjSpXV1WEAKQqIY8mVVdWhACoNiOOD1EiHEE0kRwMrC4jjA8VCo1iOCiwJiOPji1gqBC0IiONjtOMKLgmI4+OLWA4ELwmI4+pzHAUAMBGI45RkEtFEEpGMJDJRHQYxCojjScc62kEAMg6IY9FEYhlNLBLZQQAzDYhj0WJi4VykRocBNA6I40mHEVlIdpTSYQA1DYjjmGQhOV2kRocBNg2IY9FEyjWRNjoMADcMiOOYYtKpsjoQADgNiGPRRNpoIm10GAA5DYhj0UTayiI1OgwAOguI46OK5XCxHAg7C4jjo4rlcLFUCDwJiGNKtWuHAT0KiOOj2RHtaAA+CYjjyLVqBwM/DIhj0URiqTpcDgRAEIjjlGQSCUVCkVDkdRgAQQyI40lpIk0m3UEAQg2IY9hEmmoiLXYYAEMNiGPRRBKxukhGhwFEDYhjFCUykb6I6kAARRCIY5xkIUmQKAnKIncQAEYPiGOcZCFJkCgJSulQAEcOiGPRRBKx0kQmsoMASAuI44j0ZNJ3EABJCojjGMU62kEASguI41HFSrrRgQBLD4hjjHSRESUykWQkBwFMDIhjUMXaQip3EABND4hjyCQrL5KImkQmBwFOEohjyCQjCUWFIprIJDI5CABPEYhjDSUimUQmkYkkwjkQAFAMiGPYRJqIYikdClESiGMNJSKZRCZRiYhkEzkIAFIPiGPYRJpqEplIMouDAFMMiGPRROp0kRodBlQMiOOYIpKgWCsdBlUKiOOI9L/RYQBWC4jjiPRvVDkQAFcSiGPIJDKJTCKJSC4rMjkIAFgRiGPIRBLhdCgRySQyOQgAWQyI44j0RhVL6TAAWg6IY1xkkphUKaRyBwFbCohjEcU602EAXAmIY8j1HgcBXQmIY5H1SIcBXgyI44WHEpFMjisAXwiI4+P3QwAAAAAE//8A";
export { u8g2_font_amstrad_cpc_extended_8u };
export default u8g2_font_amstrad_cpc_extended_8u;
