/* u8g2 official font: u8g2_font_streamline_money_payments_t (845 bytes, 13 glyphs)
 * Converted verbatim from u8g2_font_streamline_money_payments_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_money_payments_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_money_payments_t', font)
 */
const u8g2_font_streamline_money_payments_t = "DQACAgUFAwMGFRUAABUAFQAAAAAAAzEwOTXSdeNHynypNGIcKemMNspKozayYpVRTKo5U6ViRmVlozayM9ooqzRiHClpvtL4kfk1/uZ7/AExRrWStRlpOs/MWhlrKsMNM7Vh1BqnjaXaGWoyk2NzjSOqrMepNDWuSuMxlTTHquQaU0lzrEquMZU0x4ZyjU1Lm2tpnpoJMjOvnrXj0JmZ0jiUynRSGaZKZTqpcSjNpV6qL/XSXOql+lIvzaWOkVQ1RlLHSDUzj0MCM0iVsvX05qU1W05N2lIjKacVtdJSZaQ1SmOpsYYq90wxxbFkiinbKaaMbFSmDDdMMcVMxRRTTDnFFFNMOcUUx4+YeabxR+YrNDlT1rXjO+OMV6YyNXJNjTjjkWtqZCpTI1OZGn9oKlMjU5kaMcV45JoaMcV4ZCpTK+OMRxofenwCNUeVsvUj88pwM9uZjiujTKaMMsxUnBlqmGGN04g7UyPFDDM1M4qZ2iOjjEfmOTLPNUZmzcw9M3fKY2QyZZSZQ6NM3nAMTQI2OhXydeNDZ541XBvWqBoaJZ2qoZNM9ZBJKj1kkqkeMulUDZ00qoZGScO1YdI8UxofMvMlx488PhQANzIV8nXjQ2eeNc+aZ1LNKZPqRjEl1ZQjJdVGZUqymlXSPJPmmTTPlMaHzHzJ8SOPDwU4TLWS9VxDkyNnmHHGbZRx3jWOGdc47zQ0yjjGDfOuqVxzZZjh0HBomGHmyjJTuYYZzjR0RkPFjDOuRkYZt2HGGWWZccYZ5pHJobkAOUm1knWZzvTOVEYx89povDPKGeWMa1yjnMkcc2blNH6onFk55kzmjHLGNY4Zx0zWKGZWjeoalSmnNpIa5oxj5swaZb52ylwZAjpFlbL1Q1OZOnO5Z1uNzT7U0Ggsufa1VzrVWHGotGemx1Ljj0y1qXGkNI6MYo4ZaZR3RhplOiONMp2RRpnOqM50PT4kADs4s5a14ztzxzRGLpNKclZjpM6kVR3TGHHWzFQmq2dmzcrKZeaOmTuPb2amxw/NU/OU4xE1z/FDPDexmnXjjYaKQ+exa3bNK5NDZyrDGrcyzFvDGmuYt4YZRw3z1riVqQxrcujMK7Nrdh4PjcYbAQAAAAT//wA=";
export { u8g2_font_streamline_money_payments_t };
export default u8g2_font_streamline_money_payments_t;
