/* u8g2 official font: u8g2_font_streamline_users_t (682 bytes, 12 glyphs)
 * Converted verbatim from u8g2_font_streamline_users_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_users_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_users_t', font)
 */
const u8g2_font_streamline_users_t = "DAAEAgUFAwIGFRUAABUAFQAAAAAAAo4wQ3Xyega5QWqwGmwGA81gIBFpRJJYJhaJDWSR1GCQioQGR5mMSpMa5AYhTSKTyChSiUwiFcuFI5N0Kj+Qq7TJ2hAAMUGU8toGapU0GcwMNLHMYJBJRQYnoYxK0y7TIpPItMgkMu0yoUhkUpVJZWKZgWaWHMhUA4VuIBkk5INEfqBHLAAyPbHaugaDoE6kVeRFg0FIM7iRDA4kksGBRDI4kNhJJMmIJJFKRCSJVCIiSUYSkcikTSpTM9CkkrlKjXgHMy+y1toHeYQ+kZzUaYS7lCSRCmWqMq0ioSapTKtMUSoRUeWGGvUekYfkB/o8JAw0H6/eugZClSqZyUayibTXiWwkm0mmDAfiePFAHM8BNS+y1toHeYQ+kZzUaYS7lCSRCmWqMq0ioSapTKtMUSoRUeWGGvUekYfkE+V7RBg2MLLW+iHxRB6RnSSCGuEuJUmkQpmqTKtIqEkq0ypTlEpEVLmhRr1H5CH5gT4PCQM3KnP22gd6iB5RH0kNRJmMSpFL5rKxbCodSofSoXQoncrGsrlkUiUeKAE4PLLWeuYDVSYyGGQWC41mMEikQgNJKjXK5GLzTDhSmqnMVCYyiWQik0gmBopkYqCIDgbhgVqhVqgVWgA5RrXSWvOYgVwSkSp1oYEolhkMMqnM4CaUUWmKcqFIKJFJhBKbRCaRWYRyoUgoMgllQqlQ1UBVopLEEslETimVROQDPSYKOjey1nqWmtJEKhhJ5TKpjEWqLJMKroKZlKo0l8wlE5lEMpFJJBOZRDKRSUQVCXGiOlGdqB5oATs7s9ZaBurBILi4ygw0m0TFSpLJqBRJjXw0OMmkI7W5aKY0kUlEE5lENDFQRBMDRXYwSA/kifJE+UAMAAAABP//AA==";
export { u8g2_font_streamline_users_t };
export default u8g2_font_streamline_users_t;
