/* u8g2 official font: u8g2_font_robot_de_niro_tf (941 bytes, 113 glyphs)
 * Converted verbatim from u8g2_font_robot_de_niro_tf.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_robot_de_niro_tf.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_robot_de_niro_tf', font)
 */
const u8g2_font_robot_de_niro_tf = "cQACAgMEAQQFCAr/AAgBCQIA7AHoA5EgBYAoASEHqjtZOQEiBpNOSSojCq1rq4aqhqoAJAu8WlMbJZXRUgAlCK1r0SpXWiYJrFtTZVIxBScFkS4RKAe6OlOdASkIujqJqaUAKgabTkkdKwebTEsrASwGkjpTAC0Fi00ZLgWJKwkvB6tLrcoIMAerS6usCjEHq0uRrQEyB6tL0WkOMwirS9EjjgA0CKtLSWrEAjUHq0ubRwA2CKtLmyNVADcIrFvZceYEOAerSzvUAjkHq0s74gI6BpksSQE7BqI7ywo8Bpo8kwE9BptM2QM+Bpo8iQo/CKtLmSnDBEAMvWobWo2U1MhwBEEJNEpV1WppAEIKrFuZKck0EgBDB6tLm1UFRAisW5mpZwJFB6tLmyoORgq0WkkqyxwzAEcJrFtTOa2oAEgINErrWi0NSQapKxkCSgirS8sxLgBLCq1rUTFFnWIBTAesW9HNJE0JLmtJZerfAU4HrFuZqR9PB6tLW1YFUAmsW0mqkjkCUQisW4up5wBSCi1bSTJFnWIBUwerS5sXAFQHq0tZsQVVCKxbSf1MAVYHq0tJrgpXCq57SWn1Z1IAWAisW0nNqhJZCTxJUT11mQBaB6tLmakcWwe6OlldAlwHq0uJuQxdB7o6UV0DXgebTatUAF8GjFsZAWAGkj6JAWEHpFtTnSliCaxbyzJVKgFjB6NLm6kCZAm0W49RdakAZQikW1OVSgpmCTxJVVnmMgNnCbRZS6qpkwRoCbtLK6NKVgBpBqkrSQNqCDs5zbC5AGsJvFrJVVrNHGwJtFutkswxCW0IpntLqj8DbgejS6usAG8Ho0tbagFwCbRZSapL1gBxCbRZS6qpKwByCKRbSTHVEXMHo0trLgB0CLI7SWnFAHUIpFtJPVMAdgejS0lWBXcJpntJafVMEXgHo0tJqgN5CKtKSapeAHoIrFrZsaUAewm7SlMx5RgFfAa5KjkCfQm7SpF1ikkBfgeUXUsqAaMKvFpTMcVZjwCnC7xaUxmpmDRKCqkPx4obKkNLVSpLpWEaCq4Qx4obKkO1VGWqSsM0FAC2C657U0NFlVNOCcQKREqrsapWSwPHCLtJm1VSOdYJu0tJGS2rAtcIpFyJSaoY3Am8W6tRf6YA3wo8Sa2STEnWAOQJtFuroepMAegKtFvTWFUqKQDpCrRb01hVKikA6gu8W4spY1WppAD2CbNLSRkttQD3Ca1rzdTQVAT8CLRbq1GfKQAAAAT//wA=";
export { u8g2_font_robot_de_niro_tf };
export default u8g2_font_robot_de_niro_tf;
