/* u8g2 official font: u8g2_font_u8glib_4_tr (666 bytes, 96 glyphs)
 * Converted verbatim from u8g2_font_u8glib_4_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_u8glib_4_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_u8glib_4_tr', font)
 */
const u8g2_font_u8glib_4_tr = "YAACAgMDAQMEBQYA/wT/Bf8A0AGuAn4gBEAqIQVhKioiBtMzSQUjCu151VDVUBUAJAr1uXmMjMbIESUGZDaxByYJbHYxxSqNACcF0SsCKAbybaoZKQfyLTFVCioF0i4jKwdbcmklACwF0SkCLQXLMgMuBUkqAS8GZPaxDTAHYzIjqRExBmJuqwAyB2MyM6UBMwdjMiuPADQHYzIxjRg1B2MyQ48ANgdjMiOOATcHYzIzlQA4B2MyRxoBOQZjMucIOgVZKik7BeEpSTwFWm4yPQVbMns+BlouUQE/BmIuKgdAB2Q2Q+0RQQdkdiqOGUIHZDZryCFDBmNyMwtECGQ2K8qRAEUHZDZHyiNGB2Q2Q68MRwdkNkOnMUgHZDZxTBlJBWEqI0oHYzIzLgBLCGQ2caQoA0wGYzKxHE0IZTp5raQDTgdkNnGpGU8IZHYqyqQAUAhkNiuOlAFRCWU6I8UU0wpSBmQ2rzJTCGR2Q6OhAFQHYzIrVgBVB2Q20RwCVgdkNtFMClcIZTpZJdUFWAdjMqlMBVkHZDZx6CFaB2Q2I5YjWwbyLaslXAlkNhlllFEAXQbyLao1XgXTcw1fBcw1I2AF0i8xYQZbckcAYgdjMlGlBWMFWi5LZAdjsmklAWUHWzIjLQBmB2OyKa0EZwbjMWcSaAdjMlElFWkFYSpJagfqbTkpAGsHYzIxrQJsBWEqI20HXTqqpQpuB1syKqkAbwdbMiONAHAH4zEqrQhxB+NxK8kAcgZaLisBcwdbciopAHQHY3JpRQF1B1sySY0AdgdbMklVAHcHXTpZdQF4BlsyqQN5B+MxacQRegZbMjIKewfzcarMUXwF8SkHfQnzMTLHlBQAfgfUd0klAH8HbDZDmkMAAAAE//8A";
export { u8g2_font_u8glib_4_tr };
export default u8g2_font_u8glib_4_tr;
