/* u8g2 official font: u8g2_font_open_iconic_thing_4x_t (934 bytes, 19 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_thing_4x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_thing_4x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_thing_4x_t', font)
 */
const u8g2_font_open_iconic_thing_4x_t = "EwAFBQYGBAQHICAAACAAIAAASgAAA4pASiCICH5CJ7aRkatYpRaimAUpYmGKV6CiFapghSrMB/4AQTCEhwqhiAIRBCEEIghCCEQQhBCIIAghEEEQQiCCIIRAhVBEgfARAEEkIIgIVsx0IgQhSCACEoiABCIggQj0gf8fWIL3wZUP/B9AAEIeIIYMBv8A8cGRD/wfYAhBKEIQihCEIgT5wB+gAEM3IIgIngZWqBMhiBDiIYZwBxoaggiGIIIhiGCJKZhCjFWpSlnJShe6UqWoBb3ISW1iDGU/CgBEGhjICE4GVBqzHFWQIhWmQOQo+SMf+P8DDEVlHIgIjgZVIvOcZpCCGaZQBiKSkQhkKOIYizDGKoqximIsgxhCOAYxBFGMUghjGKUYxTAMMYphGGIUwzjEIIaBiEEIIxFjEcEhCDIGQxRjFIYoxDBMoQxUICMZxlhQc6BCDQcARisgiAhWxDYygtGyoY2IIfwnCPGFD/wDRMAEIRSioMQkCP2hxCQoMQkCAEcsIIgI7oEftpFNGLmITdWFrupykWxsQhZmiEcRYnKVul5V6kKXqqLLNTAASDXYxwhWQyWmEZGnNIYxy0kQgo5UKEINS9jCByxREbryBKI0gkCKKFAyDIOUYyAHSs5aDgBJNSCGDC5WwhAOEZBABCQQAQlEQAIRkEAEJBABCURAAhGQQAQkEAEJRECCMAgPfeAHnuAFAEpPIIgIVohlJPSkdphjGcpIhSsQAYlTwMIQkiiFLAhBCUJQghCUIAQlCEEJQlCCFLIohCRMAYtDQAIVzkCGStBhGJRLmEKIchOM5EMXAQBLFhTICAY/YDH0/z/2AUtEBCKR+IAETB0amAhehCVzTGuYs551kbv1LIc1jXGEJf+/BQBNSdyHCWaERaYilchAtiQUpgihIAphhCKOoBELSStSkmEEExiCESYsZCkIQRBCEIQQ5CREGQtZAkMw8gyDGGM4BSneYIYYoCABTkwciAhGAQ+2oIdMXMMeFDWVuEDmNSRQTQmQUwTjmKE4hhiOMURzjtAYJDAHCcuhzhKQwwTENOE4jTCMMwjzkME4RijPCYqTAtIMAE8ZGMcMTgZUGrMcVZAiFaZA5P/IB/7/AANQHiCICA5e+MAPHBj9//AHfuAIXkMwmqSWlTCEEQBRHdyHCSZTohCFpsZA9lPY0MIHMkZg8n9Z0EIDAFIaHIgIBn/gouj/f/QDH1hERjCSiQ98wAgAAAAABP//AA==";
export { u8g2_font_open_iconic_thing_4x_t };
export default u8g2_font_open_iconic_thing_4x_t;
