/* u8g2 official font: u8g2_font_tinyface_tr (662 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_tinyface_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tinyface_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tinyface_tr', font)
 */
const u8g2_font_tinyface_tr = "XwACAgIDAgMEBQj+/gX+BQAA1AGxAnogBEAqIQVVKisiBcovIyMHV7JDDQkkCVtyacihEgAlCFcyKaYyBSYIVzIqDqUAJwXJKwIoBlZuqgwpB1YuMSUFKgZPM6kDKwfPcmklACwFySkCLQVGLwIuBUUqAS8HV7JVGQEwB1cyI1kjMQZXMrI1MgdXMnPIATMHVzJzxBE0B1cySY1YNQdXMiMeATYIVzIjjjQCNwdXMjPFCjgIVzIjDTUCOQhXMiONOAI6BU0qKTsF8S1JPAXObjI9Bc4uUj4Gzi5RAT8IVzIzaZQAQAdXMkeSA0EHV3KHUgFCCFcyKq00AkMGV3KzHEQHVzIqWQtFB1cyI6o4RghXMiOqGAFHB1dyM6kFSAhXMkkNpQJJBVUqQ0oHH6k9FwBLCFcySa2kAkwGVzKxOU0HVzJpKCtOB1cyI7kCTwdXcstaAFAIVzIjDRkBUQfbccuaAlIIVzIqraQCUwZXcvMCVAdXMiu2AFUHVzLJNQJWB1cyyVUBVwdXMskaKlgJVzJppDRSAFkJVzJJjRQTAFoHVzIzlQNbBlYuqxJcB1cyMZcBXQZWLqoaXgXLcw1fBUcyA2AFyi8xYQZPckcAYghXMjGOtABjBU5uBmQGV7LVEWUHTzIjLQBmCFeyKa2YAGcHV3FHXABoCFcyMY6kAmkFVSppagc+aTlVCmsHVzKxWgVsBjYqqgNtBk8yRwpuB08yKqkAbwZPchcAcAhXMSOtGAFxBldxRyxyBk5uKgFzB09yKikAdAZSLmkJdQdPMkmNAHYHTzJJLQB3B08yaYwAeAZPMisNeQhXMUmNuAB6BtMxcwp7B1dyKskofAVVKkN9CFcyMqqkAH4GS3MjAQAAAAT//wA=";
export { u8g2_font_tinyface_tr };
export default u8g2_font_tinyface_tr;
