/* u8g2 official font: u8g2_font_fub35_tn (804 bytes, 18 glyphs)
 * Converted verbatim from u8g2_font_fub35_tn.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_fub35_tn.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_fub35_tn', font)
 */
const u8g2_font_fub35_tn = "EgAFBQUGBQYHJyoA+iP3JPoAAAAAAwggBgCA4BMqMlSyMbgMZEAFKYwhjFOIIhGCWIgJjGGQQIQPVMIQxTEasghBpEIUxxiFKUiBBjIUACsUvdNgvA16/F/7wAeyNujxfw0ALBiLkdqTHMQgBzGKQYxilKIYpTBFKQwALQnNkGkU/AAELgnHqOATfGABLyrxlF2VFYxgJUawslWwEiNYiRGsbBWsxAhWYgQrWwUrrYKVGMHKVsEAMEy5lB+XBVNpjoKQdKZymKMY6BhHMoahDmEsQxjLCMcywrGMcCwjHMv9lhGOZYRjGcJYhjCWIQx1iCMZxEAHOcxhJiMhSDlNoQEDADEYcKQgNx0IMUpZxges4AiGKOZI5///DzIwmZQgtwVzYU+KzlSqgRhkHOkQhjrCoQ55Fg95RASiYPLSueSlHvKSh0AkfuAPaDM/mJQg1yzrQZGZSDUOg4gDHeJIRzjSEU/wiIdLFsMUl7ylNRGRRzykIY/oKFc6AoIOcZxjVGQyEXrWIoUFADQ9eowgtyVQeSvHag0zwsGMcCxDHMsQhzLGkY5xJIMcyCgHMspxDHNmjHMUAx3kQAcx0kE+8A8E75jnIwA1NZiUHzdUo75xxPON4xxhKRSphiWSggjkHOJIRzDUEc9FRznpCEc6AnKOUQ2qSOhRTBQYADZNmZQgFynNURCSDFUOcxDkHONAhzjkSRryIMc5xFKO0JAjOOMSC0mCYpCQoCMgygiIelNHOJQhDmUIBB3jQMdAzFEmM50oOW2RAgMANy94lCAX/ANUPMEjHhCBB0TgARF4QNRDIPIQiMADIvCAqIdA5CEQeQhEXvIQBgA4T7mUH5cFslHRmUpFqpGURCAHEUc6xJEOcaRDHOkQRzrGcQ6ClONEyWnLgpBkkIIM5BzjSEc4lhGOZYRjudaToHQI5CDiGhWhTqSaKDAAOUmZlCD3LMxR0ZkKRRCDjAMdw0hIONQRDnWEQ71LSThQEpCyiEs84RhOOAgjDnOUQxryTBzoGAc6xnEQchTETEZCkHKaMoMGADoNB7sgFHxg+SD7gQUAAAAE//8A";
export { u8g2_font_fub35_tn };
export default u8g2_font_fub35_tn;
