/* u8g2 official font: u8g2_font_streamline_interface_essential_action_t (553 bytes, 10 glyphs)
 * Converted verbatim from u8g2_font_streamline_interface_essential_action_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_interface_essential_action_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_interface_essential_action_t', font)
 */
const u8g2_font_streamline_interface_essential_action_t = "CgAFAwUFAwMGFRUAABUAFQAAAAAAAg0wKnWydRooQ1qcWJFCRZpCKEYiYaJECBNMpiZDxBkTpMQIYgPvVZwZCgAxQ7WStThwYEbEEBFDRAwRMUQcMiHCDAoRRlKIKDOihIhCQUqECRIuSBhkKE6VEGGshIhyJT60iCEihogYY8SEESMAMkK1krVYYcSMiCEihogYH1qUKyHCWAkRp0okOxMkXJAwIQoFKSGizIgSIoykEGEGhYhDJkTEEBFDRAwRMcaBAyMAM0i1knU5IKtKhDhX5JwJcyFKmBNB4tQIEkmGWRmWhqRTIkqcElECWZESwkiEIBEOBIkShESICoFCRLAQJ8iJKGFsRBhUJA4ANDm0kjU6QChWoEih4gSLEkVOjCihIkQJFiZmMgdOBAwhMMKcQFUiBJoSI46UZKLECRUpUKxABygANTm0kjU6QChWoEhBosSJIiWZKTHCVIkQJsKcMCHkhQgY5sDNxOKEihBHToxwUYLFCRUpUKxABygANicx2rWhJaZGIBqRZoSSECJUiAjxdC9CiFAhIoiKMSkGoRhlZJEBNzq1kjUTGSFiiIghAoaIGCJgiIghohCKEERGCCERQggJQSSCEBFqCFGiBB0a4YQEFUlQhDwRAknKAjgnspa1iShw1oEQNILMiRBFkpRQAvVTUSRJiRBnSAwSB2INlBgGADkaVdI1OhA10SzeKxJsyLAg9S4GzWrUA4EAAAAABP//AA==";
export { u8g2_font_streamline_interface_essential_action_t };
export default u8g2_font_streamline_interface_essential_action_t;
