/* u8g2 official font: u8g2_font_busdisplay8x5_tr (923 bytes, 92 glyphs)
 * Converted verbatim from u8g2_font_busdisplay8x5_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_busdisplay8x5_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_busdisplay8x5_tr', font)
 */
const u8g2_font_busdisplay8x5_tr = "XAADAgMEAQQEBQkA/wgACAABNgJ3A38gBYDYACEGwai4BCIHk85IlAAjD8XoKSXJoJSSZFBKSQIkDcXoygYl2xKlskUAJQzF6FiUZMmalkQZJg3F6JEqUVKrJFKkBCcFka4QKAfCuFF6CikJwriIki4KACoInN2IEiUKKwqt6QqjQQojACwHmrhJFAAtBo3rGAQuBYmoCC8LxNgrZVEWZRkAMA3F6FmySUmkTUsWADEJxejKxJ4GATIKxehZsjDrOAgzDMXoWbIwWUMtWQA0DMXoy6SklAxaWAE1C8XoOIZDGmrJAjYMxehZMnFIMluyADcJxei4FbOwCTgMxehZMi1ZMluyADkMxehZMlsyhFqyADoGmapIAjsHornJFAA8CKzaUqIwFD0HnesY1EE+CKzaEEuJBD8LxehZsjAr5lAEQAzF6FkyJTkkh3QIQQvF6FkybRgytwBCDcXoGJJMG5TMNigAQwrF6FkysVuyAEQKxegYksy3QQFFC8XoOIZDEhYHAUYKxeg4hkMSNgJHDMXoWTIxGTJbsgBICsXoyGzDkLkFSQnF6BiksKdBSgvF6Bi0sEsUSQBLDcXoyKSkpCVRJdMCTAjF6Aj7OAhNDsXoyJYhWRIlURJNC04MxejIpiFRhmizBU8JxehZMt+SBVALxegYkkwblLARUQzF6Fkyl0RJpEgJUg3F6BiSTBuUUiXTAlMLxegZxHQNtWQBVAnF6BiksE8AVQnF6Mj8liwAVgrF6Mh8S2oRAFcOxejILImSKImSKF0AWAvF6Mi0pFap2QJZCsXoyGxJLWwCWgnF6BjEWsdBWwjDyBiingZcCsTYyMIszMIsXQjDyJh6GgJeB5vNqSgBXwaN6BgEYQqt6FmTQUuGAGILxegIG4ck0wYFYwqt6FkyMUsWAGQKxejsMmhaMgRlCq3oWbJhSIcAZgvF6JIq2aCEbQBnCq3oGbRkCAcFaAnF6AhbTJotaQm82Im1ligBagrE14u1mpQoAGsLxegIm5ZIS6JIbAjDyIj6UgFtC63oUFqUREmUAm4IrehITJotbwmt6FkyW7IAcAqt6BiSbFDCEHEJregZtGQIC3IIrehITGIRcwit6BnUgwJ0C8XoCWuDEpYiBXUIrejInBQldgmt6MhsSS0Cdwut6MiUREmULgB4Ca3oyJJapRZ5Cq3oyLRkCAcFegit6Bi0tkF8BsGoOAh+CJ3ryZJaAgAAAAT//wA=";
export { u8g2_font_busdisplay8x5_tr };
export default u8g2_font_busdisplay8x5_tr;
