/* u8g2 official font: u8g2_font_synchronizer_nbp_tr (899 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_synchronizer_nbp_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_synchronizer_nbp_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_synchronizer_nbp_tr', font)
 */
const u8g2_font_synchronizer_nbp_tr = "XwADAgMDAwQEBwYAAAYABgABIwJPA2cgBQDxASEHMfExJAEiBxv3kVgCIwst81MZlMqgVAAkCzXxMyjZlgxaBCUJLfEhLVllEiYLNfGzpIOURNECJwca96EoACgHMvGjNAUpCDLxESUVBSoKLfNVqSxNEQArCi3xFUaDFEYALAca8aEoAC0GDfUxCC4GEvExBC8HLfGZdQQwCzXxs0RLMmnJAjEGcvGzdDILNfGzZJGUhYMAMws18bNkkaolCwA0CzXxl0lJMmhhAjUKNfFxHNJwUAA2CzXxs4RDkmnJAjcJNfExiFmxBDgLNfGzZMmSackCOQs18bNkWjKEyQI6CDLxMYRDADsIMvExRIoCPAcr8ZXUCj0IHfMxqIMAPggr8ZFVSgA/CTXxs2TtUARADDXxs2TKkCRKZQhBCzXxs2TaMGRaAEIMNfExJNmgZNqgAEMJNfEziK1DAEQKNfExJJnboABFCjXxcRySMBwERgk18XEckrAIRws18TOIyZBpyRBICjXxkWnDkNkCSQk18TFIYdMgSgk18ScWtWQBSws18ZFJSWmqZAFMCDXxEXYcBE0LNfGRLUuiJJoWTgs18ZFNSiJtWgBPCTXxs2RuyQJQCzXxMSSZNihhCFELNfGzZJZEipQAUgs18TEkmTYopUhTCTbxM8zmYQFUCTXxMUhhJwBVCTXxkXlLFgBWDTfxkSZZlFXCJM0AVwo18ZFZEiW5BVgKNfGRJbVKTQtZCTXxkSW1sAlaCDbxcew4DFsHMvGxtAhcBi3xkXZdBzLxobQMXggd95UltQBfBg3xMQhgBhL5EQVhCi3xsyaDlgwBYgs18REmJk0bFABjCC3xM4jVIWQKNfGZmDYtGQJlCi3xs2TDkA4BZgo18bVkgxLWAGcLLfEzaMkQDgoAaAk18REmJs0WaQex8ZEMAWoKNfGZQ6GWLABrCzTxkUVKIiWlAGwHcvGh9ABtCy3xobQoiZIoBW4JLfGRmDRbAG8JLfGzZLZkAXALLfExJNmghCEAcQkt8TNoyRAWcgkt8ZGYxCIAcwgt8TOoBwV0CTXxkw1KWB11CS3xkTkpSgB2Cy3xkWlJKckiAHcKLfGRWRKlCwB4CS3xkSW1Si15Cy3xkWnJEA4KAHoJLfExaG2DAHsIM/GV1KIsfAVx8XF9CTPxkVWiJAJ+CB3zkyW1BAAAAAT//wA=";
export { u8g2_font_synchronizer_nbp_tr };
export default u8g2_font_synchronizer_nbp_tr;
