/* u8g2 official font: u8g2_font_IPAandRUSLCD_tr (950 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_IPAandRUSLCD_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_IPAandRUSLCD_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_IPAandRUSLCD_tr', font)
 */
const u8g2_font_IPAandRUSLCD_tr = "XwADAgQDAwQFCAcAAAcABwABMwJxA5ogBQBiBSEHcSPFoAQiB6N2RaIEIwtVok1lUCqDUgEkCnWiVTaoBy0CJQp1ooU0ZZ0mASYOdaJNlkRJpkhJFCkBJwah9oQAKAjzYlVSqhUpCfNiRVaqlAAqClWqRVLZsqUBKwpVplUYDVIYASwHsiKFogAtBhWuxSAuBpHiRAAvCHWiZa1jCDAMdaLNkklLMmnJAjEJdaJVJnYaBDIKdaLNkoVZ2yAzDHWizZKFyaolCwA0DHWiXSYlpWTQwgQ1C3WixTEcUi1ZADYMdaKVlIVDkmnJAjcKdaLFINaKJQA4DHWizZJpyZJpyQI5DHWizZJpyRBmkQQ6BjEnRRI7BsIiTTY8CFWmnSKlBj0INarFoA4CPglVpoWqRooGPwx1os2ShZGWQxEAQAx1os2SKckhWbIhQQt1olWW1IYhswVCDXWixZBk2qBk2qAAQwp1os2SiW3JAkQKdaLFkGTeBgVFC3WixTEckjAcBEYKdaLFMRySsAhHDHWizZKJ0aYlQwBICnWiRWYbhswWSQp1osUghZ0GAUoJdaJlRy1ZAEsNdaJFJiUlLYkqWQBMCHWiRdjjIE0MdaJFtiyJkmi2AE4LdaJFNimJtNkCTwp1os2SeUsWAFAMdaLFkGTaoIRFAFELdaLNkrkkkjIEUgx1osWQZNqgZLYAUwt1os2SqauWLABUCXWixSCFPQFVCXWiReZbsgBWCnWiReYtqUUAVwp1okXmkijJLVgLdaJFpiW1Sk0LWQp1okVmS2phCVoKdaLFIGYdBwFbB/IixdJFXAh1okWYdgxdB/IihdJlXgk4clachFkUXwYVosUgYAazckVWYQtVosWQJoOWDAFiDHWiRRgOSWYbFABjClWizZKJWbIAZAp1omVl0GzJEGUKVaLNkg1DOgRmC3WinRRGgxSWAGcLVaLNoCVDOCgAaAp1okUYDknmFmkJdaJVPjYNAmoLdaJlDoWhliwAawt1okVYk5KpkgVsCHOjRdSbAG0LVaKF0qIkSqIUbglVokVi0mwBbwlVos2S2ZIFcAtVosWQZIMShgBxCVWizaAlQ1hyCVWiRWISiwBzCVWizaAeFAB0CnWiVRgNUlgVdQlVokXmpCgBdgpVokVmS2oRAHcKVaJFpiRKcgt4ClWiRZbUKrUAeQtVokWmJUM4KAB6CVWixaC1DQJ7CnMijRIlWRQJfAbx4sQhfQpzIoVUS6JEAX4JNbJNltQSAAAAAAT//wA=";
export { u8g2_font_IPAandRUSLCD_tr };
export default u8g2_font_IPAandRUSLCD_tr;
