/* u8g2 official font: u8g2_font_chroma48medium8_8u (796 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_chroma48medium8_8u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_chroma48medium8_8u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_chroma48medium8_8u', font)
 */
const u8g2_font_chroma48medium8_8u = "QAMEAwQEAQEFCAcA/wb/BgABcwAAAwAgB4jhxxEAIQmI4Y3LPhgAIgqIYQ0JColHDCMPiGENibEJCQqJsQkJBSQNiGFJVBJIGFIUEgolDojhlAkRCctEJEYSACYQiGGVComSCokIiQmaiAQnCIhhjotHDSgKiGEOi8swFgApCojhDYzLLBgAKg6I4YxINFQ0FJEeBgArC4jhjYuqiouHAiwJiOFHFRcWDS0IiOEHtUcDLgiI4ccsGAAvCIhhD8tzADAQiGGliRFJERIREiITQwoxCojhDZPLqhQAMgyIYaUJiouhibMEMw2IYaUJChoMCYohBTQMiOEdConJjVkoADUMiOE0iSsMCYohBTYNiGGliasJCgmKIQU3CojhtAvLLhgAOA6IYaUJiqEJCgmKIQU5DYhhpQkKCYqpiyEFOgqI4QeKB4yHAjsKiOEHigcMiwY8CohhDkuYHggAPQmI4QcxtQcFPgqI4Q1Mlh4KAD8KiGEdiglLHwxAEYjhlQqJiZAIiZCICYmSBUEPiGGlCQoJCjEJCgmKBEIOiOGsCQqpCQoJCikFQwyIYaUJColLFEMKRA+I4awJCgkKCQoJCikFRQuI4TSJI4qLswRGCojhNIkjiksORw6IYaUJCokLGQmKIQVIEIjhDAoJCjEJCgkKCYoESQqIYR2Ly2wWAEoLiGGPyyQohhQASw+I4QwKiYkhikkUEhQJTAmI4YzLnSUATRGI4QwKURIhERIUEhQSFAlOEojhDAqRCYkIySIkRiQoEgBPD4hhpQkKCQoJCgmKIQVQDYjhrAkKCQqpiQsHURCIYaUJCgkKiQjJIoYUAFIOiOGsCQoJCqnJKBIAUwyIYaUJJAwJiiEFVAmI4ayKyzEAVRCI4QwKCQoJCgkKCYohBVYQiOEMCgkKCQoJigmJkgVXEYjhDAoJCgkKiZAIURIUCVgPiOEMigmJEpMKiQmKBFkMiOGMCYoIi8sYAFoJiOE0y5klAFsKiGGdistuFgBcCIjhDMxLAF0JiOGdy9UoAF4JiGEOi4hHDF8IiOHH9iAAAAAABP//AA==";
export { u8g2_font_chroma48medium8_8u };
export default u8g2_font_chroma48medium8_8u;
