/* u8g2 official font: u8g2_font_open_iconic_thing_2x_t (486 bytes, 19 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_thing_2x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_thing_2x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_thing_2x_t', font)
 */
const u8g2_font_open_iconic_thing_2x_t = "EwAEBAUFAwMGEBAAABAAEAAAJQAAAcpAJRCS8Ikma1SISEHiBo158EAII0ZCiAgSQkSQECKChBARxAkAQRUQknCZRChIoCBBD/6BeUge/IAAQhOQ0TB8IB6SBz8wIkSJkAcPFEMbEJJwEkVIRBwhYYSEFRm1aBEjVeiSGbUpAEQQDJowkTM1ZJCkcvLgHxhFKA6SMJI0N2TUIEGjxIwaMmrICCFTTCNExCAhpYSQEDNq0JhhB4sBRhkQknCJJkxaJCO+EPHggQsRRQrRUZFCAEcWD5Zwhx5KaUGThQUOEVe0SpOVkgVIGQyacIUVSc4UIjRKVDxYomSNCUFkUJkBSRuQ0bAwYiRQkEBBAgUJFCRQkEAhhhg9eIAASiUQkjCZRDdolEAxA4cIFSJUiFAhQoUMFCRQ1KBSrEwUJi0CAEsOCpowPDhG/+xBECQOTBIMlnAJFWbq1JJVp4wJlV8BTSDusbANJWnQkBAjD4KoQmOEiRGKiBAxgmLICEFCBAFOIQ6SMIUWPHZoQUsCHRFyZoShEWbUmBhkYswRIWiCnABPD8zZMJEzNWSQfPLgHxhQEhCSMHxAmH784AExwiRVMQFREO6xsChSZtBWLJwJls8AUg4OkjB8Sv/0wREmDwoAAAAE//8A";
export { u8g2_font_open_iconic_thing_2x_t };
export default u8g2_font_open_iconic_thing_2x_t;
