/* u8g2 official font: u8g2_font_fub11_t_symbol (814 bytes, 45 glyphs)
 * Converted verbatim from u8g2_font_fub11_t_symbol.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_fub11_t_symbol.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_fub11_t_symbol', font)
 */
const u8g2_font_fub11_t_symbol = "LQADAwUEAwQGFxAA/Qv9C/4AAAAAAW4gBQCIJSMZaosrQ0KRUBQ7iBRFUYnsEBNFJdKQEAAkF8hrKqMliyhCihWtxAgpUolIrOIYACUfb4uxiMHJSCgTRWUS6YheidQr44hMKpFJQ5NhsAImFWuLraqToUw4mTZJVtQqwhHbQQAnB4L8Jw4BKAqja2ZUKPokUSkMo20nJJKJvlwkACoKptxqaCKTjAIrFCmPMOOQOCQOCR6EcUgcEocEASwJg2plJBQJAC0HRLomDgEuBkKMJQgvDqVr59RiasGYWkwtCDAPaIupaCKJkB8lIhkJADEKZYvpJIeRTD8yEWiLqUqTiUwsnQpptOH0EDMRaItpSpOJTCyjy4m0iY0ENBNpiymnjBLZRCZSEx0OVLkIADUQaIspLmLly2gsph1GJQA2EmiLqWgTUZAsoYyKjBKRjAQ3EGiLKQ5h6VQ6lU6li0MAOBJoi2kso2JpRBNJhIylEQkAORJoi6loIomQWJqcxTSRZEYCAAAABP//A5QYaolq46A4ZBwRh8IhYUwYFEVF4UMBA6kZbYkty1JhPCYXyUVykVwmFcVEogdSAQO8FmlbKmQimUgmkolkIplocpjU1QEDwBMIi2oOkVAwFAwFQzFRTFQbIDAqdou4iHHgZCQHykRxqEwih47o8EqkVK9YxhEZTSqR0aShiWUYLFUAIDkLxJpmJpIl0QAgOgzEmiZkoslECQAgRBFni6mj0qhQGpVGhdIwACEiD4n6KiYqIYkkNEmKJCICE8d7aOaZk0Qj4mIkJokFgwAiDyDtaS4OlgNNLBPLxDKxTCwTy8QysUwsE8vEMrHEVCIRHuprLA4ScUgOkoPkEDlIDopD4qA4JA6JQ+KHByISCCrOMA4DIhoYaYnpIfE4JA6JzIKxaCgaCsvlkBgAIh4Sq65wZpNYJCYMyiKxiFQCIisN51ko16Th/LchACJIDaqucIhCOpQopAAiYBLqrvBDh2kcEj2M4pA4BAAiZBIqj/Ah0uFUDprD5rA57DAiZRIqjzDiMDpsDpMOp3LEwwAlyhaHi6mkkVgolhKMRBVDsVBiJBoDAA==";
export { u8g2_font_fub11_t_symbol };
export default u8g2_font_fub11_t_symbol;
