/* u8g2 official font: u8g2_font_squeezed_r7_tr (743 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_squeezed_r7_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_squeezed_r7_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_squeezed_r7_tr', font)
 */
const u8g2_font_squeezed_r7_tr = "XwACAgMEAQQEBQgA/wf/BwAA8gHlAssgBYCoACEGuagMFSIGk80kFSMKrelVQ1VDVQAkC73o5qHyTkNHACUJs8ikmGKKKSYJvNjF1KwqVScFka0IKAe6uKnOACkIurjE1FIAKgeryaRqNSsHm8qllQAsBZGnCC0FirsILgWJqAQvCLvIVrGKETAIu8hVXhUAMQa6uK0eMgi6uMSUVBIzCLq4qCSTAjQIu8gka8QGNQi6uKyYkgI2CbvIlVElVQE3CLvIzCq2ADgJu8hVqqUqADkJu8hVKskqAToGoanEADsGqadEATwHq8mmugA9Bpq7SAE+B6vJ5KoEPwi6uMSkcgJACLzYqWjdaEEIu8hVaigrQgm7yKikVlILQwe6uKnOAEQIu8io5LUARQi6uKy0kgBGCLq4rLQqAEcIu8jNykoCSAi7yCRrKCtJBrmoHAFKBrq49RpLCLvIJGslK0wHurikXgJNCb3o5LWSdgdOCLzYxKWmM08Iu8hVXhUAUAm7yKikViwBUQe7yFVeSVIJu8iopFayAlMIuripmJICVAe7yKzYC1UHu8gkXyNWCLvIJK8yAVcJvehkr6S6AFgJu8gkVaZkBVkIu8gkq2wBWgi6uKikKgFbB7q4rC4BXAi7yMQc6xhdB7q4qK4BXgWTzTVfBYq4CGAGkr3EAGEHq8gtKwliCbvIxKiStQBjBqq4qTJkCLvIVstKAmUHq8hVQwtmB7q4qdUCZwizxy2V5AJoCLvIxKiSK2kGuaikIWoIwrfl1FIAawi7yMRqJStsBrmoHAFtCq3ojFSppJIqbgeryKjkCm8Hq8hVVgVwCLPHqGStCHEIs8ctK8kAcgiryKQVSwBzB6q4yaQAdAi6uKS0ygB1B6vIJNcIdgeryCTXAncJrehkK6kuAHgIq8ikMiUVeQmzxyQryZQAegequCiVBHsIu8immGQdfAa5qBwBfQm7yOQYVUwRfgeU3SWVAAAAAAT//wA=";
export { u8g2_font_squeezed_r7_tr };
export default u8g2_font_squeezed_r7_tr;
