/* u8g2 official font: u8g2_font_streamline_social_rewards_t (721 bytes, 11 glyphs)
 * Converted verbatim from u8g2_font_streamline_social_rewards_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_social_rewards_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_social_rewards_t', font)
 */
const u8g2_font_streamline_social_rewards_t = "CwADAgUFAwMGFRUAABUAFQAAAAAAArUwTJWyNf4hpyrDQVuUHMwSJZmTUEm2i5Js0ZQoeZIlUZJMSZq0RmmkJFOSJu1JlkRJHk2JMgzJtujYMg0HZRgSHRyGHB+GHF92XNMAMS+vnnWGhySHdViHdVjHIh1adGTSsk1aRm1QxVnNdViH5VhNUjELtTST8ijRIQUyNLOWdXRSnRLlJJ2WE4dBB/Mcy4dTrie5nuR6kutJrie5nuR6MhzyJN2R8nCIcmJOzGkAM0K1kvWRQcdVHdMhPYfTnBLmlCzcxigblEFLsmGQNm04JJo2HBJNHA6iOlyTdBjSKB7kLJ7DvJrDuQ7pmKrjg44ANDZztvWhnJbklCzHhnSI03KYhHGYhGm0aTU5S0JxTDI5K4lTmoxRHA5ZnIPxkA45VqfUaTkENUW1kvWRQcdVHdMhPRfTPArLWZhFSxZH0ZAlW5KtWaatg6aNNW0dNC0Ja0mUpEMWRUMYZZXDkIU5Jc3hXId0TNXxQUcANjy1kvWxnJrkxCSn1UlZTklzPM2RYR+WnJrkSZ7psJy1Q9mWYzmUQzmYI2k9TdI4zMI0U7UwyqGqDmoAN0e1kvWxnLoTd9qSk5acMkQ5PkQ5MhyyYVmnYVCGUBmzQRo0eRhCHTrsWKYMOZRNQ45EQ7ZHQ5LNyZBlajKkkjjkUKLqoAY4SpSytYYcGbJQMUaJFmVKlAxJlAxJNijDIdOmTYmGB0mbtyEZpEFZkiGShiSK5qk0SINUmqSpNE+leYqUeRGHeMgRdUclnaRDADk4spY1hx0OdbSO1sE4x/Icy8M6Eok5UspypLZDSU7RSbKiqsMQqsOQJfEgRvEYqmGeIzk0DCoAOkJV0vWhnVYnJXVIzVIlUVdFikuJlCVZZFmyZJGSQR2UKNqnWliL8iSPhkEbBilSoooUDYM2DFKe5FGO5Eg2fJAAAAAABP//AA==";
export { u8g2_font_streamline_social_rewards_t };
export default u8g2_font_streamline_social_rewards_t;
