/* u8g2 official font: u8g2_font_streamline_interface_essential_expand_shrink_t (512 bytes, 8 glyphs)
 * Converted verbatim from u8g2_font_streamline_interface_essential_expand_shrink_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_interface_essential_expand_shrink_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_interface_essential_expand_shrink_t', font)
 */
const u8g2_font_streamline_interface_essential_expand_shrink_t = "CAAEAgUFAQEGFRUAABUAFQAAAAAAAeQwKbVe/2AP0mMSeUg9IpMPxfOgPCjPozwoD4qH8pk8IpKHJPIYPWiwBzE0tV7zYCAOZoPhQSieSmci4Ywkm0lEspHGIj1QJI60jSQy2YgmHMmkU/HQIBzMBsODgRgyVbVex2CgGQwUwURQmAiKBplBSJVLSTKpTMSmRiJJZBKZRETSItJCpBHpgSKNSBFpESmRJDKJTCJiE9FIJJlUJqLKpUSDzCAkTASFiWBiMNAMBgoAMy61Xj8qD8qD8qB4KJ/JIyJ5SCKP0YMGe/hgD9JjEnlIPSKTD8XzoDwoD8qjADQ0tV6zSBxpG0lkshFNOJJJp+KhQTiYDYYHAz1wMBAHs8HwIBRPpTORcEaSzSQi2UhjkRg1W7Veh0gjUkRaREo0iUgiksgkMpJERNMkEcmkKlKhQSgRGiSCiaAwEUwMBprBQA8cDDSDgSKYCAoTwcQglAgNQqlEqiaSiGRqJImIZpOIJCKJjKRFpIVII1IANju1XkMelMhDMpFkJJVIJnJK2SA5iA70g0F6cKxYiAfHioV4sx4M8gPpIDmIKXWJZCIVSUYyeUgiDwo3OLVew+VgoIcs8glJOqLJZkTJUCyXTuUzeUgiD8qDEnlIJp9K52KhZEiTzUjSEUU+sYcMBsrBAAAAAAT//wA=";
export { u8g2_font_streamline_interface_essential_expand_shrink_t };
export default u8g2_font_streamline_interface_essential_expand_shrink_t;
