/* u8g2 official font: u8g2_font_open_iconic_arrow_2x_t (639 bytes, 28 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_arrow_2x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_arrow_2x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_arrow_2x_t', font)
 */
const u8g2_font_open_iconic_arrow_2x_t = "HAAEBAUFBAQGEBAAAA4ADgAADwAAAmNAD+ppwiRQ/pEKNKbICQJBEk8lwxRa8FiiD14QHi08KABCEk8hwxpc9GASD56SHSw6EABDD+opwiSOlBkUigTKPwJEHxAiwmVQFSEyhYoUKmGII8RFD5IgRqRQmSKlFJoCRSAQIsJlUFUJM0WOkDlBaC1hwmUNoSBzpMiZEqYUmgJGHxAiwmVQlYkyR4qcIYHIbGFqF5E4Q+RIGROlFJoCRx8QIsJlUFWRMoWKECNB8GhhRByZKFSkUBlCpBSaAkgRCi7CQ4z+jYokh4oNDAQASRNQ4cIVXPRgFw8ehHhCerhQAEoTUOHCKnw0kRcPHoRwPFp4KABLEQouwhRwWKEjKdQQo38DAEwO7mTD4IKNKnQmyQoDTRTHdcIWStAYIiUelDBShtAoYQFOFcdxwhBM1CAyRUw8KFGEzCBRwQBPDe4kwyaWpDlUalg4UBQuJcMhUASxRCWKlFGFziRZYQBREMltwiaMUJk6KlVXxEQAUg/JbcIhjFQ9KlNHxIQBUxQuJcMmlqQ5VGqKlCiUjIRAEQBUExAiwkaYXqpDaZa0eJg+eCAAVRMQIsLwgXiYiiZrEp1KwvQMAFYa0KHCHF6MixdChQgND2FQIUJFvHAjPjAAVxqQocImmOxocYLEkRHGTAw5QeJEjyUsDABYHxAiwsKIkUBBAoVLJMyIOCLkhBgTJFxCQQIFcQIAWSQPIsIcXMS4VEbGjBA0YkiwsoOJlhwiJNCYESJIpSssOggAWhaQIcMaXvhogqmYdENqkDhBAkOFB1sc0KHCYNRYGHEmRC1KISaJmGBhhMtQkEBBHAEAAAAE//8A";
export { u8g2_font_open_iconic_arrow_2x_t };
export default u8g2_font_open_iconic_arrow_2x_t;
