/* u8g2 official font: u8g2_font_open_iconic_other_6x_t (866 bytes, 8 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_other_6x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_other_6x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_other_6x_t', font)
 */
const u8g2_font_open_iconic_other_6x_t = "CAAFBgYGBAQHMDAAACoAKgAARAAAA0ZARJ7rCY+BHuCCPaSJcgEb3SOLqElUaV7M5VjO5VjOxVyO5VyO5VzMZSqogiZqoiLs4R6uARtwIRM0QQ/2YAt4oAciAEFsMIkOn4oPIJBuyRjLmZ7IQIyncIqWkImFsIiEwAh00Idz4IdySAMzSAdyQAVSQAdiQAZiQIZxOAiBOAdhOJRjEAZjMYZwMBbTOJbDMBjDMBjDMBhjYBiMlS3aalO65EM+QDg+gDA+ABkqAEJkKowINwZpUAqnOAzGKA7lGBAEERAECRJDPiMJEAQREAQZDuUoDMY4CqdQBmlgBmlgBmlgBmlgBmlgBmlghnhgndZpHLd5GoiRiA8Iis/ojg3RkCzB0ssQDdmOzviKDxgGDwBDWKqKDgcGY2QYxsgwjJFhGCPDMEaGYYx94I8YjJFhGCPDMEaGYYwMwxgZhjH2gT9iMEaGYYwMwxgZhjEyDGNkGMbYB/6IwRgZhjEyDGNkGMbIMIyRYRhjRHcwjAgHDMMwGMMwGMMwGMMwGMMwGMMwGMMwGMMwGMMwGMMwGMMwGMP0gX+JYRgGYxgGYxgGYxgGYxgGYxgGYxgGYxgGYxgGYxgGYxgGY5g+8C8xDMNgDMNgDMNgDMNgDMNgDMNgDMNgDMNgDMNgDMNgDMNgDBNFFjCMCAcSRv7/Y5IP/P8nJYz8/8ckRpoqjAj/gGL4gGL4gGL4gGL4gGL4gGLABmPABmPABmPABmPABmPABmPABmPABmPABmPABmPABmPABmNgBmPEDMaIGYwRMxgjZjBGzGCMmMEYMYMxYgZjxAzGiBmMETMYg2EYI8MwRoZhjAzDGBmGMTIMY2QYxsgwjJFhGCPDMEaGYYwMwxgZhjEyDGNkGMbIMIyRYRgjwzDGAEexMIwIn4oPIJBuyRjLmZ7IQIyncIqWkImFsIiEwAh00IdzWIZ1KIfESAdyQA50IAYEQYZxOJJzEIZDOQZhMAmSMIZwMAd0MI1jUIbDMAd1MAxjYAbDMAZmMAxjYAbDMAZmMAxzUAfDOAZlOA1zQAdzCAaTIAljEIZDOQZxOJJzGAYEQQZyQA50IIfESIdyWIZ1OAd9QAiMSAiLWAmZaAqneAzEiJ7JsZhs6ZAPIIoJAAAAAAT//wA=";
export { u8g2_font_open_iconic_other_6x_t };
export default u8g2_font_open_iconic_other_6x_t;
