/* u8g2 official font: u8g2_font_spleen6x12_mu (820 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_spleen6x12_mu.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_spleen6x12_mu.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_spleen6x12_mu', font)
 */
const u8g2_font_spleen6x12_mu = "QAIDAgMEAQEEBgoA/wj9Cf8BeQAAAxggBtb8/BEhCtb8SNo7mEMAIgvW/EmWZEnOGwAjEdb8cBINUpIlWRINUpIjACQR1lzhkNSScEyyJEuSIcwAJQ3W/FjUkoZpErVjACYN1vyIFrXZokSLlhgnCNb8SFrnESgK1nxamPYcKwApCdY8crXHTAMqDNb81CiThkmLchgrC9b85DQbtDSnACwI1vx8SsMQLQjW/JwGnREuCNb8/JJDAC8M1pxpmIZpmIZpCjAQ1vxTlkRKi5RkSRbtCAAxCtb8SKj2uCMAMgzW/FOWlqY0HXQAMw3W/FOWZnKaZNGOADQL1txpqadBTHMENQ3W3IOSpkOcVoYcATYP1vxTmg5RlmRJFu0IADcL1tyDkqVhtR0COA/W/FOWZNGUJVmSRTsCOQ7W/FOWZEkWDWlpRwA6Cdb8rDlTDgE7Ctb8rDktDUMAPAnW/FjYGrcDPQrW/GyDPuhUAD4J1vxxa9iOAT8M1vxTlobVHMwhAEAP1vxTlmRJsiRLssRDDkEQ1vxTlmRJlgxKlmRJlgNCEtbcQ5QlWTJEWZIlWTLkCABDCtb8Q5L2POQARBLW3EOUJVmSJVmSJVky5AgARQzW/EOSpkOUloccRgzW/EOSpkOUtoMARw/W/EOSVpYsyZIsGnIASBHW3FmSJVkyKFmSJVmS5QBJCdb8Y9rjjgBKCdb8Y9qbjgFLD9bcWZIlUbRFtSRLshxMCNbcaZ+HHE0P1txZYhmUbkmWZEmWA04P1txZIiVS0k9KpGQ5AE8Q1vxTlmRJlmRJlmTRjgBQD9bcQ5QlWZIlQ5TWQQBRENb8U5ZkSZZkSZZk0aoAUhHW3EOUJVmSJUOUJVmS5QBTDNb8Q5LGc1oZcgRUCdbcg5b2HQJVEdbcWZIlWZIlWZIlWTTkAFYQ1txZkiVZkiVZkkXbjgBXENbcWZIlWZIlLYNiyXIAWA/W3FmSRUlYibIkS7IcWQ/W3FmSJVmSRUNaGXIEWgrW3IMadk0HHVsK1jxDlPbrkABcDNYcaZzGaZzGaQJdCdY8Q9qfhgReC9b8SJhEWc4TAF8I1vz8OigAAAAABP//AA==";
export { u8g2_font_spleen6x12_mu };
export default u8g2_font_spleen6x12_mu;
