/* u8g2 official font: u8g2_font_profont12_tr (977 bytes, 96 glyphs)
 * Converted verbatim from u8g2_font_profont12_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_profont12_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_profont12_tr', font)
 */
const u8g2_font_profont12_tr = "YAADAgMEAwQEBgsA/gj+Cf8BQwKKA7UgBQCiAyEGQaPjEiIHm7ojsQQjCy2upzIolUGpACQPVZ4rWypKtiVRolS2CCUORaJnUBKlm6QoiZQAJg1Fokeq1CpRkkiREicFGbtjKAjTnisp9VYpCdOeIyv1UgIqCi2uq1JZmiIAKwotpiuMBimMACwIoppjSBQALQWLrmMuBhKjYwgvDFWasxZmYRZmYQgwDUWiZ8mkJZk0LVkAMQlFoisaexoEMgpFomfJwqzjIDMMRaJnycJIDbVkATQMRaIvk5JSMmhhNjUMRaLjGA5pqCULADYMRaJnCcMhyWzJAjcKRaJjEGvFJgA4DEWiZ8m0ZMlsyQI5DEWiZ8lsyRBWFgA6CDKjYwiHADsJwppjCIdEATwHvKYvamw9CB2uY1AHAT4IvKYjbGoDPwtFomfJwlodigBADkWiZ8mUIUmUIUyHAEENRaIrS6Kkpg1DpgVCDUWiY0gybVAy26AAQwpFomfJxG7JAkQKRaJjSDLfBgVFC0Wi4xgOSVgcBEYKRaLjGA5J2AhHDEWiZ8nE0qYlCwBICkWiI7MNQ+YWSQpFomOQwp4GAUoKRaKzo6YlCwBLDUWiI5OSkqYlUSULTAhFoiPs4yBNDEWiI1uWREk0twBOC0WiI5uURNrcAk8KRaJnyXxLFgBQDEWiY0gybVDCRgBRCk2eZ8l8qawBUgxFomNIMm1QMrcAUwtFomfJ1DXUkgVUCUWiY5DCPgFVCUWiI/NbsgBWDEWiI3NLSkkWRgBXCkWiI/OSKMktWAtFoiOzJbVKTQtZCkWiI3NLamEJWgpFomMQs47hIFsIUp9j6RcBXAzVmiNMwzRMwzQMXQjSnkPplwFeCB22K0tqAV8GDprjAGAGkr4jCmEJLaJn0EyKEmIMRaIjLA5JZhsUAGMJLaJnycR0CGQKRaKzZdBsyRBlCi2iZ8mGIR0CZgrEokuJpqwTAGcMPZpn0GzJECYLAGgKRaIjLA5J5hZpCMOiJ5daBmoJU5orlzotAGsLRaIjbEpKUyULbAjDokPqywBtDC2iY0gqSqIkSgFuCS2iIzFptgBvCS2iZ8lsyQJwDD2aY0gy26CEIQBxCj2aZ9BsyRAWcgktoiMxiUUAcwktomdQDwoAdAnEoicrTVlRdQktoiNzUpQAdgstoiPTklKSRQB3DC2iI0mUREmULgB4Ci2iI0tqlVoAeQs9miNzS4YwWQB6CS2iY9DaBgF7CtuaK4lasqgtfAZRn+MhfQvbmiOL2pKoJQJ+BhWyxwV/BQCiAwAAAAT//wA=";
export { u8g2_font_profont12_tr };
export default u8g2_font_profont12_tr;
