/* u8g2 official font: u8g2_font_streamline_internet_network_t (566 bytes, 10 glyphs)
 * Converted verbatim from u8g2_font_streamline_internet_network_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_internet_network_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_internet_network_t', font)
 */
const u8g2_font_streamline_internet_network_t = "CgAEAgUFAgQGFRUAABIAEgAAAAAAAhowSLWKNQ7keoh0EAqr0olQaqBJZFKZVSS0GIgSoUFkIBINNCPRQJMIiQaxkGgXSoQki1AklRioMonMQBVKpFPi0CCqh8gHQgAxKdXJde4RGnUum4xGVetMKJFJhBKxVEyVyCRSepBwkJPKInlEaPBBBjIwtYo16EF70B50PMlod9lddraajDJlk1QiOFTupDPtSryJhGeDA8ketAftQXuQADMus4417qn26IHkQJHb6Xa6nW6nGgxSsoFMtxMG9RA9ZPD/xeADYSadCg8GMQA0LrOOdeYh+4F6MMgNMgeJ3E630+10Oz1Et9NDdDs9RA8Z/H8x+ECYSafCg0EMNTCzjjXuqfZUe8R2cpVahVKrUGYwyIRCA1HVKhQrSocG3+Qj+URup4ckBh9oBp8ANjK0ijUNDoTZXDaXzWUSNblsLpvL5gYPYulUOhSbZfKZwQeiwcd5UB6UxywHA83gcAk3MLOOdeYh+4F6MIjvEdvJVWoVSq1C6VBqFUqHUqtQOjT4Jh/JJ3I7PSQx+EAz+AQ4OLWK9Q70MD0sPsojMpHBQJfRaiLSSIk0UqKViSLhPCoTioVCg1woHxp8IBp8oBp8m8mn4oNBEjlRtYo1DuSKCqkkE9FlUplUYpAaJEKRyEBSE8lGIoMfJAZ/oFgkFomDRH8xSPQXA0VikVgkDn4QqY1kIpGBpCgxSA0SqUwqk5NkIlJFhXwgBAAAAAT//wA=";
export { u8g2_font_streamline_internet_network_t };
export default u8g2_font_streamline_internet_network_t;
