/* u8g2 official font: u8g2_font_logisoso62_tn (982 bytes, 18 glyphs)
 * Converted verbatim from u8g2_font_logisoso62_tn.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_logisoso62_tn.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_logisoso62_tn', font)
 */
const u8g2_font_logisoso62_tn = "EgAFBQUGBQcHJEoA/D7wPgEAAAAAA7ogBgCAQDQqPnq7a7QyqBkLjnECMhSjDKMgBinEIQxxhA9UwioUghjDIEQVS3ygCocwxCEKYpBiDMUoAwmOcQJmUDMFACsTGMNMNEIg+qEP/AcMhED0QwAsFIjBvKsghhE+EARjFGVUBCMIAC0KGMFUNPgfMAAuEAjBwKsghhE+EARjEAIAL0/er0B0TVWkpipSUxWpSUUsUpOKWKQmFampitRURWqqIjWpiEVqUhGL1KQiFqlJRWqqIjVVkZpUxCI1qYhFalIRi9SkIjVVkZqqSE1VADA836dANDtqA6M2rSpdJysbUY4ylKSIZCUhaUhAHvz///9/DwlIQ0SyEqEkZShHIVvJzpWqNbUINvVgADEd0O9ANEI7KaMqC2HEB34ACc1YCoLQ//////8BMlHfr0A0O2oDozatKl0nKxtZyjKUpIhkJQJpSEBc9OB7UUvC0RJRvGQMLyFBTGrKJjWpSk1VpaaqUlM2qUlVaqoqNVWVmrJJTapSU1WpH/g/M0Tfrz80+H9Vqamq1FRVaqoqNVWVmqqqysxGPhB60IvqYpObXBRGLvo/E7yEEC0ZB0uCkhTBFGZsRTMYshTFItjYwgE0Rd+nQLRCLppFLppFLppFLppFLppFLuoeF+0eF+0eBVFIQRRSEIUURB0GSYhBEmKQhBgkHQdByEEQchD0gf97yEX/QwA1SN+nQDT4fwC56P+KwZDQJOxkRisb4UYnmrKIJSlBWUlIGhIQFz3YQy76dx8IPdiLGiKSlQglKUM5CtlKdq5kqalFsKkHAwA2Vt+nQPRCagOjNq0qXScrG1GOMpSkiGQlAmnRg7vorxgMCU3CTma0shFudKIpi1iSEpSVhKQhIWnRg//vIQFpiEhWIpSkDOUoZCvZuVK1phbBph4MADdB36dANPh/AHGxlgSkJQFpSUAaIhCWiKMlNrGITauJTauJTauJTVnEplnEptXEptXEptXEpixi0yxi02piUw4AOGDfr0A0O2oDozatKl0nKxtRjjKUpIhkJQJpSEAe/O8hAWmISFYilKQM5ShkK9m5UqWqdJ2sbGQpy1CSIpKVCKQhIWnRg/8eEpCGiGQlQknKUI5CtpKdK1VrahFs6sEAOVjfp0A0O2oDozYtC10nKxtRjjKUpIhkJQJpSEAe/P9cEpCWhGQpQUmLWEojusGRrWgmO1hqArIQglz0CwaEHuxFDRHJSoSSlKEchWwlO1ey1NQi2NSDAToaaMTIqyCGET4QBGMQH7xADCN8IAjGIAQAAAAABP//AA==";
export { u8g2_font_logisoso62_tn };
export default u8g2_font_logisoso62_tn;
