/* u8g2 official font: u8g2_font_wedge_tr (791 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_wedge_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_wedge_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_wedge_tr', font)
 */
const u8g2_font_wedge_tr = "XwACAwMDAgMFBwYA/wX/BQABAgIJAvsgBYCsACEGqpyYAiIInbZIlJQCIwmvxKku1aUCJAm0q4Y1VIYAJQmuvIiUrCIFJgquvI4yKE2iJCcGmp5UACgHq6RRSgEpCKukiJJEASoJrbSG1SRRAisJrKyJEiVKACwGmptQAS0FzLYQLgWSnBAvCbSrqkRJFAEwCq20TdIhSRMAMQittE2RrCoyCK200JCoLDMIrbTU8WwBNAittE7ReAs1B6203LUFNgmttE0ypZoANwittNSiWgQ4Ca20TapJNQE5Ca20TSpamgA6BqqckAQ7B7KbkBUAPAesrEpqBT0HnK3QEAE+CKysyColAD8KtbNNalFGSgBACa20TRIbmgBBCa20xpN0SAJCCa20UJIlWQBDB6ysleoBRAittFASywJFB6ysmJNIRgisrJiTKAJHCa20TbJESQRICa20SNQhUQJJCKysUKKKAEoIrKyNygoASwqttEhUNEqRAkwHrKyImgRNCa20xNMhUQJOCe28hNQhkQFPCa20TRJLmgBQCa20UBJlyQBRCrWzTRJLoqEAUgittFASZSlTB6yslWQFVAisrFCiFgBVCK20SFzSBFYJrbRILGkOAVcJrbRI1CHNAVgKrbRIlDRJlABZCq20SJQ0yiIAWgisrJCSkgBbB6ukVKoBXAm0q4iyKIsCXQerpEyqAl4HnbbGkwJfBYyrEGAGmp5QAWEIpbRNEqUKYgmttMiURFkAYwekrJXyAGQIrbRLFiURZQiltE1SPQFmCKyslZMoAmcJrbNZEi1NAGgIrbTIlMQSaQaqnIgGagizo8mQigJrCK20yCpLAWwHq6RImgJtCqfEWFJERbQAbgiltFASSwBvCaW0TRIlTQBwCa2zUBJlyQBxCK2zWZREC3IHpKyYSgBzB6Ss1VAFdAerpEiVKHUIpbRILIkAdgmltEiUNIcAdwqnxMhUREVSBXgIpbRI0jgpeQqts0iUREsTAHoGpKyQDHsIrKxN0igOfAaymxwFfQmsrIziJE0AfgeWvU3SBAAAAAT//wA=";
export { u8g2_font_wedge_tr };
export default u8g2_font_wedge_tr;
