/* u8g2 official font: u8g2_font_tinyface_te (713 bytes, 103 glyphs)
 * Converted verbatim from u8g2_font_tinyface_te.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tinyface_te.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tinyface_te', font)
 */
const u8g2_font_tinyface_te = "ZwACAgIDAgMEBQj+/gX+BQAA1AGxAqUgBEAqIQVVKisiBcovIyMHV7JDDQkkCVtyacihEgAlCFcyKaYyBSYIVzIqDqUAJwXJKwIoBlZuqgwpB1YuMSUFKgZPM6kDKwfPcmklACwFySkCLQVGLwIuBUUqAS8HV7JVGQEwB1cyI1kjMQZXMrI1MgdXMnPIATMHVzJzxBE0B1cySY1YNQdXMiMeATYIVzIjjjQCNwdXMjPFCjgIVzIjDTUCOQhXMiONOAI6BU0qKTsF8S1JPAXObjI9Bc4uUj4Gzi5RAT8IVzIzaZQAQAdXMkeSA0EHV3KHUgFCCFcyKq00AkMGV3KzHEQHVzIqWQtFB1cyI6o4RghXMiOqGAFHB1dyM6kFSAhXMkkNpQJJBVUqQ0oHH6k9FwBLCFcySa2kAkwGVzKxOU0HVzJpKCtOB1cyI7kCTwdXcstaAFAIVzIjDRkBUQfbccuaAlIIVzIqraQCUwZXcvMCVAdXMiu2AFUHVzLJNQJWB1cyyVUBVwdXMskaKlgJVzJppDRSAFkJVzJJjRQTAFoHVzIzlQNbBlYuqxJcB1cyMZcBXQZWLqoaXgXLcw1fBUcyA2AFyi8xYQZPckcAYghXMjGOtABjBU5uBmQGV7LVEWUHTzIjLQBmCFeyKa2YAGcHV3FHXABoCFcyMY6kAmkFVSppagc+aTlVCmsHVzKxWgVsBjYqqgNtBk8yRwpuB08yKqkAbwZPchcAcAhXMSOtGAFxBldxRyxyBk5uKgFzB09yKikAdAZSLmkJdQdPMkmNAHYHTzJJLQB3B08yaYwAeAZPMisNeQhXMUmNuAB6BtMxcwp7B1dyKskofAVVKkN9CFcyMqqkAH4GS3MjAaAEQCqhBXUtaaIIV3JpxJUAowdXcqWKA6QG17LrBKUIVzJJVSsBpgV1LkoAAAAE//8grAhXclNlAQA=";
export { u8g2_font_tinyface_te };
export default u8g2_font_tinyface_te;
