/* u8g2 official font: u8g2_font_kibibyte_tr (676 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_kibibyte_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_kibibyte_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_kibibyte_tr', font)
 */
const u8g2_font_kibibyte_tr = "XwACAwMDAQMEBQgA/gX+BQAA1gG+AoggBEA2IQZpKlMAIgbTM5EUIwpteik1KEkpACQJ+3EROVIRACUIazJRWEYBJgn7cdEYiVQEJwXRKwIoB2ouU0oAKQdqLlJqACoGWzNRDisHW3LRFAEsBdEpAi0FyzIDLgVJKgEvCGuyUZgKATAHazKUigAxBWkqBTIGai4SJTMGai7SAjQHazKRRCY1BmoukzQ2BmsyJEU3BmouUg44BmsyVEU5BmsyFEk6BlkqUQA7BuEpkQA8BlpuYgA9Blsy8wA+BlouoQQ/B2ou0hgBQAlsdlIozZAEQQdrMpRUBUIIazJSNEUEQwdrMpQYEUQIazJSpJoARQdrMqQUDkYIazKkFIYARwdrMmQkEUgIazKRVEkBSQVpKgVKB2syY5IASwlrMpE0RVIATAdrMmHmAE0KbTpWJEVSJCVOB2sylFYATwdrMpSKAFAHazJUGQJRB2w2U74IUgdsNqWVDFMGazLkSFQHazJTmAVVB2sykRYBVgdrMpHWBFcLbTpRJEVSJEUGWAhrMpGUJQVZCWsykUSFEQBaB2syY5QcWwdqLlNKAFwHazJxmA5dB2ouUmoAXgXTcxlfBUw2BGAG0i9hAGEGWzJSRGIHazJhSBFjBlsy5ABkBmuyYUVlBlsykThmCGtyoxSGAGcGazEUSWgIazJhSEkBaQVZKgNqB2otUmoAawdbMtGUAGwGWi5RJG0HXTpWJCVuBlsylBRvBlsyFAFwB2sxVBkCcQdrMRSZAHIGWzJkCHMHW3JSJAF0CGtyYTSFAnUGWzKRRHYHWzKRNAF3CF06USRFBngGWzJRDnkHazGRRBJ6BlsyYih7B2pukRgFfAV5KQd9CGouUShFAH4I3XpxlI4AAAAABP//AA==";
export { u8g2_font_kibibyte_tr };
export default u8g2_font_kibibyte_tr;
