/* u8g2 official font: u8g2_font_victoriamedium8_8u (736 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_victoriamedium8_8u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_victoriamedium8_8u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_victoriamedium8_8u', font)
 */
const u8g2_font_victoriamedium8_8u = "QAMEAgQEAQEFCAcA/wf/BwABaQAAAsQgBojh5wghCIjhyXUfBiIIiOHI9J4YIxGIYakZbCKhSCiSGWwiUQAkDYjhiQ0ywWFmEAsDJQqI4czEusljACYRiGFRRUKRlCqSKMoMEkkAJwiI4cnVkwMoCYhhitUV1gIpCYhhCdaVVQMqDYjhSSWKDkSjRFUYKwuI4c2lBqpcHgUsCYjhp8rF0gAtCYjhhw72NAAuCIjhp5ZpAS8HiGGP9RwwDohhGWVKNIkaSaZoCzEKiOGJ6boaSAEyDYhhGWVyKVUsN5ACMwyIYRllcilhpmgLNA+I4VElQpFQJDSQxaYANQ2I4RhocoNgLlO0BTYMiOFRxXKDUKbRFjcKiOEY6GJ1jQE4DIhhGWUajTKNtgA5DIhhGWUaDXKxlBg6CYjhzQPzaAA7CojhzQNzsTQAPAiI4Yo1bAo9Cojhhwymgz0UPgiIYQk2aw0/C4hhGWVyKVk+DEAUiGEZZEKJiEUkoYgkJINIcBABQQuIYRll2gw0fQpCDojhGIQybQahTJtBFkMLiGEZZerahLYARAuI4RiEMv2bQRZFDYjhGGhyuVUuN5ACRgyI4RhocrlBKFcORwyIYRll6iKajrYASAuI4cj0ZqDpUwBJCYhhmeU62wJKCYjhynVTtAVLEIjhyJSEEilZIhUJZaIATAmI4cj1biAFTQyI4chkFJpETX8KTg6I4ci0kWQSNRFNpwBPCohhGWX6R1sAUA2I4RiEMm0GoVw5AFELiGEZZfqLomEEUhCI4RiEMm0GoUQqEspEAVMMiGEZZQqHmaItAFQJiOEYqHI9BlUJiOHI9D/aAlYLiOHI9I8SsTAAVwyI4cj0FzUKTSkAWA2I4cg0SsQqQpmmAFkLiOHI9CgRyxUDWguI4RjoYt0NpABbCYhhWeW62wJcB4jhDPYSXQiI4dn1agpeC4hhiiVCmTwtAF8IiOFnOxgIAAAABP//AA==";
export { u8g2_font_victoriamedium8_8u };
export default u8g2_font_victoriamedium8_8u;
