/* u8g2 official font: u8g2_font_osr21_tn (537 bytes, 18 glyphs)
 * Converted verbatim from u8g2_font_osr21_tn.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_osr21_tn.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_osr21_tn', font)
 */
const u8g2_font_osr21_tn = "EgAEAwUFAwUGGRwA+hX5FvoAAAAAAf0gBgAQogAqGooZuyQ4JyQTUhIiUzY0ESExEkKTSHAGACs4OJfpHA8YDxgPGA8YDxgPGA8YDxgPGA8YDxh78GA4HjAeMB4wHjAeMB4wHjAeMB4wHjAeMBYALAwEeaEwcRCTSRIALQdH+K7wAC4KhBiiIXEQIQEvHYlbtZhOLjBdYDq5wDi5wDi5wHSB6QLTyQUGAjAtzvbFRSgUJhYVJyMYIygiKDEoMSgxKDHoUGJQYlBEUERQRE5ILJWciKgYADEOqh7GFqhu5m7/vzkYMiCsGsZTFiUSKBFIWHc1MTUSJjkpGam7CMGISLKDBwYzJcz6xVMlNCI2MSZBJTI1KSo5IyRkLCs6OSF2dVUnISYzIzcFNCGuGsYZLLuUsjJiUGIwZC5mTGYsaCpqSGro4G52hwcDNSCs+sUhFnMQdBWbiyo1cSJxopMrxK6uzCTERsKEbgA2Ksz6xUUmFBUlIzQiNSIlI7mEZiJGhEqCSmLMswmxCTGRKRkhKRFBKQA3F6v+xfDBoKRgRGBoZNLISIWSCul4BDgtzvrFZCYlJCcyKDEoMSgxKEEXUxR1EHglYiNVMTcx6FBiUEQwZkxKRnIMADkrrPrFRCYUJBYjJjEmMSYx5mxCbEKKREZChkZUNEZKZEpkKkZKRirKCAA6D8QZoiFxECEPK3EQIQEAAAAE//8A";
export { u8g2_font_osr21_tn };
export default u8g2_font_osr21_tn;
