/* u8g2 official font: u8g2_font_open_iconic_weather_6x_t (594 bytes, 6 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_weather_6x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_weather_6x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_weather_6x_t', font)
 */
const u8g2_font_open_iconic_weather_6x_t = "BgAGBgYGAgQHMDAAADAAMAAAPwAAAjZAPzCpwy9E2RAhHmWzZJgrc2mqTcWZOpPnCTGkpaSYkhOCOlQGi2gJLuEVvIIf8AMkwTuhRbAK1YFKTE3IAABBXzAswhdE2RAhHmWzZBhswkU8COgQm0bGgogWSeNRJJAmgVCWxGFREAcmORwZhZBoEoGyqThTZ/I8IYa0lBRTckJQh8pgES3BJbyCV/ADfoAkeCe0CFahOlCJqQkZAEJR7mvCn8A6SAto4TyYiDJBKo0LkSlshI7v6YN4kE7CSbjJNtkoWiWzYJcLY2UsDcWRPpDIIAisQUWoCpSBOkwJaRE1oMcjaSoMRukcpGECAEN+MCzCL0TpCCEeZbNkmCtzaSoOxZk6k+cJMaSlpJiSE4I6VAaLaAku4RW8AomBUkpMJWg4lIABTQIGNBEIDaFZEAHH4CQmw3OgDFChMkQDy/ARDsNBmAyGkWQwjCSDYSQZDCPJYBhJBsNIMhhGksEwkgyGkWQwjCYCQtQAAERZbnvCLQErtBJUotSAGp0IE6lUkEojI3IFrEFVoBDSImpAj0fSVJjLklE2CSfZKBpVZsEUggJLEIkrYSQsBIKwDIyhMjgGqgAVKIJEmAbWQBJgAimgBRIARW4wLMItwmpQja2EjqARGgNmYAyYgTFgBsaAGRqCRuAMJ2N0hJBP0lE2i2blEA7MQQgMBsZgGBiDYWAMhoExDAHhwBwEx6JZbZRO8kFCx8g4DRxBIzQGzMAYMANjwAyMATM0BI3QEVaDamwlWAAAAAAE//8A";
export { u8g2_font_open_iconic_weather_6x_t };
export default u8g2_font_open_iconic_weather_6x_t;
