/* u8g2 official font: u8g2_font_tallpix_tr (870 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_tallpix_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tallpix_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tallpix_tr', font)
 */
const u8g2_font_tallpix_tr = "XwACAgMEAgUEBxD+/Az8C/4BDQI4A0ogBQBhAyEHYaHySAEiBxMvk1QAIwpDIZPUUGooFSQMUx+XRpJTqZESACUKQyGTYhVTrAImCUsf18s1YgAnBRGvIigKax2bYop9xxwpC2sdk2OOfcUUASoHGy+XVgIrBxsnl1YCLAURnyItBQspMy4FCaESLwljHdsVW7EJMAljITOS/xoBMQZhofIBMgljITPjkH0OMwpjITPjiH2OADQJYyGTrBH7AzUKYyEzYpx9jgA2CmMhM2Icya8RNwdjITP7HzgKYyEzkhrKrxE5CmMhM5Iasc8ROgdBoZJxADsHSZ+SsQA8Byslm+oCPQYbJ7MHPgcrJZOrEj8LYyEzUkwq9oYJQApjITPSUL6GHEEKYyEzkhrKXwFCCmMhM5Jaya8RQwljITOS7K8RRAljIaOS/1oARQpjITOSHLGvEUYKYyEzYhyxnwBHCmMhM5Ls5RoBSAljIZOsofwVSQZhofIBSgljIdufSo0ASwljIZOslfwVTAhjIRP7zwFNE2WhcyWVVFJJJZVUUkkllVQBTghjITOS/xVPCWMhM5L/GgFQCmMhM5JfQ5YAUQtzHTOS/xopJgBSCmMhM5JayV8BUwpjITOSnMrXCFQIYyGzYv8FVQhjIZP8rxFWCGMhk/yvClcTZaGTkkoqqaSSSiqppJJKqgtYCWMhk6yWvwJZCWMhk6yyvwBaCmMhM1uxFcsBWwhrHTNi/zlcCWMhE9uxHRtdCGsdM/vPEV4GEzHXAF8FCx0zYAYS7xIDYQpDITNSHMoaAWIKYyETmyP5GgFjCEMhM2LPAWQJYyHbHMrXCGUJQyEzYhyxHGYJQyEzYhyxCWcKYxkzkq8RyxFoCWMhE5sj+RVpB1GhksYQaglzmJph/zkCawpjIRO7rJVcAWwGYaHyAW0ORaFzJZVUUkkllVQBbghDITOSXwFvCEMhM5KvEXAKYxkzkq8hmwBxCWMZM5KvETtyCEMhM5LsCXMKQyEzkpxKjQB0CWLhklqrlwB1CEMhk/waAXYIQyGT/KoAdw5FoZOSSiqppJJKqgt4CEMhk6yWK3kKYxmT/BqxHAF6CUMhM6uYYhx7Cmsdm2JXjt0BfAZ5m/IDfQprHZNjd4pdEX4HFGmXVAIAAAAE//8A";
export { u8g2_font_tallpix_tr };
export default u8g2_font_tallpix_tr;
