/* u8g2 official font: u8g2_font_5x8_mr (983 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_5x8_mr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_5x8_mr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_5x8_mr', font)
 */
const u8g2_font_5x8_mr = "XwIDAgMEAQEEBQgA/wb/BgABQAKOA7sgBsX6vAIhCMX6YTuUAyIKxdpJlERJzgAjDcU6pSQZlMqglJIYJAvFWtlS25JkywElCsXaYZJVwhwEJg3FOlkSJVklSrIkBicHxfphnQUoCMX6WdiaAykJxdpp2JYjACoLxfpYFElDJJUBKwrF+mgYDVKYAywHxfrMWg0tCMX65CEnAS4IxfrM2RYBLwrF+kiYNeYQADAMxfpZEiVREiVZDjEIxfqZ2DYDMgrF2lIxksIhBjMLxbpDlqlJFOkANAvF+pmUREMW5gA1C8W6QxKuSRTpADYKxdpSOFWiSAc3C8W6Q5iFWZgjADgKxdpSSapEkQ45CsXaUiWKxkgHOgnF+qCmI5oOOwnF+qimI1oNPAnF+khWTMsAPQnF+pQhHnIQPgnF2mkxqyMAPwrF+lkSZjmUA0AMxVpSJC2JkkhVBUEMxdpSJUqGJEqiGEIKxbpTZapEyQ5DCsXaUiUsRToARAzFulMlSqIkSnYARQvFukMSTmE4xABGCsW6QxJOYR0CRwvF2lIlTJQo0gFIDsW6URIlQxIlURLFAEkIxdpb2DYDSgrF2ltYSrIcAUsMxbpRUtKSKInKAEwIxbphxyEGTQ7FulEyJEMSJVESxQBODsW6UaIkQ5IoiRLFAE8MxdpSJUqiJIp0AFALxbpTJUqmMIcAUQzF2lIlSpSKpCYAUgvFulMlSqZKFANTCcXaUmtU0gFUB8XaW9gdVQ3FulESJVESJVGkA1YMxbpREiVREkWaDlcOxbpREiVRMiRDEsUAWAzFulESRZpUiWIAWQrFupmW1MI6AFoKxbpDmDUOMQBbCMXaU9g4A1wIxbph2hgDXQfF2mOnGV4IxfpZkrMCXwfF+tyHBGAHxdppzgxhCsX6pCVKomgGYgrFumE4VaJkB2MJxfo0KUxlAGQMxfpIGC1REkUzAGUJxfokKTHqAGYLxfpZEmVbmCMAZwrF+iSpNEYSAGgLxbphOFWiJIoBaQnF+jki1mYAagvF+kgOhaUkiwBrCsW6YSmZKlEMbAfF2mK3GW0LxfoUpUVJlCoAbgrF+pSpEiVRDG8KxfokqRJFOgBwCsX6lKkyhSEAcQrF+qQlisYKAHIKxfqUklLMIQBzCcX6NEmNdAB0CsXaYbaFSZYDdQvF+pQoiZIomgF2C8X6pCRKoiTLAXcKxfqUTEmUzgB4CsX6lCjSpDIAeQzF+pQoiaIliiQAegrF+pQhqw0xAHsKxVpSGqlZKgN8B8X6Ye8AfQvFGmqWSmmkIwB+CMXaSTszAAAAAAT//wA=";
export { u8g2_font_5x8_mr };
export default u8g2_font_5x8_mr;
