/* u8g2 official font: u8g2_font_4x6_tr (722 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_4x6_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_4x6_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_4x6_tr', font)
 */
const u8g2_font_4x6_tr = "XwACAgMDAgQEBAYA/wX/Bf8A6QHTArYgBYDNACEG6cisACIGk8skFSMKrMikNFQaKgEkCbPHpaFHSgAlCKvIZNRGASYJrMjFFKuYAicF0csIKAfyx6lmACkIssfEVCkAKgeryKRqNSsIq8jFtGICLAaSxykALQWLygwuBcnIBC8Hq8hWZQQwCKvIVUNVADEHq8glWQ0yB6vINVMaMwiryMyUFwA0CKvIJDViATUIq8iMqBcANgeryE3VAjcIq8jMVEYAOAeryK3WAjkHq8i15AI6BuHIxAA7B6rHZagAPAeryKa6AD0Gm8nsAT4Hq8jkqgQ/CKvI6JRhAkAGq8gtW0EIq8hVQ6kAQgiryKi00gJDCKvIVTJVAEQIq8ioZC0ARQiryIyo4gBGCKvIjKhiBEcIq8jNpJIASAiryCQ1lApJB6vIrFgNSgeryJaqAksIq8gktZIKTAeryMTmAE0Iq8ikMZQKTgiryKqhJABPB6vIVVYFUAiryKi0YgRRB7PHVVYdUgiryKi0kgpTB6vI7bwAVAeryKzYAlUHq8gk1whWCKvIJGukBFcIq8gkNYYKWAiryCTVUgFZCKvIJFVWAFoHq8jMVA5bBurIrEpcB6vIxFwGXQaqyKhqXgWTyzVfBYvHDGAG0svEAGEHo8gtlQRiCKvIRJXUAmMGo8jNLGQIq8impZIAZQajyFVTZgiryKa0YgJnCKvHrSQXAGgIq8hElawAaQiryGUk0wBqCLPHZlguAGsIq8jEtJIKbAeryMjWAG0Io8ikoVQAbgejyKhkBW8Ho8hVqgJwCKvHqLRiBHEIq8ctlWQAcgijyKQVIwBzB6PIjbwAdAiryKUVcwB1B6PIJCsJdgejyCSrAncIo8gkNVQAeAejyKQyFXkIq8ckleQCegejyMyUBnsIs8emJOsAfAbpyAwBfQmzx+SoYooAfgeUyyWVAAAAAAT//wA=";
export { u8g2_font_4x6_tr };
export default u8g2_font_4x6_tr;
