/* u8g2 official font: u8g2_font_percent_circle_25_hn (749 bytes, 9 glyphs)
 * Converted verbatim from u8g2_font_percent_circle_25_hn.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_percent_circle_25_hn.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_percent_circle_25_hn', font)
 */
const u8g2_font_percent_circle_25_hn = "CQEEAwUFAQEGGRkAABkAGQAAAAAAAtEwTDmfczzYPYRMjLCsZHxcPEhYPEhUPFDCwZjIiMiQyIjIkMiIyJDIiMiQyMmQeLCQeLCYuJi4oNDAqMBkcZFxUTFRkbLCcvIQ94gAMVM5n7M9xMG0zIGkpF30XHxEWDxIVDxQFjNDMVEx6UKiImamQqIi4qJCoiLiokKiIiYipkJiI0PiwWLiYuKCQgOjApPFRcZFxURFygrLyUPcIwIyTjmfsz3EwbTMgaSkXXRVPFU8BE08DEnYxBRFZETgRNzE2ERcVNhEXFTYRNzEXEg8WEg8WExcTFxQaGBUYLK4yLiomKhIWWE5eYh7RAAzVTmfsz3EwbTMgaSkXXRVPFU8BE08DEnMxMwIRVhMqokomZgVYTFRMRNhMVExE0EzEREzE8FxE/FQI3ExYSShcTSBcURxcWRRMVFzshKhcvIQ94gANFI5n7M9xMG0zIGkpF10VTxVPARNPAxJ2MQURVxMRNhE3ESyiciIZBOREckm4ibGJuKhJuKhRuJiwkhC42gC44ji4siiYmLqJE1lDqQP5mHsADVXOZ+zPcTBtMyBpKRddFU8VTwETTwMSczEzAhFUFRM1ETQxMyKoIh0MRNBEeliJoImJiJmJoLjJuKhRuJiwkhC42gC44giouLIZtJU2dkdHIweWB/QATZLOZ+zPcTBtMyBpKRddFU8VTwETTwMSdjEFEVkROBEZMTYRGRMmGFMmGHEmD2QPdBZTNhBZBwFXRwNVRxRTZoqO7uDg9ED6wM6ADdROZ+zPcTBtMyBXISk1XQRNQ09BT3IQcjEzMhNREwqm5mYGZuImKgYm4iYqBibmYiIGds4e6CzmLCDyDgKujgaqjiimjRVdnYHB6MH1gd0ADhIOZ/fAfWB6cHBnKvaImoaegp6kIOgiEVXEbmyisiVVUSurCJyZRWxyh7IHugsJuwgMo6CLo6GKo6oJk2Vnd3BweiB9QEdAAAAAAT//wA=";
export { u8g2_font_percent_circle_25_hn };
export default u8g2_font_percent_circle_25_hn;
