/* u8g2 official font: u8g2_font_squeezed_r6_tr (707 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_squeezed_r6_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_squeezed_r6_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_squeezed_r6_tr', font)
 */
const u8g2_font_squeezed_r6_tr = "XwACAgMDAQQEBQcA/wb/BgAA5QHNAqcgBEBUIQZxVEYKIgZTZpIKIwpt9KqhqqEqACQL/XPzUHmnoSMAJQlzZFJMMcUUJgl07GKKVTMFJwVRVgQoBnLcVDMpCHJcYqoUACoH62RStRorB1vl0koALAXRUwQtBcpdBC4FSVQCLwhzZKuYYgQwB3PkKlcFMQZy3FYHMgdyXGJSSTMHclyUTAo0CHNkkhqxATUHclxWTAo2CHPkSpVUBTcIc2Rmii0AOAdz5HqpCjkIc+RaskoAOgbZVFIAOwbpU6IAPAZa3WQAPQZaXaQAPgZaXaICPwdyXKLKCUAIdOxUVDcaQQhz5KqhrABCCXNkVFpJLQBDBnLcVDNECHNkVHItAEUHclzWSgJGB3Jc1qoARwhz5GaykgBICHNkkhrKCkkFcVQOSgZy3LoGSwhzZJJayQpMB3JcUpcATQl1dPJaSdsBTgh0bOJS0wxPB3PkKlcFUAhzZFRasQRRB3PkKlcSUghzZFRayQpTB3LcVEwKVAdzZFbsAlUHc2SS1whWCHNkkqtMAFcJdXSyK6kuAFgJc2SSKlNSAVkIc2SSVVYAWgdyXFRSSVsGclxWS1wIc2RijjkGXQZyXFRrXgVT5hpfBUpcBGAGUl5iAGEHY+SWSgJiCXNkYlRJLQBjBmLcVAxkCHNkq6WSAGUGY+SqKWYHctzUqgBnB+vjVpILaAhzZGJUyQppBnFU0ghqCPrbcqoUAGsIc2RitZIKbAVxVA5tCWV0RqpUUgVuB2NkVLICbwdj5CpVAXAI62NUUisCcQfr45ZKMnIHY2TSihFzBmLcpAJ0B3JcUloxdQdjZJI1AnYHY2SStQB3CGV0skqqC3gHY2RSmQp5CetjkkoyJQB6BmJclAF7CHNkU5J1AHwFcVQOfQlzZHJUMUUAfgdU7pJKAAAAAAT//wA=";
export { u8g2_font_squeezed_r6_tr };
export default u8g2_font_squeezed_r6_tr;
