/* u8g2 official font: u8g2_font_DigitalDiscoThin_tu (826 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_DigitalDiscoThin_tu.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_DigitalDiscoThin_tu.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_DigitalDiscoThin_tu', font)
 */
const u8g2_font_DigitalDiscoThin_tu = "QAADAgQEAQQFCw0A/gr9Cv4BhwAAAx4gBQCxAiEHoVHioAQiBzOfIrEEIxWpUa+YhVk0DFIWZtEwSFmYhVkGJBHG7SoNh6SWhEMWdRq2NAMlEqlRR4t6CaU8R/JITKLeFAAmFblRb82RHJGjTEyqUZzEUagNUQAnBTFfYigIwm1G6Z8CKQnCbSJK+osCKglEuUYZEiUKKwpV0yqMBimMACwHMm8mUQAtBhS3YgguBRFRIi8Ko5GqJWqJSgAwFKgxa8jCJB0TLZIyJVyTMBsiADEIonEiSvoDMgynEWurpHHa6zAEMxGoMWfY43TIkVyWkzAbIgA0EagxI68maZImaRRmw5wnADUPpxFnkOJ4yMuxGA0RADYRqDFLzeNkiMQkNidhNkQANwym8eJaTMM0TGsAOBKoMWvIwijMhixMYnMSZkMEORGoMWvIwiQ2J6E0JHGeSgA6BmFTIgw7CHJxJk8UADwIZvNSMsoGPQhG9eKODgM+CWbzQjZKRgA/Dagxa8jCJJa755QMQBWpUWvQ0iTXJKkiVbQhyaEcGiQAQQ2oMWvIwiSWh0PsOUIRqDFnyMIojIYpTWLXZJgAQw2oMWuQUr13JI0GBUQNqDFnkNIk9msyTABFDqbxakjCNB2UtBwPAUYNpvFqSMI0HZS0KwBHFKlRa9DSJEdyJEfCQdeTNBskAEgLqDEjdh4OsecASQahUeIhSgmzj2LqLyUASxCnESNMwiRMsmiQwiR1DUwIpLEi68dQTRWrkUvToiRKwlAMxVAMxVAMxVAsTguoMWvIwiT25wBPDqlRa9DSJPc9SbNBAlAPqDFryMIkdh6TZIjyHFEQyU1r0NIk9z1Js0FHckhSD6gxa8jCJHYek2RQYjlTE6gxa8jCKM+RIUdyRE7CbIgAVAmnEeOQxf0NVQuoMSP25yTMhghWEagxIzYnYRRGYRaFUSprAFcVq5EjDMVQDMVQDMVQDMVKlESZCVgRpxEjTbJKmKRxmoRJVkkDWQ2oMSP2nITZEOc1AFoNpxHjkMZpOS2nwxBbCMJtYulfBFwKo5EiqkVtUQFdCMJtQulfBl4INd0qS2oBXwYYL+MgAAAABP//AA==";
export { u8g2_font_DigitalDiscoThin_tu };
export default u8g2_font_DigitalDiscoThin_tu;
