/* u8g2 official font: u8g2_font_tom_thumb_4x6_mr (781 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_tom_thumb_4x6_mr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tom_thumb_4x6_mr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tom_thumb_4x6_mr', font)
 */
const u8g2_font_tom_thumb_4x6_mr = "XwIDAgMDAQEEBAYA/wX/BQAA/wIAAvEgBnR8NgAhB3ScrB4DIgd0jKSdBiMJdIwkWSpLFSQIdBybosUAJQh0jDSqpgAmCXQMSVpKKgAnB3ScLCcCKAd0rFoxBSkIdIwwK+UAKgl0jCSq5DAAKwh03GjKMQAsB3R8OMoBLQd0fGSHAS4GdHxaDC8IdKwsquUAMAh0HKUvMgAxB3ScSGsGMgh0DDGqrQAzCHQMMQoTGTQIdIykZasCNQh0jCUTExk2CXQcJVsqKwA3CHSMLarlADgJdIylslRWADkJdIylsiUyADoHdNw8xwA7B3TcPMoBPAd0rMYqAD0HdMx1hwA+B3SMsFQHPwh0jC3KYwBACXScKEmWUAVBCXScKEmWrgBCCnQMKUmkJJEBQwh0HCUrqgBECHQMKelFBkUIdIwlW7IVRgh0jCVbshxHCXQcJVtKKgBICHSMpGXpCkkIdIwpK60ASgh0rKxSigFLCXSMpEVKWgFMB3SMrG0FTQh0jCS5dAVOCHSMJHmpAk8IdJwo6SkGUAl0DClJpCwHUQl0nChpmVQAUgp0DClJFilJAVMIdBwlrMgAVAd0jClrBlUIdIykn1QAVgh0jKSnLAZXCHSMpOVSBVgIdIykqdIKWQh0jKQpKwNaCHSMLaqtAFsIdIwlq60AXAZ0zHYIXQd0jK1lBV4IdJwoyWkAXwZ0fNIKYAd0jDAnAmEIdExNqawAYgl0jExKWmQAYwh0XCULVQBkCHSsSOmkAmUIdFyloqkAZgh0rNKUxQBnCXRcpbJFEQBoCHSMTEp6BWkHdJw8KwNqCXSsPEtKEQBrCnSMLEkkKUkBbAd0DK1pBW0HdMzlUgVuB3RMKekVbwh03ChpigFwCXRMKWmRMgBxCHRcpZOWAHIHdFwlqwNzCHRcRVNkAHQIdJxoyjIVdQd0zKQnFXYIdMykZYoBdwd0zCR5BXgJdMwkyqIkBXkJdMykSYsiAHoIdMxJkVYAewh0HKmYqQB8CHScLM9iAH0IdAwtjCIZfgZ0HDsRAAAABP//AA==";
export { u8g2_font_tom_thumb_4x6_mr };
export default u8g2_font_tom_thumb_4x6_mr;
