/* u8g2 official font: u8g2_font_p01type_tf (742 bytes, 103 glyphs)
 * Converted verbatim from u8g2_font_p01type_tf.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_p01type_tf.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_p01type_tf', font)
 */
const u8g2_font_p01type_tf = "ZwACAgMDAgMEBQYA/gT+BP8A0wG2AsogBIBkIQbpW1YAIgaTZpIKIwqt86qhqqEqACUGpGxiDyYJrOtiRknFFCcFkVYEKAaq21QZKQeqW2JKCioGm2RSBysHm+TSSgAsBpLbFAAtBYtlBi4FiVQCLwak62MbMAer45a1ADEGqVOGADIHq2P00AIzBqtj9AU0CKtjkhqxADUGq+PmBTYHq+PmSAs3CKtjZhUTADgHq+MOtQA5B6vjjrgAOgaZVFIAOwai27ICPAarY1NdPQabZPYAPgerY3JVAj8JrGs2ShpHAEAIrOtGVHsBQQek7EYcM0IJrOtGHCmOBEMHpOxGziNEB6RsVpRDRQis60ZeGQ1GB6Rshl4ZRwik7EaOIwFIB6RsohwzSQahVEYASgai3CoFSwikbKIcKQZMB6Rsco0GTQekbOKYMk4HpGziUjNPCKTsRpQjAVAIpOxGHCkDUQik7EZUSQVSCKTsRhwpBlMJrOtGHnkkAFQJpXSGzCijCFUIpGyiORIAVgikbKKZFABXCaV0UlJJpSVYCKRsokwqBlkIpGzi0CMBWgikbEYsRwBbBqpbViVcCaRrMsooowBdBqpbVDVfBoxrRgBhBpvkjgBiB6Nk4kgLYwab5OYAZAajZNMRZQar4g4tZgej5FRaCWcHq+KOuABoB6NkokoqaQWZVAZqBqraWgprB6NkYloFbAahVEYAbQed9LpUAW4Hm2RUUgFvBpvkLgBwB6virhgBcQerYlQlC3IGm+RmBHMGq+LmBXQHo+TSygF1B5tkkkoCdgebZJKqAHcInXRSUl0AeAabZFIHeQirYpJKcgF6BptkVhp7B6vjVB0FfAapU4YAfQirY2ROSQF+B5TtkkoAoQapU9IApgbpW5QAqwmtc1PvlFMArAaTZGYArQWLZQaxB6vj0spotwWJVQK7Ca1zUk459QS/CKxrM1YZDdcGm2RSB/cIq+My2igBAAAABP//AA==";
export { u8g2_font_p01type_tf };
export default u8g2_font_p01type_tf;
