/* u8g2 official font: u8g2_font_tiny_simon_mr (797 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_tiny_simon_mr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tiny_simon_mr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tiny_simon_mr', font)
 */
const u8g2_font_tiny_simon_mr = "XwICAgMDAQIEBAcA/gX+BQABCQINAwEgBnx4/gUhCHyYXFOZCSIHfJjU5gcjCXyYlFa1agYkCXy4OOPMLAAlCXyYlGOdMgMmCXy4mGIVNQMnB3yYnPkJKAl8uJhrlFkAKQl8mIxymZkAKgh8mBSrzBMrCHx4GGfmBCwHfHh2zQQtB3x4cvMELgd8eF6ZCS8IfNgc68wEMAl8uJjSKjMLMQh8uKjLzQAyCHyYnVbeDDMIfJgdddoMNAh8mNTaNQM1CHyYlXfaDDYIfJiVV7UZNwh8mB3rzAQ4CHyYVa1qMzkIfJhV7bQZOgh8eDJTmQk7CXx4MlM5UwA8CHx4WKPMCT0IfHi04eYCPgh8eJRRzDw/CXyYHTXOLABAB3yYVb0ZQQh8mFWtbgZCCnwYmZJMSbMAQwh8mNVOaTNECXwYmXppFgBFCHyYlWXeDEYJfJiVZc5MAEcIfJiVU2szSAh8mNRa3QxJCHyYmcvNAEoIfJhdVZsBSwl8mNSSqc0ATAd8mNzeDE0IfJiUVt8MTgh82FStNhNPB3yY1ddmUAl8mFWtnJkAUQh8uJhaUzNSCHyYVcnUZlMIfJiVd9oMVAh8mJnbLABVCHyY1K/NAFYIfJjUz8wCVwh8mNRr1QxYCHyY1KzaDFkJfJjUmjmzAFoIfJgd680AWwh8GJlrzQJcCXyYnFFGOTNdCHwY3dQsAF4HfLiYMj9fB3x4XpsBYAh8mIwyvwBhB3x4ctoMYgh8mJxXtRljCHx4cuXNAGQIfNicVrUZZQd8eNLcDGYJfDgZZ84sAGcJfHhyVTtJAGgIfJicVzcDaQh8mEzlmglqCHy4TOVSE2sJfJhcJZkyA2wIfJjc1iwAbQh8eHKtmgFuB3x4WnUzbwh8eHJVmwFwCXx4clUrZwBxCHx4clW7AnIIfHhS5swEcwh8eFpGzQJ0CHy4HGfWDHUIfHgytTYDdgh8eDI1Mwt3CHx4MqWbAXgIfHgyxSozeQl8eDK1dpIAegh8eFJnzQB7CHw4GXXWDHwHfJjczQR9CXwYnWXULAB+CHx4nFbmAQAAAAT//wA=";
export { u8g2_font_tiny_simon_mr };
export default u8g2_font_tiny_simon_mr;
