/* u8g2 official font: u8g2_font_DigitalDisco_tu (809 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_DigitalDisco_tu.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_DigitalDisco_tu.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_DigitalDisco_tu', font)
 */
const u8g2_font_DigitalDisco_tu = "QAADAwQEAQQFDA0A/gr9Cv4BegAAAw0gBQCxAiEHonHiiQAiBzXfQsIiIw+oMUvT4UARaTkcSJoAJA/G7UooO1RETZJDTSgCJRmqcUcmiohEEUWRXA6Ri4SSiEgUEckkACYUuVGLWJxTJAfSRCgRSkajQ4giJwYyf8IAKAjDjYaifxIpCsONQiTRXygAKgpW90pkoZhEACsLZvNKKDqUhCIALAYyb6ICLQYkt+IQLgYicYIALwuksUqLSItICQAwEKgxi2YZlSyHiak0sZEAMQijkUIy0R8yDacRa1aZ1ISzbYcDMw6oMcdklRLLxNLERgI0EagxQ6wmkUlkkpHoZBVLADUOpxGnVJLSqlPSQUQCNg+oMWtIm5ouo2JpYiMBNwym8eJQlMlmQp0AOBCoMYtmUgvFLKNiaWIjATkPqDGLZhkVS5OTdUYcAToGYnOCSDsHcnGCWAE8CogxW0hiJDMLPQlm8+JQhx4KPgqIMUPMkcQoBj8OqDGLZhnVhqtyuFgGQA6pUat2mVVJT+vGEgBBDagxi2YZFQ8HI0cBQg+oMYdmUjJdZEXaYWICQxCpUat2mVUjctXIbHIrAUQNqDGndJEVeTtMTABFDabxinKICSsV4bBERg2m8YpyiAkrFaFGAEcPqVGrdplV6TJrbXIrAUgLqDFDyHg4GHkUSQeiceLBAEoKtK9mSV8sIgBLEacRQyQRSUQSyaRkEdXYBEwKpdFCpm8z0gBNFqyxa+0wmVBqMpqMJqPJaDKajKYATguoMYtmGRX5UQBPDqlRq3aZVbnWJrcSAFAQqDGLZhkViaXDRDISiwFRD8lNq3aZVbnWJrf6XAJSD6gxi2YZFYmlw+QiKwpTDqgxi2YSF8vF0sRGAlQKpvHiUBLqJwBVC6gxQ8iPpYmNBFYOqDFDyCgR6Y1IFcsAVxissUMmo8loMpqMJqPJaLIKZXKYjUYAWA+oMUNYmtioYinNMioKWQ2oMUPIsTSxUcVqAFoMpxHjUThUHAoPB1sIw42ion8ZXAqksUKkJtImUl0Iw41ion8pXglG/UpGoogEXwcoLeNBAAAAAAT//wA=";
export { u8g2_font_DigitalDisco_tu };
export default u8g2_font_DigitalDisco_tu;
