/* u8g2 official font: u8g2_font_spleen5x8_mu (678 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_spleen5x8_mu.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_spleen5x8_mu.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_spleen5x8_mu', font)
 */
const u8g2_font_spleen5x8_mu = "QAIDAgMEAQEEBQgA/wb/B/8BPwAAAoogBsX6vAIhCMVaYXcoByIKxTqlJEpyVgAjDcXaSTIopSQZlDIAJAvFWtlSEzVljAAlDcV6SZQUszApJSEAJg7FWlkSJZGUJFKkpAAnB8VaYZ0ZKAjFeo2tFQApCMU6abGtBioLxfpYFElDJJUBKwrF+mgYDVKYAywIxfrMYZYBLQjF+uQhJwEuB8X6HHMALwvFemEWZmEWhgAwCsXaUiWxlCIdMQjF+pnYNgMyCsXaUjGSwiEGMwrF2lItTaJIBzQMxbphEiXRkIU5ADUKxbpDEq5hsgM2CsXaUjhVokgHNwvFukMShVkxRwA4CsXaUkmqRJEOOQrF2lIlisZIBzoIxfq0HM8BOwnF+rQcCrMMPAnF+khWTMsAPQnF+pQhHnIQPgnF2mkxqyMAPwrFOlIxq0M5AkALxdpSJVESJZ0BQQzF2lIlSoYkSqIYQgrFulNlqkTJDkMIxdpL2DoDRAzFulMlSqIkSnYARQnF2ks4hekMRgrF2ksYTmEOAUcMxdpLmChREkUzAEgOxbpREiVDEiVREsUASQjF2lvYNgNKCcXaW9ikIwBLDMW6URIlUyVKohhMB8W6YdcZTQ7FulEyJEMSJVESxQBODcW6UaIkSkVJlCgGTwzF2lIlSqIkinQAUAvFulMlSqYwhwBRDMXaUiVKoiSKRAVSC8W6UyVKpkoUA1MJxdpLqobJDlQIxbqDFHYHVQ3FulESJVESJVE0A1YMxbpREiVREkWaDlcOxbpREiVRMiRDEsUAWAzFulESRZpUiWIAWQzFulESJVE0JjsAWgrFukOYNQ4xAFsIxTpT2OMCXAvFGmEapmEaJgBdCMU6Y58WAF4JxfpZUsvJAF8HxfrchwQAAAAE//8A";
export { u8g2_font_spleen5x8_mu };
export default u8g2_font_spleen5x8_mu;
