/* u8g2 official font: u8g2_font_osb29_tn (749 bytes, 18 glyphs)
 * Converted verbatim from u8g2_font_osb29_tn.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_osb29_tn.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_osb29_tn', font)
 */
const u8g2_font_osb29_tn = "EgAEBAYGBAUHIyUA+B33HPkAAAAAAtEgBgCAcAkqJw60fGpiiZISM0bEGCFIgqgIUYwoqRIhShAJgkaImTHCiJIVBgArTqGoqvzjwY8HPx78ePDjwY8HPx78ePDjwY8HPx78ePDjwY8HP/7BP0g/Hvx48OPBjwc/Hvx48OPBjwc/Hvx48OPBjwc/Hvx48OPBjwcsFAiTSSlkTKA4YkxYMKkEDRIFAC0ICqHYCR8oLgyGoVAZJB6kIAEALyRNqSi6QicVOqlYoZMKnVToTIVOKnRSsUInFTqp0JkKnRQAMDRSp896hAWJHDRu2Chio4iRKUamWJFiJYyVMMZ/ZqJYkWJFipUhRogYqWFTkRs01HhIADEPDdfQaiMJFkpn//8/ajI7UafPWgcFlRJWZlyRceqWsWpkwoyRQkbNVkuY8GihYcSGCRwkdJAQ5EQ8CPEgRJglgZSEQhPMdDAAMzRRp89aB8eUElZIXJFxJoiZKGWilIlSRkgVLluWoHkQxAsbLmyiFK+WqSsyrJAwYmpDAjQrEqfQmqULW3spliJMijAoxKAQc2LMiTEmyJggU6JMiTIkzNCDgYbtQwc1M5G3z9pixg1qxEpdQrPi5cSciECkhpURV0Zg4cJmjQwzUYqrZSXIlRhIRlwhYcQShwQ2O1K3z3pGBwkcJozYIFKFCJkpZKZQVYQK28IUGjKHihgrYayEMc5MFDNRzEQxI8TKECtEitggkqgDAjcxEbfPGkIIDRFhZoiaEWtEMBHxIISwEiJCBwksJLAIseLDCxc+evhowmULV2uPyQE4PlOnz2pmR4kbGWqooLFCyAohK6SoEJNhkIlRI4oh70IsEqREHBKRJoYmHjF4xOARg4eMFUM02MCAJUiLBDk9UrfPWkbJjCs0qtigYkSMETFWwlgJYyWMMTNRzEQxI4XOkEFlwrBtSBWqxlAZQ4RKERpGTNg4USNRBwU6EcakUBkkHqQgDzmJBylIAAAAAAT//wA=";
export { u8g2_font_osb29_tn };
export default u8g2_font_osb29_tn;
