/* u8g2 official font: u8g2_font_sirclive_tr (890 bytes, 86 glyphs)
 * Converted verbatim from u8g2_font_sirclive_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_sirclive_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_sirclive_tr', font)
 */
const u8g2_font_sirclive_tr = "VgAEBAQEAgQFDQoA/gf+BQABFgJcA14gBQBiBSEHcaOEEgEiCCM3hRAiAiMTe+KOcEHChVgRLsSKcEHChQAkDnmfpkBqAiUKoygQACUVeyMHEqGChAhFImgUpEIECRWCACYPWaOGIiHChEASIliIBCgIUuOEEVEIKQhS4wQRUQwrDFmjpoCBEgUMBAAsBiGfBAEtBhmrhgQuBhGjhAAvC4WjlSGB4skQADAIWaMGddIpMQZRo4QCMghZo4aECxMzCVmjhoRhDCo0CVmjhnDiFEY1CFmjBoUJFTYIWaMGheoUNwdZo4aEcTgIWaMGdesUOQhZowZ1ChU6B1GjhDABOwdhn4QwAj0IWaOG9IATPwx5o4aEAdcDCQgAQBOdWge3IlKIDCEihYhwIUSwdUELeaMGdeLWSRcAQg15owYU4cStE5cCAEMJeaMGhXGYAEQLeaMGFOHkLgUARQp5owaFARUGTEYLeaMGhQEVRggARwt5owaFkZwTpwBIC3mjhnDSrZMuAEkGcaOEA0oLeaOGVAHjxgwASw95o4Zw0i0KEyhMoDAATAl5o4aA8TABTRJ5owY1YcSEERNGTBgxYcRETgl5owZ18i4ATwl5owZ1cqcAUAt5owZ14hZGCABRDXmjBnXSCBEkQhQDUg95owZ14haFCRQmUBgAUwp5owaFARMGVFQKeaOGRAHjEQBVCXmjhnDyTgFWCnmjhnCyU5kAVxB5o4Zw0oQRE0ZMGDFhFFgNeaOGcNKFOBFOugBZDHmjhnDSKQoYEQBaCnmjhoQBFwZMWwmC44QR8UIAXAmFo4VB8dEAXQmC4wQR8WIAXwYZo4YEYQhZo4aE6xRiC3mjhoAB1UmnAGMIWaMGhREmZAl5o8aA66RTZQhZowZ1CxNmCVmjBoUKAwJnCXmbBnXSKVRoC3mjhoAB1ckuAGkHcaOEEAVqCpLbjDAh4mIAaw15o4aAAdUtChOIAGwGcaOEA20OWaMGNWHEhBETRkwEbghZowZ1sgtvCFmjBnXSKXALeZsGddItDAgAcQp5mwZ10imMAHIIWaMGhTEEcwhZowaFCRV0C3mjhoABFUaYAHUIWaOGcLJTdglZo4Zw4lQmdw9Zo4YwYcSEERNGTBgFeA1Zo4Zw4kKcCCcuAHkKeZuGcLJTqAB6CFmjhoQLE3wGcaOEAwAAAAT//wA=";
export { u8g2_font_sirclive_tr };
export default u8g2_font_sirclive_tr;
