/* u8g2 official font: u8g2_font_profont15_mr (1420 bytes, 96 glyphs)
 * Converted verbatim from u8g2_font_profont15_mr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_profont15_mr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_profont15_mr', font)
 */
const u8g2_font_profont15_mr = "YAIDAgMEAQMEBw8A/Qn9C/4BxgO4BXAgB//58/8DIQv/+bPFfYdzNgAiDv/5I1EWZVEW5fwnACMP//mzRNEw1aJomOp8AiQV//lDcbolpSRM0jUJkyiprXEOAiUU//mzDEOSKVHSltSSpkRLxJwFJhH/+bNspVqSVsIoqWVLzgInCf/5Y3E7/w0oC//5g2lz39shACkL//kjeXNf21EAKg7/+TOFSW3ckmLORwArDP/58ykOBzHOOQIsCv/5859UOa0CLQr/+fOXIecTAC4J//nzn1SdDS8Q//lT4zRO4zRO4zTOYQAwFf/5swxRmGRKlDQlWhImYTTkTAAxC//5s4Vz34YhZzIO//mzDFEYV7sOOwsAMxD/+bMMURjX9jgJoyFnAjQQ//kzpmKSRbVoWON0ZwE1EP/504cljgc9roTRkDMBNhP/+bMMURwPUpiESZiE0ZAzATcL//nTh7na3M4IOBX/+bMMUZiESRgNUZiESRgNORMAORL/+bMMUZiESZiE0SCXhpwJOgv/+fOk6qx2NgA7C//586TqrOa0CjwJ//mz9t6dBT0L//lzH3bKsPMFPgr/+bPkXbuzAj8N//mzDFEYV9vhnBFAE//5swxRmERLKSklkRTng84CQRL/+TOpYpRFxWRYwiRMwpwFQhT/+dMHKUzCJEwGKUzCJEwGnQlDDv/5swxRmMQ9RkPOBEQU//nTBylMwiRMwiRMwiRMBp0JRQ//+dOHJS4PUlwedhYARg3/+dOHJS4PUtzODEcS//mzDFGYxDUlTMIkjIacCUgU//nTwyRMwiRMhiVMwiRMwpwFSQ3/+dOHIYv7Ngw5A0oP//mzxl3CJEzCaMiZAEsS//nTwySLakmoJmGUlcKcBUwL//nT434edhYATQ//+dPTbalIkRSprjkDThX/+dPDREtKSZTUlDAJkzAJcxYATxX/+bMMUZiESZiESZiESRgNORMAUBD/+dMHKUzCJEwGKW5nBlEW//mzDFGYhEmYhEmYlJIoiYY8pwBSFP/50wcpTMIkTAYpTMIkTMKcBVMS//mzDFGYxPmQx0kYDTkTAFQL//nThyGL+50NVRT/+dPDJEzCJEzCJEzCJIyGnAlWEP/501NrkkVZJUzSOGcDVw7/+dNTT5EUKZVtzRlYEv/508MkTMKoqIpRMQlzFgBZDf/501NrklXSuJ0NWg3/+dOHOe05HnYWAFsL//lDY9w/7yQAXA//+VPiPM7jPM7jPM4BXQr/+SNz/3GnAV4L//mzpUlW518AXwn/+fN/H4YcYAn/+SN5nf8NYRH/+fNlUMIkTDIlSiIpZwFiEv/50+PyIIVJmIRJmAw6EwBjDv/582WIwiSuDzoLAGQS//mzxqVBCZMwCZMwGnQWAGUP//nzZYjCZFjifNBZAGYM//mziXG6xt0ZAWcS//nzZVDCJEzCJIwGuTREAGgS//nT4/IghUmYhEmYhDkLAGkL//mz5VS5684Eagv/+bPlVLkfRQBrEP/50+O2qJaESlYKcxYAbAr/+TPJ/bozAW0Q//nzPixRJEVSJEVSnQFuEf/58x5JSZRoSZiESZizAG8Q//nzZYjCJEzCJIyGnAlwEf/58z5IYRImYRImgxSXAXEQ//nzZVDCJEzCJIwGuQVyDf/58x5JSZSocZ0Zcw7/+fNlUPIhj5NBZwJ0DP/5M8XVNW7XmQB1Ef/58x4mYRImmRIlkZSzAHYO//nzHiZhVItCVWcDdxD/+fMeRVIkRVIkVewsAHgO//nzHkZFVYyKOQsAeRL/+fMeJmESJmESRoNcGiIAegv/+fM+rF2HnQV7C//5iXGvedy7BHwJ//ljcf93DH0L//noce9p3KMIfgv/+fNFSiKdnwB/B//58/8DAAAABP//AA==";
export { u8g2_font_profont15_mr };
export default u8g2_font_profont15_mr;
