/* u8g2 official font: u8g2_font_fur11_t_symbol (812 bytes, 45 glyphs)
 * Converted verbatim from u8g2_font_fur11_t_symbol.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_fur11_t_symbol.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_fur11_t_symbol', font)
 */
const u8g2_font_fur11_t_symbol = "LQADAgUEAwQGFBAA/Qv9C/0AAAAAAX8gBQCIJSMXaossszSKo2y4RXGUDbcojlIpjUQAJBzoa+rydJCUKFGiRAmHeBAjLRqSaEgiZVDzECUdbYtvhjCTtEySQkkRJSUekmhPsjTKQikLs9YFJhhri6yGWEslecg3RbJIS6QNkbhp46AMJwiC/CYOCQAoC8NbpZIo8ae2ACkMwl0mkkTplyFJACoMptxqokwaJm1IACsTKo8wdURHdEQcDqGO6IiOiAAsB4JqZIYFLQckuiaGAC4HQowlhgAvDaRr5pqkrJSVshoAMBZoi6mGLFPEREzERBzCIUzEKNOGCDEKZY2plmHR/AMyDmeLaQYpGzLV6OswBDMRZ4uphigcU02X4zHJpCEBNBJoiynXMdEUyZQpmjIMqmwBNRNniykuqjpIWqKp6pANWTREADYWaIuphkxSxEQepkkRE3EIo0wbIgA3DWeLKQ6pNVVTa2oDOBNni6mGKEzCRJKGKBvCN2lIADkWaItpBklTxERMtGVI5DzRpEwbIgAAAAAE//8DlBVqiWpzKEfmRI7iSMzEUEqleHgDqRptiS0HWRXzTJd0SZd0TZWyTBqGZHgaBAO8FWhbKcIojMIojMIojExDMuR1AAPAEwiLaoZBicIojMIokzJp0AYgMClzi3WGMIdsOWTKMUnRMUnJ0SGJtj3JEimNskQKpSyRwqwiZem2ACA5CsKcZoYkUQIgOgvDmiYkqTIkACBEDmeLqVO1nJbTVI0BISIOiforFkukKNFSSgoiAhPHe2n25pKURIM2jkkYFTUAIg8f7WkuPiTDQZM1WZM1WZM1WZM1WZM1WZM1WRmmQSIRG+prLF7kSId0SEd0SIdyJIdyJEdyJB/+ACISCCrOMB4CIhoVaYnpkTxHciTZwiyN0ijWdSQDIh4Rq65wtiVLMjHUkixRFQAiKwznWShvatx/GwEiSA+qrnCGUBxydAjFIQEiYBLqrvCj4ZDmSDocohzJEQAiZBIqj/ARdVx1aMd2bMeGQwAiZRIqjzBybMixHVPHVScOhwAlyhSHi6nUJIuySpikxiiLikmaAQA=";
export { u8g2_font_fur11_t_symbol };
export default u8g2_font_fur11_t_symbol;
