/* u8g2 official font: u8g2_font_streamline_music_audio_t (940 bytes, 14 glyphs)
 * Converted verbatim from u8g2_font_streamline_music_audio_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_music_audio_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_music_audio_t', font)
 */
const u8g2_font_streamline_music_audio_t = "DgADAgUFBAMGFRUAABUAFQAAAAAAA5AwOjWi6wwPco6nOb7lkBbVpVqSilHSGEcVMY40MZw0MVMiTdqGKFSUUKskQw5lSaRjUR3fcjweHmQAMT+1IusjOjHKaVFOi3JakhN1dIik4aAmOS3KYSU6HLKkHU9KOaZEUjLcSjkeJTk4DdFwyHPiDi9DMjwOOVEnMkO1Iusjg46rOrYjepRjaRiKzVk2xlkUSYMWJakaZXKyxHLSLCdLLKdjEg+aEuVYquVQGuZYmOZQluvIjqk6PugIADNDtSLrI4OOqzqmQ3oOp+GOhFkOZqVBjlorWRJNqZYkg5KqiaWmJoNSU6MpyZK0KR6krA5mYQ6JaQ7nOqRjqo4POgI0RZRiaw93LIdyJBqGKI6GQ5Imw0OaDA/hMGZamKlKlOVQooQ5lChhFCaJHIVJY45pQ5oleTzlSA7l2HAH4xwbxHn4kAA1QLQi66NDjk87GLVjSZjk0PCORGGUI1EY5cjwDiVhkmNROzjt8LDjw44nQ44nQz4mQ5xlwxpmyiZnQw5nOmUHNjOtMmsOelorJlkSZsUkS6Ikqwz5kOSJkidKnkhplESDlOXpMORQjuZoDg1DOByk4aAAN0q1ImsOOiXN4ayOJlmSo1kdTbIkx5KskiP7jtSTHKnnWJJHgxal0TBk0SBFU5ZrmTYs65wN2RBn65xpmTZM0RQNp2HIhkM0aAA4LXJm68M5TSclOSXK8awOZZmO5EleivMszbNsj4c8HvJcR3LKjg85PuQUnQI5QrUi6yOioiNSVzFKwzirxmESV7PijoTZkKVZNkRJFo1iOuhwNuSwpkNakodRa5JFzamWk9MkDcekNg05nA05UQQ6RbUi6+dwmqRZDuVYqCOhmMSbmEM5pFO14RjnUA7lYI4kyqLEwwctzMMkHoZY2qFJaRmUFpcWl5ZBaZF2aEpyWjZ8kAA7SXNma/wHHRwGJU+GQRWHQYyyYRCjbBhUcRh0cBjEIRsGLYyGQYqkZBikJEqSYZCSKEmGQYqkZBi0MBoGcciGQcmTYdDB4QcBPFO1Iusjg44Pd+ww5MtwUBdJGkRFGZYhU5RhUIYoUYZDsijJkA3JsCTr8CGKhg/pkgzLkA1JohwOiRINyTAotiEZFuMgWdbhoOzDkO3YcMcHHQE9PfXh6ww/JDlVySmJNjxkUqRKkZIoXZRESZQ0URIlUYYhURIpGk6RNjxkOlWJhoOUaDmYJbVhyJJs+CABAAAABP//AA==";
export { u8g2_font_streamline_music_audio_t };
export default u8g2_font_streamline_music_audio_t;
