/* u8g2 official font: u8g2_font_missingplanet_tr (970 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_missingplanet_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_missingplanet_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_missingplanet_tr', font)
 */
const u8g2_font_missingplanet_tr = "XwADAwQEAgQFCw7+/An8CQABPgKYA64gBQBiBSEHkaLEJQAiCDM6RUQlACMRlaJNUiRSSYqEIpFKUiQCJBO1nlXIEoqEIqFSJBQJRUwhACUOlaLFRBKhxHKhRCQDJhKXIkYpFoqlRGOR3EIpkVkAJwYxusQAKAiTIgUpnwYpCJMixSifCCoKVbJFJGVSmWQrClWqVTBUCoYALAczmFSIAC0GFbJFAS4GEaJEAC8JlaJlthwTATAIlaKFTd8MMQiVosUwPxUyCZWiRTHxmFgzCZWiRTHRmGg0CZWiRUybMQc1CZWihTGxmGg2CZWihTHRpmY3B5WiRTF/OAmVooVN7aZmOQmVooVNzZhoOgdRokQsADsIc5hUHBgiPAlVqtUkFo0OPQc1rkW1AD4JVarFNC0yAj8OlaKFTRYMjYJxUAgAQBSZosZhLqlII5KKJBaRHOKQgwBBCpWihU3tpi0AQhGW4gUpFgnKIqRYJCiLkABDCJWihTEfC0QQluIFKRaJRYLaIrEICQBFCZWihTHRmFhGCpWihTHRmBEARwqVooVNMUJTM0gKlaJFTNtNWwBJB5GixEEASgeVomV+NEsPluJFUC0SCpGyRYLCAEwIlaJFMD8WTRSZosZhFpPFZDFZTBaTxWQxWQJOFJmiRk0Wk8VkMVlMFpPFZDFZAU8IlaKFTd8MUAqVooVN7ZgRAFEMpZ6FTS8RScQUAlIPlaKFTe0UCUVCkVAEAFMJlaKFMbGYaFQJlaJFKZifAFUIlaJFTL8ZVguVokVM3yJpIQBXFZmiRiwmi8lispgsJovJYrLYYQBYDJWiRUwtkpaSphZZC5WiRUybKZgJAFoJlaJFMfGYWFsIkyIFKZ8GXAmVokUwNccEXQiTIsUonwheBiM+TQZfBhWaRQFgByL+RCgAYQdVokXxZmIKlaJFMKNNzQBjCFWihTGxAGQJlaJlxpuaAWUHVaKF7VhmC5Wi1SiYVApmAmcJlZKFTc2YaGgKlaJFMKNNWwBpB3GiRKQAagmzkFQ0lE8Eaw2VokUwN1GEEorEAmwHkaLEQQBtDFWihSUiiUgikgRuCFWihU1bAG8IVaKFTc0AcAqVkoVN7ZgRAHEJlZKFTc2YA3IIVaKFMSMAcwdVooWxaHQLlaJVMFMpmAkAdQhVokVMmwF2ClWiRUwtkhYCdw1VokUkIolIIpKIAXgLVaJFTBaZxGQBeQqVkkVMmzHRAHoHVaJF8Vh7CpWi1SiYNMw4fAfRksTBAH0LlaLFMOMomDQCfgk1usVEEpEMAAAABP//AA==";
export { u8g2_font_missingplanet_tr };
export default u8g2_font_missingplanet_tr;
