/* u8g2 official font: u8g2_font_smallsimple_te (911 bytes, 106 glyphs)
 * Converted verbatim from u8g2_font_smallsimple_te.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_smallsimple_te.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_smallsimple_te', font)
 */
const u8g2_font_smallsimple_te = "agACAgMEAQQFBwgA/gb+BgABDQInA2ggBYA4ASEGsSgZKSIGk0xJKiMMtniLaazYGismACQKtWgbKu+kqgUlCrNISTHFFFMAJgq1aMspV0lGFScFkSwRKAeyOFPNACkIsjiJqVIAKgabS0kdKwqtac0oDplRBCwGkjdTAC0Fi0sZLgWJKAkvCLNIrWKKETAKtFhTUY0kkwIxB7NIS7I1Mgi0WFOxewQzCrRYU7FGMikANAy1aIkpppiGzigBNQq0WBl6I5kUADYKtFhTeUWZFAA3CbRYGTnWJQA4CrRYUzGpKJMCOQq0WFNRpp0UADoGsSjJKDsHujfLtAI8B6tJTXUBPQajSdl4PgerSclVCT8JtFhTsU1FAEAMtngbKSPX0HgkAEEJtFhTUY4pA0IKtFhZcaQoRwJDCbRYU1GXSQFECbRYWdE5EgBFCbRYGXrlPAJGCLRYGXrlGkcKtFhTUaeZFABICLRYiXJMM0kHs0hZsTVKCLRY27VMCksKtFiJKslUygBMB7RYyd0jTQm1aMlrJW0HTgi0WIlLTTNPCbRYU9GZFABQCrRYWVGOlDMAUQm0WFPRFVMAUgq0WFlRjhRlAFMKtFgbGWkkkwJUDLVoGTKjjDLKKAJVCLRYiZ5JAVYKtWjJdipTjgBXDbeIyVBDDVMz1SkCWAm1aMmprmodWQy1aMmpziijjCIAWgm0WBk5tkcAWweyOFktAVwIs0iJOeYYXQeyOFGtAV4HnWvNqQ5fBYtIGWAGkjyJAWEIpFgbUaYBYgq0WMl5RTkSAGMGo0ibWWQItFivRpRpZQikWFNpZAVmCLNITWnFCmcKtFYbUaY9EgBoCLRYyXlFM2kGsShJI2oIwjbLqaUAawq0WMlRJZnKAGwFsSg5bQmlaFEtlVQBbgekWFnRDG8IpFhTUSYFcAq0VllRjpQzAHEItFYbUaZdcgijSEkrRgBzCKRYGxoNBXQIs0iLacUcdQekWIlmGnYHo0hJVgV3CKVoyVYXAHgHo0hJLRV5CbRWiWbaIwF6BqI4UQZ7CLNIU8mMAnwFsSg5fQmzSJFRqaQAfgeUWksqAaAFgDgBoQaxKEkjogisWBmq1wijCrVozSnmEfMQpAqtaclpprhyAKULtWjJqY5DZhQBpgaxKJECpwu9Z1s56ZRVTguoBotNSQGpDLZ4GympvZVKIwEAAAAE//8grAu1aF15xIwyHAA=";
export { u8g2_font_smallsimple_te };
export default u8g2_font_smallsimple_te;
