/* u8g2 official font: u8g2_font_tiny_simon_tr (668 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_tiny_simon_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tiny_simon_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tiny_simon_tr', font)
 */
const u8g2_font_tiny_simon_tr = "XwACAwIDAQMEAwcA/gX+BQAA0wG1AoAgBCAXIQY1lSkAIgbrmUgKIwY3magVJAk3uWiKpggAJQk3mSiMklEAJgY3uXwJJwXpFQEoBjY3KRkpCDaXMIokACoGr5koBysHb7loigAsBSkVAS0Fp5kBLgUllQAvBzfZVDIEMAc3uVSVAjEHN7lITA0yBjeZsRwzBzeZMRIJNAc3mUgiEzUGNxlyJDYGNxmSIjcIN5kxSoYAOAY3GaoiOQY3GYokOgYtlSgAOwbxlEgAPAZuNzEAPQZvmXkAPgZul1ACPwk3mTGSoQgAQAY3GeoYQQc3GaqSAkIJNxkpmqIJAEMHNxlKjAhECDcZKVJNAEUHNxlSCgdGCDcZUgpDAEcHNxkykghICDeZSKqkAEkHN5kpTA1KBzeZMZQISwk3mUiaIikATAc3mTBzAE0HN5moUgVOBzdZqRIBTwY3GUpFUAc3GaoMAVEHN7mURAlSCDcZaoqkAFMGNxlyJFQHN5kpzAJVBzeZSIsAVgc3mUgrBVcHN5lIVQVYCDeZSMqSAlkJN5lIosIIAFoHN5kxSg5bBjaXKSVcBzeZME4GXQY2Fyk1XgXruQxfBSeZAWAG6pcwAGEGL5lJAWIHN5kwpAhjBi8ZcgBkBjfZsCJlBi8ZSRpmCTc5KZrCCABnB7cYipwAaAg3mTCkpABpBjWVaABqB/q2OIoGawc3mTA1JWwHNpcoSwBtBi+ZKwBuBi+5SQpvBi8ZigBwB7cYqgwBcQa3GIpMcgYulykCcwcvOSmSAHQIN7kwmkIBdQYvmUgidgcvmUhKAXcGL5noAHgGL5koB3kIt5hIIicAegYvGTEUewg3OSkSQwF8BTWVAn0JNxkxlCIJAH4Gb9kSAAAAAAT//wA=";
export { u8g2_font_tiny_simon_tr };
export default u8g2_font_tiny_simon_tr;
