/* u8g2 official font: u8g2_font_NokiaSmallPlain_tr (816 bytes, 88 glyphs)
 * Converted verbatim from u8g2_font_NokiaSmallPlain_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_NokiaSmallPlain_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_NokiaSmallPlain_tr', font)
 */
const u8g2_font_NokiaSmallPlain_tr = "WAACAgMEAgQFBwgA/wf/B/8BIgIrAxQgBQBxAiEHOVEyVAAiBxObklQAIw090VamNFQ1VJkSACQKRK8aR0rz0AklCjyxolaMsloCJgw90ZZTTLlKMqoAJwURWyIoB0JvpnoGKQhCbxJTlwIqCi3TVschc0oAKwot05pRHDKjCCwGEm+mAC0GDLcyAi4FCVESLwk7kVrFKkYAMAk8saaiZ1IAMQa6kbZ6Mgo8sbJRTirnETMLPLGyUU4a5ZEANAk8sR5VkkMXNQo8sbLyRjmPBDYKPLGm8opmUgA3CjyxMnLMMZcAOAs8saaiTCrKpAA5CjyxpqKZdlIAOgahcRIDOwcqb5ahAjwKPLEe2yijjAI9CByzMjIaAT4LPLGSUUYZxTYAPwo8sbJRrDMVAUAMPdG2shpqqZwWAEEJPLGmojmmDEIKPLGy4kjRHAlDCDyxNnI3GkQJPLGyoudIAEUJPLEy9Mr1CEYJPLEy9MptAEcJPLE2cppmGkgJPLES5ZjOAEkGOVFyBEoHO5HacwFLCjyxElWSWaYyTAg8sZJ7jwBNCj3RktdKKmk7Tgo90ZKnSnLbAU8JPdG2sndaAFAKPLGyojlSzgBRCkXPtrJXtWEAUgk8sbKiOVIzUws8sTZyRhrlkQBUDT3RMmRGGWWUUUYRVQg8sRJ9JgVWCz3Rku1UppxRBFcPPxGToYYpx1SmOmVUAlgKPdGSdaqrWgdZDD3RknWqM8ooowhaCTyxMnJs5xFcCTuREnOsYwBfBg3PMgRhCSyxplEaMQ1iCjyxkvOK5kgAYwcrkTZrAWQJPLFejWimAWUJLLGm4thIAWYHOnGmVgtnCjSvNqJMOykAaAk8sZLzis4AaQc5UZKGAGoIQm+WU0sBawo8sZJLlWQqA2wGOVFyBG0LLdEyUqWSSqoAbgcssbKiM28JLLGmopkUAHAKNK+yohwpZwBxCTSvNqJMuwByCCuRkoYsAXMHK5G28wJ0CDpxktIqA3UHLLESnWl2Ci3RknUqU44Adwot0ZJVUp0pAXgJLLESZVJRBnkJNK8SzbSTAnoILLEyYnsEfgg90XJ7jwEAAAAE//8A";
export { u8g2_font_NokiaSmallPlain_tr };
export default u8g2_font_NokiaSmallPlain_tr;
