/* u8g2 official font: u8g2_font_lastpriestess_tr (868 bytes, 66 glyphs)
 * Converted verbatim from u8g2_font_lastpriestess_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_lastpriestess_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_lastpriestess_tr', font)
 */
const u8g2_font_lastpriestess_tr = "QgADAwQEAwQFDA3//Qr+Cv4AdQIcA0ggBQDECiEIkkWKQ4kAJwhC9AmKBAArClXVq2CoFAwBLAhCNQqKBAAtBhVkiwIuBiJFCgIvDqVEy7RgLBgLxoJBADoHYlUKIgE7CIJFCiJFAjwIdE27UMYMPQc13YtqAT4JdE2LYKZsAD8Nl0ScyogmVJVDlQBBFKnDzPk0Io0IQ8KQzBYTBSWzAUISqMSc0khTTaQmkUlkEpHEBEMQqUTNkkwinWufRmYiCwBEFalEHdNMJAwJJUKJUCKUyERKRQBFEajEnMNMIozUxBojsoMEAEYOqMScw0wijNTEuhIBRxOqxM2akjQih4iJtlA1NJOZAEgUqMQcWU0ik1xkEplEJpFJZDUBSQikxBqTfiFKDabEu9FQLyGJ0ggASxOoxBxZTSIL1URqIZlEJpGVBkwNqMQc6VgfI7KDBABNFqrEHaltwiKZaJKIQhJRSCKVSKsCThKpRB2hTUKS6KeIEkU2kRkFTw2pRK2aipSvEpmsBFAQqMQcy0wik8gkJrFWIgBRDrk8rZqKlE8SJZJ9AFITqMQcy0wik9REaiGZRCaRmQRTD6jEnNIsIh6bV2kTCwBUDajEjMNETRQT65UEVQyoxAwhf5QEYyQAVg+oxAwho0Skt1CQKpYBVxerRA45u0QqEoVUJrLIJDgZyqSxGABYE6lEHZlIpiIdjyNRiVAiU5kNWQ6pRI2hRChSJMt1JgFaDKdEnENsqFfZ7CBhC2bEG0pMciJJCmIMhsQbmbAi4iShAGMLZsQrikyoFqEAZAuGxEsVCaXEJCllDGbEq1HoMJRFKABmDKW1q4lMVJFpSwRnC4a0mxMnSVFCAWgMlsQLoRbJhMRJAGkLhMYLsUiXiAQAag22rDupHCTUS0g0AmsMhcULmdKEEhlRFGwKhcWLmb6EJABtD2bEi0rKJDKJTCKTiABuCWbEi4qIJwFvC2bEq5GExCShAHANhrQLiWRCYroIhQBxC5asGwmlxCQpanIKZcULSUmmDQBzC2bEG4qUOpNQAHQMhsQrocgk1BKTAHUJZsQLES8TBXYLZsQLkUSn2TAEdw9mxAtJZBKZRCaRiyQCeA1mxAuRRBKTRZRIAnkLhrQLEU+SomgCeglmxIuTTNsBAAAABP//AA==";
export { u8g2_font_lastpriestess_tr };
export default u8g2_font_lastpriestess_tr;
