/* u8g2 official font: u8g2_font_koleeko_tu (774 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_koleeko_tu.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_koleeko_tu.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_koleeko_tu', font)
 */
const u8g2_font_koleeko_tu = "QAADAwQEAQQFDA3//gn9Cv8BcgAAAuogBQCxAiEHk5HigWYiCTXdQkKRpAAjEpbxRhKSRA6VUORQiYgiEgAkEZbxRhKSRA7S6SEiCUkiACUOmDFjRAlZaLyYIqQBJhKacYs6EU6k1BqJMhPNRqYAJwczneIQASgJtK9KoqRvCikKtK9CpqQvSgAqCUXXIpIymmQrClcVazg6DUcALAdEr2bFAi0GFdeiAC4GM5HiIC8OpvFSTSgTyoQyoRAAMA6W8YZyCFEsJNIhQgExCZORKnKI6AEyDZbxhmKUTSiz2aEAMw2W8YZilFSowkOEAjQOlxFTOCNJlCSH23ACNQuW8eJRWBUeLAA2DpbxakQRCisi0iFCATcJlxHjUeNuADgPlvGGcgiRJBQR6RChADkOlvGGcgiRJEUV0ggAOghzkeIgOwg7CHSxZuvEAjwIlxFztusOPQhV1eIwPQw+CZcRY7rbjgA/DZcRw3K4kUhz4BoAQBirj+smlYhGFBWKCkWFokKSyOSwQwQAQQ2XEadyOIxKhwOpNEIOlxHDchgdIofR4SECQw6XEadyGBWXDgdJBQBEDZcRo2Q5jJoODxEARQuXEeNhaLEMDw9GC5cR42FosQw3AkcNlxGnchhOPB0kFQBIC5cRQ9R0eDA1CUkLldHiMBltORwCSgqW8aZptqWFBEsNlxFj1HSIlCyipgFMCpbxYrbb4WEATRGZUUcmoRweKBFLxBKx2QZODJcRY2Q5HCimTgNPDZcRp3IYdTocJBUAUA6XEaNkOYxKh4hlOARRDZcRp3IYdTlILhMBUg6XEaNkOYxKh8hBVBNTDZcRp3I4TKuHBwkAVAmXEePTcE8AVQuXEWPUp8NBUgFWC5cRY9QnSW0aA1cVm5FjJCqJSqKSqCQqqRxkk2ksBlgOlxFjVDqIZpWDqGkAWQyXEWPU6SCpDZcAWgmXEePbtsMDWwmF0eIQ2lMBXA2m8UIoFUqFUqFUKF0JhdGitKdDAF4KSB5PSptIZgJfBicN4wEAAAAE//8A";
export { u8g2_font_koleeko_tu };
export default u8g2_font_koleeko_tu;
