/* u8g2 official font: u8g2_font_open_iconic_weather_8x_t (768 bytes, 6 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_weather_8x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_weather_8x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_weather_8x_t', font)
 */
const u8g2_font_open_iconic_weather_8x_t = "BgAGBgcHAgUIQEAAAEAAQAAATgAAAuRATkCYGBhE0BCXslpQTckZPSHoC32ijsSRNpNmys4qVvR6Yo6smTG0pabYlBuiM3YFb/AJPuEX/AP+gEHwT+gNPYJX6A5cYltoTkxaJQBBekCgEBhC0BCXslpQTckZPSEI3JCY06JSVgorcSMvFITAHg2EcjAUqcFYIsaieRgKx1konmaRgJpEEmoOi4ghNCQm8JA2k2bKzipW9HpijqyZMbSlptiUG6IzdgVv8Ak+4Rf8A/6AQfBP6A09glfoDlxiW2hOTFolAEJnPp8SmArsg7yAG2xEjagTtGJeyIy4ATveJxeqlbCSdWqlpFWpBbWcGBNjZkoNqSE3I0fshB7w84G+UCfiSJopQ1mrhiDsCL0CZ9wQW0JTZoysgT2uiDWpKhRG2kSeR9SclNZxAQBDqUCgEBhE0BCXslpQTckZPSHoC32ijsSRNpNmyk4ZimJFryfmyJoZQ1tqik25ITpjV/AGn+ATfsEvyBg3ZubEIE4gkTZBhNIEECsjPKzMUDgECSERGBBiMBmmRoaYFhqCSmyI6sAhrEKHuAYeQiUoCIWwGRJEYsgQCBKGQJAwBIKEIRAkDIEgYQgECUMgSBgCQcIQCBKGQJAwBIKEIRCkzKAYbQSGSAIARHS+3hHYE/BCO0Enyg240Y2wkWoFrTQzZKbYATu9kMsX8AZdgUNoi6yBPS5JVaEuU0biQJ8n5IyaEmNiSg2pNXJErtAhOMAG0QAZBuNjIAxPwSi8hJPoElCCQ0gIzmAZNgNm0Io0AkfIBuAAE4gCLEAGGABFlkCgENgj7IYcgSPLDTsBJZCEySAaIgSIgBAgAkKACAgBIiKDaJgIJMFE1A5Y0lJWS4o5NSWH5Iwe0WsiKCCFMBgSUGIIEAgIgSAgBIKAEAgCQhCBIQElhoGggBTC5BG9Rg7JKTUnJrWslFYCO2qESSAJk0E0RAgQASFABIQAERACREQG0TARSAJK2A05AkeWG3aCBwAAAAAE//8A";
export { u8g2_font_open_iconic_weather_8x_t };
export default u8g2_font_open_iconic_weather_8x_t;
