/* u8g2 official font: u8g2_font_saikyosansbold8_8u (840 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_saikyosansbold8_8u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_saikyosansbold8_8u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_saikyosansbold8_8u', font)
 */
const u8g2_font_saikyosansbold8_8u = "QAMDAgQEAQEFCAcA/wcABwABiAAAAywgB4jh8y8AIQmI4cnecR0EIgiI4Ui+8wwjEohhKdIwRIqmaIo0DJGiQwAkDYjhpcOiD7oyrDkKJQ2I4SOaIqlOiqZDACYPiGGNiqaIo7JI2qJDACcIiOHJdr4AKAmIYapmux0DKQmIYelmqx0FKgyI4Ri3YchGRWcFKwuI4YOyOIyyTgUsCYjhc5dVHQUtCYjhMw47VwAuCYjh80XWQQAvCYhhx6rnnAAwEIjhDJKmaIqmaIomDToGMQqI4amzx2GHADIPiOEMkiZrQ6bKw5BDADMPiOEMkiZrQ65o0qBjADQOiGENmSJ5GoZU1jEANQ6IYRwSedhlRZMGHQM2EIjhDJKmyMOkKZo06BgANwuIYRwSTTW7gwA4EIjhDJKmaNIgaYomDToGORCI4QySpmjSMCuaNOgYADoKiOGDso7LOhU7C4jhg7KOy6qOAjwIiOF6d4cAPQuI4dOGHRt2RgA+CYhh6a7uKAA/DYhhDVkmi6uO6yAAQBOIYQ1ZmESWKFGiRBqiHBkiAEERiOEMkqZoiqYMQ6Ipmg4BQhCIYZw0RVOGSVM0ZdgxAEMNiOEMkqbIbtKgYwBEEIhhnDRFUzRFUzRl2DEARQ6IYRwSWR4mWR6GHAJGC4hhHBJZHjTZTkcQiOEMkqbI0qIpmjToGABIEYhhaIqmaMowJJqiKZoOAUkIiOHJfgcBSguI4cpeNGnQMQBLD4hhaIpk0YZQ0SSbDgFMCohhyD4PQw4BTRCIYWjKw5AoiU3RFE2HAE4RiGFoyqQMiWVIpEVTNB0CTxCI4QySpmiKpmiKJg06BlAOiGGcNEVTNGWYZJ0AURCI4QySpmiKpmiKJg26AlIQiGGcNEVTNGWYNEXTIQBTD4jhDJKm6IOuaNKgYwBUCYjhDKPsOwhVEIhhaIqmaIqmaIomDToGVg+IYWiKpmiKJininKMAVxGIYWiKpiiJJVGGIbloOgRYEIhhaIomKeKoSJqi6RAAWQuI4Ui+DalsBwFaDIhhHNLx6zDkEABbC4hhDaHsecgxAFwJiOHkvucQAF0KiGENsY9DjgFeCohhxqOi1bkCXwiI4fP7MAgAAAAE//8A";
export { u8g2_font_saikyosansbold8_8u };
export default u8g2_font_saikyosansbold8_8u;
