/* u8g2 official font: u8g2_font_logisoso50_tn (850 bytes, 18 glyphs)
 * Converted verbatim from u8g2_font_logisoso50_tn.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_logisoso50_tn.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_logisoso50_tn', font)
 */
const u8g2_font_logisoso50_tn = "EgAFBQUGBQcHHTwA/TLzMgEAAAAAAzYgBgCAQDAqL9Wy4zAqYFkaSEEGQYxCFOEIReDCRB60qAU9ZApcKMIRiFGIQgykIEMqYBkCACsSc7rKsDGa+c4HfqAyRjPvACwPJrE9aSACFoohEFEAAC0J07jQMPgDFS4MxrBAaSACFogAAC86WKZAcDzBI57gEY9oxFM04ika8RSNeIJHPMEjnuARj2jEUzTiKRrxFI14ikY8wSOe4BFP8IhHBAAwNVmmQHA64MKeFJ2pVEQJykAOIo50hGM5q2ns//9/rVnOOsKRDoEcZChBIVWZTpQetsAjATEaTN5AsDErJ4KMRHzgA0FIxlEMY/7///8HMkxZpkBwOuDCnhSdqVREEclADiKOdIRjOatprNYsZx2hWIcg2CGEdkQkHhGJp4jEU0TiERGIxCMiEIlHROIpIvGICETiEZH4gT+gATNBWaY/MPgHtIjEIyIQiUdE4iki8YgIROIRkZhA5TGtYQ1UJCKPacxjmn/yKAE7xrAOYSQkJAYZFqGMhCDltCQBND5ZpkBwMuSZNOSZNORJGtOQJ2lMQ56kIc+kIU/EQAcxkFGMcxTjHMU4RzGOYQxzGMMc5TAf+ANaM6b5ZwA1PlmmQDD4DwTT/DeONBmqVMQal2CCIpKDBCQd4VjOahrTjGl+k2lMa5azjnCkQyAHEUtQSFWmE6WHMe9IADZKWZ5AcDoew54UnalURAnKQA4ijnSEYzmracw0P5GgyVTEGta4hFKSgKQjHOoIx2oa+9ea5awjHOkQyEGGEhRSlelE6WELPBIANz9ZpkAw+A8ErFnOOoKxjmCsIxgKCYY65Cki8ZCneMizeMhTROIhTxGJhzxFJB7yFA95ikg85Cki8ZCniCwAOFRZpkBwOuDCnhSdqVRECcpADiKOdIRjOatp7GPOOsKRDnGkQyQlGVWZToSiM5WKKEEZyEHEkY5wLGc1jb3WLGcd4UiHQA4ilqCQqkwnSg9b4JEAOUlZpkBwOiCznhSdqVRECcpADiKOdIRjOatp7B9zlqOQcCQkJEUR17CRykwoEcY0bzKNxZx1hCMdAjmIWMIyqjKdKD2MeUcCADoRhrNGaSACFogPVoiABSIAAAAABP//AA==";
export { u8g2_font_logisoso50_tn };
export default u8g2_font_logisoso50_tn;
