/* u8g2 official font: u8g2_font_tenthinnerguys_tu (719 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_tenthinnerguys_tu.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tenthinnerguys_tu.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tenthinnerguys_tu', font)
 */
const u8g2_font_tenthinnerguys_tu = "QAADBAQEAgQFCg0A/Qn9CQABZQAAArMgBQBiBSEHkuIEEwEiCkW2hQgVkSgAIxCYYo6QyEOIkLw8hAiJACQNpuKVGItQJRE2IQAlD4hmxthIkMngLEYhYwMmC2bqlaAQk6AQACcIQzpFSggAKAqW4qXY0IwzCikKluKF4JxmEwQqD3cmTljIlLKxkilhIQArC2bmlaAQk6AQACwIMx6NCAkALQYlroUCLgYy4oQBLxKK4j6I+PCI2NDIYPE4SDAAMAiW4oUTnRwxB5LixMMAMgyW4kWJoYiKoCADMwyW4kWJ4YmhYAsANAmW4oUQJUc5NQuW4oVjiaFgCwA2DJbiTWMJEhEKCQA3CJbiBaP8ADgOluINCZIICRIRCgkAOQ6W4g0JEhFKoUgJCQA6B3LihJEBOwqDHo2MIiIkADwNlaJlmNBICtGYYAA9B1bqBTMDPg6V40Wg2BBJypBYIAA/D5biDQmSoBDROJCgEABAD5miLtKJ0cg0ERlFsABBDJbiDQkS0UMQJQFCDZbiRQkS0YkQUQsAQwmW4k2jHE0KRAqW4kUJEp1aAEULluKFY0mJoCADRgyW4oWjYEmJoEQARwqW4k2jJEooBUgLluKFEKWHIJoESQmUYgWKkFwQSguW4qUciYhQSABLDZYjhhAVlBKRIkoCTAiW4oWgfGRNDZhihmDRg4kIIY0CTgyW4oVQyUNIEU0CTwuW4g0JEp1QSABQDJbiRQkSUYugRABRC6beDQkSnY4KBVIMluJFCRJRixAlAVMLluJNY1GhYAsAVAmW4gWToHwCVQqW4oUQfUIhAVYKluKFEH1BIQJXEJhihiAtIiQiJCIkIk0DWAyW4oUQJRQSJEoCWQyW4oUQJRQyQZkAWgmXIobj2BwdWwiUYoWSnBBcDJmi3vC0B7bhaQBdCJRiBZKcFF4INvqVGIkBXwcoVsZDAAAAAAT//wA=";
export { u8g2_font_tenthinnerguys_tu };
export default u8g2_font_tenthinnerguys_tu;
