/* u8g2 official font: u8g2_font_minuteconsole_tr (734 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_minuteconsole_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_minuteconsole_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_minuteconsole_tr', font)
 */
const u8g2_font_minuteconsole_tr = "XwACAgIEAQQEAwkA/gf+BwAA6AHbAsIgBEBsIQZdVIYKIgbLZpIKIwlfZFJOOeUUJAdfZDb3ACUJX2RSTLGKKSYHX2SSXwEnBclWBCgHX2RTWRcpCF9kclmVACoGT2ZSBysHT+XSSgAsBclTBC0Fx2UGLgVFVAIvCF9kq1jFCDAHX+QqrwoxB1/kkuwaMghfZHRMZRwzCV9kdEw5LgA0CF9kkjViAzUIX2RGzOUCNglf5GZUSVUANwhfZGYVWwA4CV/kKtVSFQA5CV/kKpVkXAA6BtVUcgA7Bt1TMhI8BtdkU109Bk9l9gA+B9dkclUCPwlfZHRMMcMEQAZfZPYDQQhf5Co1lBVCCV9kVFIrqQVDB1/kZrcARAhfZFTyWgBFCV9kRowjxgFGCV9kRowjlgBHCV/kZhxJJQFICF9kkjWUFUkHX2RW7BpKB19kZucCSwhfZJK1khVMB19kYs8BTQhfZNJQXgFOB19kVPIVTwdf5CqvClAJX2RUUiuWAFEHX+QqryRSCV9kVFIrWQFTCF/kZi4XAFQHX2RW7AVVB19kkq8kVghfZJKrrABXCF9kktdQAVgIX2SS1bICWQhfZJJVtgBaCF9kZlXGAVsHX2RG7BxcCF9kYo51DF0HX2Rm5wheBcvmGl8FR2QGYAbKXmIAYQdXZHRaSWIJX2RiVMlaAGMGV+RmLWQIX2SrZSUBZQdX5KqhBWYIX+TmiE0AZwhf45aV5AJoCF9kYlTJFWkIX+Qykq0BaghnYzOSnQtrCV9kYqVWUgFsB19kZK8BbQhXZNJQVgBuB1dkVHIFbwdX5CqrAnAJX2NUslaMAHEIX+OWlWQBcghXZFSSJQBzB1fkdl4AdAhf5GJasQV1B1dkkisJdghXZJJVJgB3CFdkkjVUAHgIV2SSaqkAeQhfY5IryQV6B1dkZioHewhf5HbKKQt8Bl1UjgB9CV9kdMopLwB+BUvlGgAAAAT//wA=";
export { u8g2_font_minuteconsole_tr };
export default u8g2_font_minuteconsole_tr;
