/* u8g2 official font: u8g2_font_5x8_tr (843 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_5x8_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_5x8_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_5x8_tr', font)
 */
const u8g2_font_5x8_tr = "XwACAgMEAwQEBQgA/wb/BgABGgIxAy8gBQB+AyEHMWMzUgAiB5tuk6wAIw09YlemNFQ1VJkSACQKPWKbV71T2hElCKtmE1NnACYKPGIXU7NqpgAnBRlvMygHsmKnmgEpCLJiE1OlACoKLGITkxpJxQArCi1im1EcMqMILAebXqdKAC0GDGozAi4Hm16XVgIvCDRiX7YzADAIs2JXuSoAMQezYpdkazIKNGKnYk4qjwAzCjRiM2LUSCYFNAo0YhtVNWJOADUKNGIz9EYyKQA2CjRip/KKMikANwo0YjNyzDFHADgKNGKnYlJRJgU5CjRip6JMOykAOgeqYjPiCDsIs15nI1UCPAezYpvKXD0IHGYzMhoBPgizYpPLVAI/CbNi10wZJgBADEVeK6NcSSVZQwVBCTRip6IcUwZCCjRis+JIUY4EQwk0YqeiLpMCRAk0YrOicyQARQk0YjP0ynkERgk0YjP0yjUARwo0YqeiTjMpAEgJNGIT5ZhmAEkHs2KzYmtKCTRiN3NVRgBLCTRiE1WSqTNMCDRik7tHAE0JNGITxxHNAE4JNGIT11hnAE8JNGKnojMpAFAKNGKzohwpZwBRCTxep6JcbhRSCjRis6IcKcoAUwo0YqdiyqhMClQIs2KzYhcAVQg0YhM9kwJWCTRiE51JKgBXCTRiE81xxABYCjRiE2WSKsoAWQs1YpN1qjPKKAJaCTRiM3JsjwBbB7NiM2JzXAo0YpMzyiijHF0Hs2IzmyNeBpNy1wBfBgxeMwJgBpJyEwNhCCRiN6JMA2IKNGKT84pyJABjB6NiN7MAZAk0Yl+NKNMAZQgkYqfSyApmCTRiW5UzRwBnCSxep2LaSQFoCTRik/OKZgBpCLNil5GsBmoJu16bYakqAGsJNGKTy5GiDGwHs2IjuwZtCSVio1oqqQJuByRis6IZbwgkYqeiTApwCSxes+JIOQNxCCxeN2LaBXIIJGKTkp0BcwejYjfyAnQKNGKX48wpJgB1ByRiE800dgejYpOsCncJJWKTVVJdAHgIJGITk1QxeQosXhNlGjEpAHoIJGIzYjkCews8YqsyShrFjAR8BTFjc30MPGKjUcxIZZQkAH4HFHKXVAIAAAAE//8A";
export { u8g2_font_5x8_tr };
export default u8g2_font_5x8_tr;
