/* u8g2 official font: u8g2_font_pearfont_tr (624 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_pearfont_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_pearfont_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_pearfont_tr', font)
 */
const u8g2_font_pearfont_tr = "XwACAgMDAgMEBQYA/wP/BAAAygGYAlQgBIBsIQahVFQAIgaTZpIKIwec7NJYCSQHo+PiiAklB510Yi4DJgis7GKKlRonBZFWBCgGotxUDCkHolxiUgAqBptlUgcrB5vk0koALAaS2xQALQWKXQQuBYlUAi8Gm2RTCTAGklxGADEFkVQEMgaTZKQAMwaaXOIANAebY1KSATUGk+RGAjYGmlzSCDcGmluUAjgFmlwOOQaaW0YKOgbZXFIAOwai27ICPAaa3GQAPQabZPYAPgaaXKICPwaiXFQOQAmt82SVVE4LQQeb5NJIAUIHm2TUUABDBppclgBEB5tkVFoARQWaXA5GBppchgJHCKNjRkojAUgHm2TSUAFJBptkVhpKB6NjZlwASwabZNIqTAaaXFISTQacbC4ZTgecbJSaAU8Hm2RGGgFQB6NjVFoRUQej41aSAVIGm2SUKlMHm+RUUgBUB5tkVkwAVQebZJIaAVYHm2SSqgBXB5xs4hoCWAabZFIHWQebZNJICVoGm2RkFFsGolxWElwGm2RyAV0GolxUGl4Fk+YaXwWLYwZgBpJeYgBhBpNk1ABiBppc0ghjBpJcRgBkBprchgBlBppbZgBmBprcVAJnBppbRgpoB5tk4kgBaQaZVFIAagahU5IAawabY9IObAaaXFIMbQaUbK4AbgaTZEYKbwaSXEYAcAaaW4YCcQaaW0YKcgaSXBYAcwaT5EYCdAaaXNICdQaTZNIIdgaTZFIFdwaUbNQQeAabY1IHeQebY1KZAHoGk2SkAHsHq+RUHQV8BqFURgB9CKtkZE5JAX4HlO2SSgAAAAAE//8A";
export { u8g2_font_pearfont_tr };
export default u8g2_font_pearfont_tr;
