/* u8g2 official font: u8g2_font_dystopia_tr (940 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_dystopia_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_dystopia_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_dystopia_tr', font)
 */
const u8g2_font_dystopia_tr = "XwACAwQEAQQFCQ4A/Ar8CgABPwJ1A5AgBQCxAiEGonHyJCIJNd8iUVIKACMNpdGWko4qdVSUlAIkDbXPKk43Vox1jSIAJQyl0SJRsjgtZYkNJg2l0Tbd0ETJEnVNACcGMn9CBSgIo5F26TUJKQmjkSJNel0AKglV2yJdqUsAKwtl0xpD4THGUAgsBjJvQgUtBiXXcgwuBSJxQi8MpdGuHGVRFkdZBjAOpdE2XbMUSZE8XRMAMQml0Tax9ToGMgyl0TZdsuqI5GMAMwyl0TbVojyrrwkANAml0a6KjloPNQul0XLUVK2+JgA2C6XRNt3UxbomADcJpdFC1eJaDzgLpdE2vSaJdU0AOQql0Ta9aN0RADoGUnFCEjsHYm9CUgE8CGXTOp0zOT0IVdVyzOAxPgll0zLS4zUCPw2l0TbV4jTKMlIWAUARqVH3qMuQmqiJDGv4kC4AQQml0TY9Ll4CQgul0UI9KIl1UABDCqXRNt16XRMARAql0UJdfB0UAEUMpdE23eMoq6sJAEYKpdE23eMo6wZHCqXRNt1arIsASAql0SKxjouXAEkGonHyMEoJpdGub+qaAEsKpdEisQ5K4iVMCaXRIut3NQFNCqXREk/UcfESTgql0RJS1HHxDE8KpdE2XXxdEwBQCqXRNtUHJesGUQ3VyzZdvGSJmuVZAFIKpdFC1Qcl8RJTC6XRNt0krb4mAFQJpdFyzLB+AlUJpdEi8dc1AVYKpdEi8Zc0TgBXCqXRIvE6LmoOWAul0SKxpHGSeAlZC6XRIrEuWnmNAFoMpdFyzNIRyepjAFsIo5FyRHoZXAyl0SLLsxqS5VkBXQijkWLpdQReCEXdNk4SJV8GJc1yDGAGNL8iK2EIVdFC1dQBYgqV0SJrU/VBAWMIVdF20BUBZAmV0a7roCsCZQlV0TZJdDUBZgu0rXaI4jFqxgBnC6XJLh10RVPXBGgKldEia1MXSwBpB3JxQh4BagiyaUIeRwRrDJXRImtFEmVJlABsCJORIumnAG0MWDFDScckURKlAG4IVdFCXSwBbwhV0Ta9JgBwCpXJQtUHJWsDcQqlyS4ddEXrAHIIVdE2XbQMcwhV0WbXFgB0CZORImkdkSh1CVXRIrGuCQB2CVXRIrGkcQJ3DVgxI0mUREnHJEoAeApV0SJR0iRRAnkLlckisS6auiYAeghV0VKKo1h7CqSxKk3SUnMUfAaicfIwfQyksSKO4jSJqkkEfglF1SbO0CgBAAAABP//AA==";
export { u8g2_font_dystopia_tr };
export default u8g2_font_dystopia_tr;
