/* u8g2 official font: u8g2_font_profont10_tr (839 bytes, 96 glyphs)
 * Converted verbatim from u8g2_font_profont10_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_profont10_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_profont10_tr', font)
 */
const u8g2_font_profont10_tr = "YAACAgMEAwQEBQkA/gb+B/8BEgIoAysgBQBiAyEHMWMzUgAiB5N2k1QAIwotZlcNVQ1VASQMRV6bh8o7qWpHACULNWI3VDKVSjIBJgo0YhdTzEnFFCcFEXMjKAjDXpvKdgEpCENek8tWCSoJLGYXKxUrACsHG2aXVgIsBxpalxQALQWKaiMuBQljEy8KRFpf5phjzgAwCjRip6IaSSYFMQezYpdkazIJNGKnYo7lCDMKNGKnYo1kUgA0CTRiG1U1Yhw1CjRiM/RGMikANgo0YqfyijIpADcJNGIzcqxLADgKNGKnYlJRJgU5CjRip6JMOykAOgYhYxMDOwgyWpdhUgA8B6tim+oCPQgcZjMyGgE+B6tik6sSPwk0Yqdim4oAQAk0YqeiutEAQQk0YqeiHFMGQgo0YrPiSFGOBEMJNGKnoi6TAkQJNGKzonMkAEUJNGIz9Mp5BEYJNGIz9Mo1AEcKNGKnok4zKQBICTRiE+WYZgBJB7Nis2JrSgg0Yt+WSQFLCjRiE1WSMpUBTAg0YpO7RwBNCTRiE8cRzQBOCTRiE5eaZgBPCTRip6IzKQBQCjRis6IcKWcAUQk8Xqeiy0YBUgo0YrOiHCnKAFMKNGKnYtJIJgVUCLNis2IXAFUINGITPZMCVgg0YhO9YgRXCTRiE81xxABYCjRiE2WSKsoAWQk0YhOtmEsAWgk0YjNybI8AWwdCX7N6CVwMxFqTM8oZ5YxyAF0Hwl6jeg1eBpNy1wBfBg1aMwRgBpJ2EwNhCCRiN6JSBWIKNGKT84pyJABjCCRip6JGA2QJNGJfjSjTAGUIJGKnhkYDZgmzYpvSihUAZwo0WjeiTDspAGgJNGKT84pmAGkIs2KXkawGagjCWhdVSwFrCTRik6skUxlsB7NiI7sGbQklYjNSpZIqbggkYpOSKQNvCCRip6JMCnAKNFqzohwpZwBxCTRaN6JMuwByCCRik5KdAXMIJGI3NhoJdAizYhfTijl1ByRiEy1VdggkYhOtGAF3CSVik5JKqgt4CCRiE5NUMXkJNFoTzbSTAnoIJGIzYjkCewnLWptilWMdfAZBX3MIfQrLWpNjnWIVAX4HFGqXVAJ/BQBiAwAAAAT//wA=";
export { u8g2_font_profont10_tr };
export default u8g2_font_profont10_tr;
