/* u8g2 official font: u8g2_font_trixel_square_tf (763 bytes, 106 glyphs)
 * Converted verbatim from u8g2_font_trixel_square_tf.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_trixel_square_tf.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_trixel_square_tf', font)
 */
const u8g2_font_trixel_square_tf = "agACAwMDAQMEBQkA/gX+BQAA2gHBAt8gBEAmIQZpKlMAIgbTM5EUIwnteakqVaUAJAhzclFZRQAlCGsyUVhGASYJbTpjFFLJAicF0SsCKAdqLlNKACkHai5SagAqBlszUQ4rB1ty0RQBLAXRKQItBcsyAy4FSSoBLwlrspEUSSEAMAdrMpSKADEGam5TBjIHazJURA0zB2syYyQSNAdrMpFEJjUGazLkSDYGazIkRTcGazJjDjgGazJURTkGazIUSToGWSpRADsG4SmRADwGW3KkAD0GWzLzAD4GWzIiBT8JazJjJEMRAEAJ9Tm2FEk0VEEHazJUJQVCBmsyVEVDB2sylBgRRAdrMpSKAEUHazKkFA5GCGsypBSGAEcHazJkJBFICGsykVRJAUkFaSoFSgdrMmOSAEsJazKRNEVSAEwHazJh5gBNCm06EjVFUiQHTghsNtIkLQNPB2sylIoAUAdrMlQZAlEHbDZTvghSCGsy1BRJAVMGazLkSFQHazJTmAVVB2sykRYBVghrMpGKigBXCW06sSqSIgNYCGsyERVRAVkJazKRRIURAFoGazJjOVsHazJkcgBcCGsyoRiKAV0HazJjkgBeBtMzVABfBUsyA2AG0i9SAGEHXDZTigBiB2syYUgRYwZbMuQAZAZrsmFFZQZbMtUAZgdqLtMUAWcGazEUSWgIazJhSEkBaQZpKtEAagd6bXGUGmsHazJhqgpsB2ouUZYAbQddOlYkJW4GWzKUFG8GWzIUAXAHazFUGQJxB2sxFJkAcgZaLlMEcwdbclIkAXQHai7RFAl1BlsykUR2B1syERUBdwhdOlEkRQZ4BlsyUQ55B2sxkUQSegZbMlM0ewhrclIkhgJ8BWkqBX0JazJiKEUSAH4G27IlAKMIbHZTLIYEpwd7MSRFEqsG0zKRFLsG0zKRFMQJezJRTFVSANYIezJRTKkI3Ah7MlEcaRHfB3sxVDME5AlsNlEMTikC9gdrMlFMEfwIazJRHEkEAAAABP//AA==";
export { u8g2_font_trixel_square_tf };
export default u8g2_font_trixel_square_tf;
