/* u8g2 official font: u8g2_font_streamline_interface_essential_key_lock_t (573 bytes, 9 glyphs)
 * Converted verbatim from u8g2_font_streamline_interface_essential_key_lock_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_interface_essential_key_lock_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_interface_essential_key_lock_t', font)
 */
const u8g2_font_streamline_interface_essential_key_lock_t = "CQAEAgUFBAEGFRUAABUAFQAAAAAAAiEwQrLmGgfiVDSXTA2CCUUkEYwkBolYRJFQxCKKQSKWiRWVpSSxzCKSyoQik0wqlEiFIoNMk0yiUWSSSYXCkXEkrwExKazyegarWCajSWQUGc0gIzKVJoKZWEqiiwQjs1TJLBKMzFIls0hSBTJGteKaB/rBIL1ZOYqEVJJJSCUJhVSSSUglioRUkklIJQllBgeKSW2kbaRNi1BaIgllMopBIjVSDBJhiSScCEWSmUFocAIzOrXiGgdylVSpS6fyqDwoPciEQ4nQ4MQmOkhoEgeJQUKTaBKxSbQJRTJVg0welkflU+mcUqqSD4QANDi14jrWi9xAJ0vFVLlULBfOhXPhXHZwoMwGs8HQKJhZZIKZgSYYGgVThamiTDYjSoZUg6vEegE1VLTiGgeDcC4aGUiCke4SmYpkpiK1yiRCmcRgoAhlQplEKBPKJDKDQaYikotkEpHIJDFYRCKTmkQkU5JJRDIlmUQkF8kkMoNBZLDIg1KDDzSDDwQ2LK/umgaDXFUylAwlQ8lQMpTMDB4k0lYr0SIkGohUK1lMFpPF1IlsZnAgATdAseq6BoOgTiQaKVKZlCgVEqVColRIlAppBjeSZESSSWQiksgiEpFEBpKIJLOJJIoqInWRTGQwiKSSuUqNeAc4PLPmmgaDbC5ZmAwmg8lgMpjMDR6k8pigShFSJDWLzMYqU6SJtMokmqQyiSapTEUkF6lJxDKiyECiUgAAAAAE//8A";
export { u8g2_font_streamline_interface_essential_key_lock_t };
export default u8g2_font_streamline_interface_essential_key_lock_t;
