/* u8g2 official font: u8g2_font_open_iconic_human_8x_t (729 bytes, 5 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_human_8x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_human_8x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_human_8x_t', font)
 */
const u8g2_font_open_iconic_human_8x_t = "BQAGBgcHAQUIQEAAAEAAQAAAoQAAAr1AoUBYDLwp5ghrQTWkJwR9o82UQRDI5XAcVUNqTA2qETWsxtPAGk1DazAMjrE0lgLTSBqKwWkcjsTwOAwHcngchSM5QI7hgSCgh/BAEkYAeQQQREEIEBACFTwQCPIQHggEeQyOxKlwIE6GI2EkjqOhKJRG0lgMS2NhcAymoTWaBtZ4GlYjalCNqSE1KofjuCAIJDNxIw8UekgNamkjsmIDAEG+QGAInBWmA3h4GB6ieXCJJbIpkom2OCjborBsi+HClThSN/JE3YgjbSXNlJmyE8YQMhiDuGAMw3IxEMrFUCQXg4FcDMeBLSAGtpAW14JaVIuKMS0qR7SoIM+ikjSLirIsKkuyqBbC4lhUC0JhLKqFkSgW1QJBEItqoRiIRbVgCMSiWlCLakEtqiVqYTGkxdWAFpjDWWQPZqFBlMUWQRacxFh0E2LhUYTFBwI/oUfsjBxyU2rMzIlBL6lFBQBCYkBbCcwgMETlkBxR5Ik0FIayWBRLgkEwh8bQFFsFh+AMHsF7wQ/4fwAi8Al+A6/QGboDl9gWWiN7YJFrYlWqC5WZNlIn+kChZ+SUmhOTWlZKK3khsWNm1IobkRt2Qi/4AEOgQGAInBpwRc2YHTHklbiTdrIZGAqmWCYXY5FYDkVSQRTJJEkkEgWRSJQkElmQSGRBIpEFiUCXBAJhkEeEQR4RBnlEGOQRYRCHhEEcEgZpTBiEQV0SRmVBFpcFUWAWxbBRWAoXgCTcAIJwBcjBHSDGpoAUGkMyZA930k6IgTZQJEMBKyQS4WAdkkigkBRIJGA4DCQSPJBHgkPwPwz9YQBEWkBgCNwZboYMeSUtZbWkGBRzakoOyTV6RK8QBIL/Qo/oNXJIrlJzYlBMalkpreSFyIzbkBJAQoXwENCCWzQNrbE8LkgioSRHBaoUGkRD8Aaf4Bf8gP9/AAMAAAAE//8A";
export { u8g2_font_open_iconic_human_8x_t };
export default u8g2_font_open_iconic_human_8x_t;
