/* u8g2 official font: u8g2_font_squeezed_b7_tr (859 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_squeezed_b7_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_squeezed_b7_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_squeezed_b7_tr', font)
 */
const u8g2_font_squeezed_b7_tr = "XwACAwQEAQQFCAgA/wf/BwABFAI2Az8gBQBxAiEHcnFyjAIiByXbIlECIwpXE6e6VJcKACQLdvEqHzJ9yCIAJQx28SJSMiSrIYkUJgt28TZKmqNUiQUnBSJ7QigHc5FG6RQpCXORIkpaFAAqCVXTIklTNSkrCDS1JlESACwFIm9CLQUTlzIuBSJxQi8JdLGqElWiCDAKdbE2SbykCQAxB3ORVukBMgl0sTKLklIkMwl0sTKLtVgBNAh10SKxbg01CXSxYs6iWAE2C3XRNskyJVHSBDcJdLFCqkQtADgMddE2SZQ0SZQ0ATkLddE2SZREU9IEOgdCcyJDAjsHUm8iQwQ8B1SzKqkVPQYzlTIPPghUsyKrlAA/C3SxMouSKMMSAEAKdvFGiVQ3SAFBCnXRNknUIbEEQgt10UJJlCVRFgBDB3SxVuoeRAl10UJJvCwARQhzkVJJlTRGCXORUkmVCgBHC3XRNsnyRUkTAEgJddEisQ6JJUkGcnHyAEoHc5GmVwFLC3XRIlHWSEmUAEwHc5Ei6TVNC3cRI1dHFdFsAU4KdvEiVsdUMgVPCnXRNkm8pAkAUAp10UJJlCWrAVEKdvE2SvoZiQVSCnXRQkmUJbEEUwlzkUaJkkQBVAh0sUKJegFVB3XRIvF1Vgp28SLylGgRAFcQeDEjQzREQzREScckSgBYC3XRIlHSOEksAVkOdvEikhItQzIkQyIAWgl0sUJKligSWwdzkVLpGlwJdLEiyqJaFF0Hc5Ey6SpeBiS7JhFfBRORMmAGI5siCmEIVdFmsSQCYgp10SLLlMSyAGMHVLFWqgdkCXXRrrJYEgFlClXRNkmHDE0AZghzkUZVWgBnCWXPZlESeQFoCXXRIsuUxCVpB3JxIh4DagmDjyZDuigAawl10SKrLIklbAZycfIAbQtYMXOpKImSKAVuCFXRQklcAm8JVdE2SSxpAnAJZc9CSSxLBnEJZc9msSRaAHIJVdEiWbIaAHMIU5FGShQAdAlzkSJJlVIAdQdV0SJxHXYJVdEicUkTAHcMWDEjQzRESZSmBHgKVdEiSeMkUQJ5CmXPIrEkcpoAeghTkTJR0gB7CXSxKonSqBZ8BnJx8gB9C3SxIoviJEoiAH4IJvsmURIAAAAABP//AA==";
export { u8g2_font_squeezed_b7_tr };
export default u8g2_font_squeezed_b7_tr;
