/* u8g2 official font: u8g2_font_open_iconic_embedded_4x_t (906 bytes, 17 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_embedded_4x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_embedded_4x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_embedded_4x_t', font)
 */
const u8g2_font_open_iconic_embedded_4x_t = "EQAFBQYGBQQHICAAACAAIAAAJAAAA25AJCAGGQw4wkcIShCCEoSgBCEoQQjK/ihBCEoQghKEoAThRwBBKyAIEdwMrFRmOtKJEITvSU7WKEYtK2FHK9zwhBc+8AHhg4MIRrKxCQcAQkcgCBHsiG1oYwbGMMEiBjKIhB3tYAhLlkpIog50pEMdRVFKUBgdU4KiFIIoBJ1UQhJlJQxhRztYIgYyiBUYwwTT0MYmHABDMtCHE2yMZCgjGcpIhjKSoZzgCCc4ylCFMlSxClWsYhHmCc5gyFKUg6AjGYtgQxMWAEQxHhcZ7IRNZMMqk4mOkxaVLKMNLngDM/hnEIQYBCEGQYhBEGIQhBgEIQZBiEEQMgBFKN8HEXwFTmgjn8vGExLxiCQ8AyNWoYx04PPeH3RiI5m5UKUmFrkARkGgBhnMBC/qBCdtQxtFmEYRJDKIiAwiIqOASTAOI4iQCU905AhJMcjxDGJEwhSRMIQkDDGHI1ABCVRAAhVQ4ABHPxwIEcyIa1ijHhWhyFSkEhnIvOY5riBFM4jBDGKsgxzqIEdCyJEQgiCEIMcyVsEINhaijIUsYiFLYMgH/gBINCAIETwJbeBTNvIJo62AIUpgSBoY1aQ2sYlRi1oTW4LRFroeHYRRBUJYgQx3EEM2NqEBSRIgBhkMOMJ/5AP/DxSE/wgASksUWBFchkjA4h0NYYoigpEIYRBBEMQIpPIUIyDEGIcwjBEMpCyEIUtJRjDMIQyCECMkRQlEMYIgCGIYQhiICEZSFMKOVjwCDgwAS0QgCBHMkOpAqVFrGUhijHGaYxQHGcRJxXhUIZ5FiGcRAVoVo98qwrMI8SxCPKoYTiqIg4zSHOMwxkjLQBbVJOhUhAFMGhwIEQz+/wNR0D4Y/cAfSERGMJKJD/wABk0qFEgR3ARYtGMhCg0J4UAqhCj0kBAOpEKIQlSSFsRKywfxoyEMYccBAE5KHAgRzAhMngwKUYI1EIIMqRjEKI4xiGGUohClIIQhjcIQphDEIYXiECdBBEIoOprIIhCSEAUsBgEJUriiGMo4hzmStCDHSEQBTzwgCBHMkOoc4URlMJQgynEaYjBlGC4RRUREAZNQQCUQcAnEgzj5dYITvLQLbjhhGYxYiEEW1SToVIQBUCweCBGsFCgljHBBUUooZCEGO3zwDjKdBznoEYaAAQs++B6RjYtYtGtkogEAAAAE//8A";
export { u8g2_font_open_iconic_embedded_4x_t };
export default u8g2_font_open_iconic_embedded_4x_t;
