/* u8g2 official font: u8g2_font_minicute_tr (964 bytes, 94 glyphs)
 * Converted verbatim from u8g2_font_minicute_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_minicute_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_minicute_tr', font)
 */
const u8g2_font_minicute_tr = "XgADAgMEAwQFCAsA/Qf9BwABQgJ/A6ggBQBiBSEHOePEoAQiB5M2RaIEIw69ok0pSQalMiilJAEkDcWiVbbUtkSpbBEAJQ/G4k2mREkUNiVRoiUAJg29ok2WRElWSaRICScHmvJMogAoCLsiVVKqFSkJuyJFVqqUACoJpa5FUpmWBisKraZVGA1SGAEsB5reTKIALQaMasUQLgaJokQALwzFomUWZmEWZiEAMAu9olWW1GxJLQIxB7rizNIDMgy9os2ShZGUhYMAMwy9osUgZpmqJQsANAy9ol0mJaVk0MIENQu9osVxSEMtWQA2DL2ilZSFQ5JpyQI3Cr2ixSBmjTUAOAy9os2SacmSackCOQy9os2SackQVhYAOgYh50QUOwiy3kyaKAA8CLxiXdTYAD0InarFoA4CPgi8YkXY1AY/C72izZKFWR2KAEAOvyLWEIWSolQs9UEBQQu9os2S2YYh0wJCDb2ixZBk2qBk2qAAQwq9os2SiW3JAkQKvaLFkGTeBgVFCr2ixTGcwnAQRgq9osUxHJKwCEcLvaLNkomlLRkCSAq9okVmG4bMFkkIuyLFEnUZSgu9os2QhS1RJAFLDb2iRSYlJS2JKlkATAi9okXY4yBNCr2iRbYsieYWTgy9okWmTUoibVoATwq9os2SeUsWAFAMvaLFkGTaoIRFAFELvaLNkrkkUqQEUg29osWQZNqglCpZAFMLvaLNkqmrliwAVAm9osUghT0BVQm9okXmW7IAVgy9okVmS0pJFkYAVwu9okXmkiiJ0gVYC72iRaYltUpNC1kKvaJFpiW1sAlaCr2ixSBmHQcBWwi7IsUQdRpcC8WiRRqmYRqmAV0IuyLF1GkIXgidslWW1AJfBo2ixSBhCa2izaCZFCViDL2iRRgOSWYbFABjCKxizZAVB2QKvaJlZdBsyRBlCq2izZINQzoEZgu9opVUyYYorAFnDMWWzaDZkiHUkgVoCr2iRVgxabYAaQi7Ik0otQxqCsxaXay1SYkCawu8YkVWUhIpKQVsCLsihdTLAG0MryLGokSRFEmRVG4JraJFYtJsAW8JraLNktmSBXAMxZbFkGS2QQmLAHEKxZbNoNmSIWxyCa2iRWISiwBzCa2izZIeFAB0CrxiTRYNSVYUdQmtokXmpCgBdgutokWmJaUkiwB3Cq2iRWZJlC4AeAqtokWW1Cq1AHkMvZpFZkuGUEsWAHoJraLFoLUNAnsKuyKNEiVZFAl8BsmexAN9CrsihVRLokQBfgmdqk2W1BIAAAAABP//AA==";
export { u8g2_font_minicute_tr };
export default u8g2_font_minicute_tr;
