/* u8g2 official font: u8g2_font_standardized3x5_tr (668 bytes, 94 glyphs)
 * Converted verbatim from u8g2_font_standardized3x5_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_standardized3x5_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_standardized3x5_tr', font)
 */
const u8g2_font_standardized3x5_tr = "XgACAgMDAQMEBQj//gX+BQAA1AG0AoAgBEA2IQVpKisiBtMzSQUjCi121VDVUBUAJAj7cXHnmQAlCGsyKaYyBSYHa3L1SgInBdErAigGam6qDCkHai4xJQUqBlszqQMrB9tyaSUALAXRKQItBUszAy4FSSoBLwdrsilWETAHazIjWSMxBmpuqwEyB2syOpUDMwdrMjrlBTQHazIxjVg1B2syI+oFNgdrcnOkETcHazIzxQo4CGsyIw01AjkIazIjjbgAOgVZKik7BeEpSTwF23JbPQXbMns+BtsyegE/CGsyOmWYAEAGa3LLFkEHa3LVUCpCCGsyKq20AEMGa3KzFkQHazIqWQtFB2syI6o4RghrMiOqGAFHB2tyM6kkSAhrMkkNpQJJB2syK1YDSgdrcjKqCksIazJJraQCTAZrMrE5TQhrMmkMpQJOB2syKrkCTwdrcpVVAVAIazIqrRgBUQdrcpWVBFIIazIqraQCUwdrcjsvAFQHazIrtgBVB2syyVUBVgdrMslaEVcIazJJjaECWAhrMkm1VABZCGsySZUVAFoHazIzlQNbBmouqxJcB2syOdYBXQZqLqoaXgXTcw1fBcsxA2AF0SsCYQdjcpVKAmIIazJRJbUAYwZjcjMLZAdrsmmpJGUGY3JjC2YHam5qJQBnCHNxSyW5AGgHazJRJStpBWkqaWoHem05VQprCGsyMa2kAmwFaSpDbQdjMmokFW4HYzIqWQFvB2NylaoAcAlzMSqpFSMAcQdzcUslWXIGY3KzBHMHY3IbLQB0B2tyacUKdQdjMslKAnYHYzJJrQh3B2MySY0keAdjMqmlAnkJczHJSjIlAHoGYzJTDnsHa3KqjgJ8BvkpRwB9CGsyMqekAAAAAAT//wA=";
export { u8g2_font_standardized3x5_tr };
export default u8g2_font_standardized3x5_tr;
