/* u8g2 official font: u8g2_font_pxplusibmcga_8u (807 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_pxplusibmcga_8u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_pxplusibmcga_8u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_pxplusibmcga_8u', font)
 */
const u8g2_font_pxplusibmcga_8u = "QAMDAwQEAQEFCAcA/wf/BwABewAAAwsgB4jh418AIQyIYUmJVLEcLocCIgqI4ahJZBI5PiMQiOGoSUQniegkkUnkMAAkDIhhSUtyuqgqhwIlDojhQ2QSkVSTRCYHASYOiGENJcIVlZHaRA4CJwmI4YilcnwEKAqI4UmV1dWBACkKiOHIlVXVwQAqDYjhg9RIhxBNJEcDKwuI4cPEQqNYjgwsCYjh410slQItCIjhY7PjDC4JiOHjXSyHAi8JiOHqcxwFADAQiOGUZBLRRMIiGYnqMAAxCohhScc62mEAMg6I4dBEYuFQKgvZYQAzDYjh0ERi4VykRgcCNA2I4Q1pEpHSVUoHATUMiGGYxHWxSI0OBDYMiGENpeKaSBsdCDcLiGGYlKXK6lAAOA2I4dBE2mgibXQgADkMiOHQRNrKUuEcCjoMiOHDxHIsYjkUADsMiOHDxHK4WCoHAzwJiOFJtWsHAj0KiOEj2RHtiAA+CYjhyLVqBwM/DIjh0ERiqTpcDgVAEIjhlGQSCUVCkVDkdCAAQQyIYUlpIk0m3WEAQg2IYdhEmmoiLXYYAEMNiGHRRBKxukhGhwFEDYhhFCUykb6I6kAARRCIYZxkIUmQKAnKIncQAEYPiGGcZCFJkCgJSulQAEcNiGHRRBKx0kitDgJIC4hhiPRk0ncYAEkKiOFQxbrSgQBKC4jhUcVKutGBAEsPiGGMdJERJTKRZCQHAUwMiGFQxdpCKncQAE0PiGHIJCsvkoiaRCYHAU4SiGHIJCMJRYUimsgkMjkIAE8RiGENJSKZRCaRiSTCORAAUAyIYdhEmmpiKR0KUQyI4dBE+jIjz2EAUg+IYdhEmmoSmUgykoMAUw2I4dBEMrmaSEYHAlQMiGGYIpKgWCsdCFUKiGGI9D/ZYQBWC4hhiPRvVDkUAFcSiGHIJDKJTCKJSC4rMjkIAFgRiGHIJDKRRDgdSkQyOQgAWQyIYYj0RhVL6UAAWg6IYVxkkphUKaRyBwFbCojhEMU604EAXAmIYcj1HgcBXQmI4ZD1SAcCXgyI4YWHEpFMjisAXwiI4eP3QwAAAAAE//8A";
export { u8g2_font_pxplusibmcga_8u };
export default u8g2_font_pxplusibmcga_8u;
