/* u8g2 official font: u8g2_font_mystery_quest_36_tn (658 bytes, 18 glyphs)
 * Converted verbatim from u8g2_font_mystery_quest_36_tn.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_mystery_quest_36_tn.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_mystery_quest_36_tn', font)
 */
const u8g2_font_mystery_quest_36_tn = "EgAEAwUFAwUGFCD//RzxHP4AAAAAAnYgBgAQrgAqH+2Vv0Y5OiUjEzIichJCUlFUKUo3IlQyJUQUNBoEKw8PtsonrZ8dHIhJ6zMALAzEtJkhcRAxIiEBLQltdMfwgTEALglkFJpwECEBLx9v77U8OzwsPCw8rFpYWrG0sLSwtLC08LDwsPBiADAqkfvZVksxODS2iGxocIRwhHCE8vT/dGJyZHKEcGZQaG5q2dTcgWgZADEbSxOuJbguQi5CLEQsREhGUv8vB+eqDiIEATI9kdfJVXogN0Q1NyRIIkMzIhIUMiISIREyIpIiZERGRGJGLGRIxZjJ+PT49Lj4uO4lgySDZCiGDmzIKAAzPa/3yX7wIOZg0HBCciJyJFImUDpaWDraUmRceqZKZERIQkqGZiKGJCIkhiQopCQmpmZIRHBkiuhgzgoANDPx1804zXGxhOyE7IToiOiIqIzkjOCQVMiQVASRkJXMwQckZjOSQ5FDkeN7XWx6ICcJNT+QE8bw5sCGTmYyZjJmMmYyZjJmepOjI5k6EUKhULkwISMZIRkRmZAYkRiRGJFEMSIxNDIxQzKCQ2JLCI8ANjSP98VJeTcUNiISNBKRaCaR1NCw8LCMkchByITQSNkE3cSkX05ITkiKDMrIDUmNyQwaATcljve9MHnwakJSQlIiNCRSJFIkMljtrLDsWtlNZ5eyLDyIGgU4OrH3zXVJIzcXNRkkKjIqIisiKzI5MjkjOCU2dyB3IEc1RDczOUE5MSsx6+nE6MjkyODQGFVF4RUAOTOvF8ZVeRA2JTQmMzcyKDEpMSkxafgwQmJMQmJqQoSCYuZELkp47fDsLO0oaaEprSQAOgyE9Z1wECEPekABAAAABP//AA==";
export { u8g2_font_mystery_quest_36_tn };
export default u8g2_font_mystery_quest_36_tn;
