/* u8g2 official font: u8g2_font_pxplustandynewtv_8u (846 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_pxplustandynewtv_8u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_pxplustandynewtv_8u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_pxplustandynewtv_8u', font)
 */
const u8g2_font_pxplustandynewtv_8u = "QAMDAwQEAQEFCAcA/wf/BwABhAAAAzIgB4jh418AIQyI4UmJVLEcLgcCIgqI4Yi0heL4ACMQiOGoSUQniegkkUnkMAAkDIjhSUtyuqgqBwIlDojhQ2QSkVSTRCYHASYOiGENJcIVlZHaRA4CJwmI4YmlcnwCKAqIYUqV1dVhACkKiGHJlVXVoQAqDYjhg9RIhxBNJEcDKwuI4QPFQqNYjgosCYjh44tYKgQtCIjhY7TjCi4JiOHji1gOBC8JiOHqcxwFADARiGENJSKZRBJRE0mEcyAAMQqI4UnHOtpBADIOiOGUZGLhUCqS3EEAMw6I4ZRkYhldIhPVYQA0DYjhDWkSkdJVSgcBNQ2IYVzEYrtEJqrDADYOiGENpWKTTCIT1WEANwuIYVxkUs3qUAA4EIjhlGQSmagkk8hEdRgAOQ6I4ZRkEpnILJXRgQA6DIjhA8VyLGI5EAA7DIjhA8VyLGKpEAA8CIjh6q4dBD0KiOGj2RHtaAA+CYhhybVqhwI/DIjhlGRSZTlcDgRAEIjhlGQSCUVCkVDkdCAAQRGIYQ0lIpnkIpPIJDI5CABCDYhh2ESaaiItdhgAQw2IYdFEErG6SEaHAUQNiGEUJTKRvojqQABFEIhhnGQhSZAoCcoidxAARg+IYZxkIUmQKAlK6VAARw6IYdFEErHSSG0SBwFIEYhhyCQyiUxykUlkEpkcBEkKiGFRxbrSYQBKC4jhUcVKutGBAEsPiGGMdJERJTKRZCQHAUwMiGFQxdpCKncQAE0PiGHIJCsvkoiaRCYHAU4SiGHIJCMJRYUimsgkMjkIAE8RiOGUZBKZRCaRSWSiOgwAUAyIYdhEmmpiKR0KURGI4ZRkEplEJpFJRKPyBABSD4hh2ESaiBKZSDKSgwBTDYhh0UQyuZpIRocBVAyI4ZgikqBYKx0GVRGIYcgkMolMIpPIJDJRHQZWEYhhyCQyiUwik8hEEuEcCFcSiGHIJDKJTCKJqEQkJ4kcBlgRiGHIJDKRRDiUiGQSmRwEWQyI4Yj0RhVL6TAAWg6IYVxkkphUKaRyBwFbCohhEcU602EAXAmIYcj1HgcBXQmIYZH1SIcBXgyI4YWHEpFMjisAXwiI4eP3QwAAAAAE//8A";
export { u8g2_font_pxplustandynewtv_8u };
export default u8g2_font_pxplustandynewtv_8u;
