/* u8g2 official font: u8g2_font_tinytim_tr (797 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_tinytim_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tinytim_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tinytim_tr', font)
 */
const u8g2_font_tinytim_tr = "XwACAgMDAgMFCAf//wX/Bf8BAQIOAwEgBYCsACEG6ZysACIGk6ckFSMLrrymOFQ5ZIoAJAq1s+el0Rg5AiUIrbTIlaspJgmttOYUV1QqJwWRlwgoB7KbqWYAKQiym8RUKQAqBpumpA4rB5ulpZUALAaSmykALQWLpgwuBYmUBC8Hq6RWZQQwCKysqWgmBTEGqpytBjIJrbStHGUeAjMJrKxslDQaCTQJbaxnmdLQCTUKrbQcGaqcFgA2Ca20yjhUTgs3CKysjBzrCDgJrbStnFZOCzkKrbStnEZGaQE6BqGUxAA7B6qbZagAPAmttCuZoYYCPQicrYyMRgA+Ca20aKhhVBo/CKysqVjjCEAMv8PuKipVyZmpIUEJrbStPEbWAUIKrbSMlIfKQwFDCa20raxRTgtECa20jJTtoQBFCKysDL3yCEYIrKwMvXIGRwqttA2N0shpBEgIrKxEOaYMSQbpnAwBSgerpMlyAUsJrKxElWQqA0wHrKzk9ghNCa20qJVU0jpOCKysxKWmDE8IrbStbKcFUAuttIyUh8ooIwBRCbWzrWyqDQNSCa20jJSHyjpTCa20DQ03HApUC620DJlRRhlFAFUIrbRkd1oAVgqttGSdypQjAFcJrbRkK6kuAFgJrbTkVFd1AFkKrbTkVGeUUQRaCK20DN0eAlsHspuslgBcB6ukxFwGXQeym6jWAF4Io6bFlFQAXwaMrIwAYAaSn8QAYQiltM2h0whiCq20ZJRMPRQAYwikrI2cRwBkCa20o2TuNAJlCKW0jSPDEWYIs6SmtGIFZwmtsw0tlUoLaAisrOQVzQBpBrGUpBFqCHqT5VQpAGsJrKzklGQqA2wGqZQMAW0JpbSolkqqAG4HpKysaAZvCKSsqSiTAnAKrbOMlKdSGQFxCa2zDS2VyihyCKOkpBUjAHMIpbQuDccCdAirpKUVowB1B6SsRDMNdgikrESZpAJ3CaW0ZJVUFwB4CKSsxCRVDHkJrKtEmXSMAHoIpKyMWI4Aewizo6lkRgF8BbGTHH0Js6PIqFRSAH4Glba5AAAAAAT//wA=";
export { u8g2_font_tinytim_tr };
export default u8g2_font_tinytim_tr;
