/* u8g2 official font: u8g2_font_originalsans_tr (988 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_originalsans_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_originalsans_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_originalsans_tr', font)
 */
const u8g2_font_originalsans_tr = "XwACAgQEAQQFDAv//gj+CP4BQgKlA8AgBQCxAiEGgVFyBSIHM5uSrAAjDoXRVqY0VJnSUGVKACQMldGaV6XyTqraESUPhvGyUxwpo4wySiOmPCYOhvGWUZ0yyqiOSccVJwUxWzIoCKONmsreBSkJo42Sy14lACoGM5uSOisKVdOaURwyowgsBTFNMi0FE5cyLgURURIvCoSxXuaYY84AMAyF0bayXEmlqdMCMQiDkZZkrwEyCYSxpmIu2yMzDISxpmJOGmWZFAA0DYXRnmUq09AZZZQANQuEsTJ03ijLpAA2CoXR3kYr22kBNw2F0TI0yhnljHJGGTgLhLGmokwqmkkBOQuF0baynTbKNQA6B2FRklEAOweBTZLRADwKdLEe2yijjAI9CDXVMjQcAj4LdLGSUUYZxTYAPwuEsaZijnWmIgBAFqlNPzLKKMYlK5WTyklFJZXMOI4FQQ+HEZ9xhimjuhwqQw0DQguEsbKiHCmaIwFDDYXRtrJGGWWUUU4LRAmEsbKiz5EARQqEsTJ0XrkeAUYJhLEydF65DUcMhdG2skYZxa3TAkgJhLESzTGdAUkIg5GyYq8BSgiEsd5nkgBLDIXRkmUqtU6xygFMD4XRklFGGWWUUUYZDQFND4cRk+FelYwaaqihhgFOEYgxk/GGKiOZddQoabhxAE8JhLGmos+kAFAOhdEyUtZDZZRRRhkBUQqUr6aiz6RRAFIMhdEyUtZD6RSrHFMMhdG2soYaZqjTAlQPhdEyZEYZZZRRRhlFAFUIhdGS/U4LVhCHEZOhhinHXGVUw4wzAFcSi5GTU9Ypp1zmVht1w5xxDVgMhdGSdaozyqnWAVkOhdGSdaozyiijjCIAWgyF0TI0yjXKNRoCWweibbL6JVwJk48S61jHAl0Hom2i+jVeBiOd1gBfBRbvcmAGIn0SA2EKZLGmYhpRpgFiCoSxkvOKzpEAYwlksaaiLpMCZAmEsV6N6EwDZQpksabi2DEpAGYIg5E2R+wEZwqErTaimbZMCmgJhLGS84qeAWkHgVGSxgBqCKJMllMvBWsNhdGSUUYxlTrFKgdsBoFRcghtDGcRs1SMMsoooyxuCGSxsqJnAG8JZLGmojMpAHAKhK2yonOknAFxCYStNqIz7QJyCGORklZsAnMKZLE2MtJIJgV0CYOREuOIrQV1CGSxEj3TAHYLZdGSdSpTzigCdw1pUZOzrjpTu0Y5AngLZdGSU51RTnUAeQ2FzZJ1KlPOKGeUAXoJZLEycmyPAHsJo42aYpVjO3wGoU3yCH0Ko42SY51iKwJ+ByS3llQCAAAABP//AA==";
export { u8g2_font_originalsans_tr };
export default u8g2_font_originalsans_tr;
