/* u8g2 official font: u8g2_font_timR08_tr (994 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_timR08_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_timR08_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_timR08_tr', font)
 */
const u8g2_font_timR08_tr = "XwACAgQEAgQFCwv//Qf+B/4BMQKlA8YgBQCmBCEHceNkqAAiByM2JakAIw11Yq1MaahqqDIlACQMlF41jqiRRnLkBCUPdyJujBRTOyWZytROACYPeCJWw5ShmitGnVVaCicFIbZEKAqTGjXFFOuYAykLkxolxxyrmCIAKgYzcyV1KwpVojWjOGRGESwGIt5EBS0FEyplLgUR4yQvCXPitIpVjAAwCXRiTUXPpAAxCHNjLcmuATIKdGJNxRxzjCMzC3RiTcWcNMojATQMdWI9y1SmoTNKADUKdGJtxY1yHgk2CnRiVcUVzaQANwl0YmXIOuYSOAt0Yk1FmVSUSQE5CnRiTUUzzSQBOgZR4yQHOwdi3ixjFTwHU2M11QU9CDWmZWg4BD4IU2IlVyUAPwpzImWkmGKGCUASmFp25IzKpWJSMalktsmhAEENdyI+w41qVA+Z0wFCDHWiZcQqplnFoQBDDnbibYysYYYZ6jQSAEQOduJlyKhyyimnOEYCRQx1omWomDKaGcUxRgx1omWomDKaGeUJRw524m2MrGEcGe00EgBIDXciZq0ccxwyx5wOSQhzImXFrgFKCXQibeZWJQFLDXbiZalYZY3qmJYATAx1omVnlFFGGcUxTQ95omYvLVMzNdOKrZUGTg53ImYtWZWpjDKqmQBPDnbibSS5kUYaTTUSAFAMdaJlxCqmmVGeAFEPltptJLmRRhpNtaGGAlIMduJl5NjcKce0BFMKdGJtxK2RHAlUDHWi5SozyiijvABVDnciZq0cc8wxR6UnAFYOdyJmrRyVThnVMOMMVxF7oWZduZRRp5VRN8wZ1wBYDXciZq1cZZhhytUBWQ53ImatXGW0YcYZTgBaCHWi5e49BlsHktpk9SVcCXPiJOZYxwBdB5LaRPU1Xgczc61SAV8GFVZlCGAGIvokBmEHUyJFpyNiDHVhRaOMZhVTTAtjB1MibdYCZAx1YlWjuGKKKUYVZQdTIu3KAmYJdCJVxZnLBWcLdFptpGZWcSQAaAt2YUXDDHfsqQRpB3LiLKoOagmT2TQj2bkAawt2YUXDDFt5x1JsB3MiRfYabQtYImbJVqxi5QBuCVViZVYxxWRvCVRiTUUzKQBwDYVVZcQqpphmRnkCcQ2FVm3FFFOMG2WUB3IJUyIlJRXTAHMHUyJt5xF0CWQiLc5cIwF1ClViRc0UU4wqdgtWYWWpmFPWMAJ3DVkhZlmxTjWyYcoAeAlVokWpukoGeQ52WUWtWGWkUUZaIwB6CFRiZcTmEHsJkxo1xSrHOnwGkZrkAX0KkxolxzrFKgJ+BybqTVoAAAAABP//AA==";
export { u8g2_font_timR08_tr };
export default u8g2_font_timR08_tr;
