/* u8g2 official font: u8g2_font_profont11_tr (966 bytes, 96 glyphs)
 * Converted verbatim from u8g2_font_profont11_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_profont11_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_profont11_tr', font)
 */
const u8g2_font_profont11_tr = "YAADAgMEAwQEBgsA/gf+CP8BPgKBA6ogBQCiAyEHOaNjUAIiB5u2I7EEIwstqqcyKJVBqQAkDk2eK1sqSrYlSmWLACUOPaJnUBJTEilKIiUAJgw9okeq1CqJFCkBJwUZt2MoCMueKyl1KykJy54jK3UpASoKLaqrUlmaIgArCi2mK4wGKYwALAiimmNIFAAtBYuuYy4GEqNjCC8MVZqzFmZhFmZhCDAMPaJnyaQlmbRkATEJPaIrGjsNAjIKPaJnycKsbRAzCz2iZ8nCSNWSBTQMPaIvk5JSMmjZADULPaLjOKShliwANgw9omcJhySzJQsANwo9omMQa8USADgMPaJnybRkybRkATkMPaJnyWzJECYLADoIKqNjiIYAOwm6mmOIhkQBPAe8oi9qbD0IHapjUAcBPgi8oiNsagM/Cz2iZ8nCrA5FAEANPaJnyZQhSZQhHQJBDD2iK0uipDYMmRZCDT2iY0gybVAybVAAQwo9omfJxLZkAUQKPaJjSDJvgwJFCz2i4xgOSRgOAkYKPaLjGA5JWARHCz2iZ8nEaNOSBUgKPaIjsw1DZgtJCj2iY5DCToMASgk9orNR05IFSww9oiOTkpKWRJUsTAg9oiPscRBNDD2iI1uWREk0WwBOCz2iI5uURNpsAU8KPaJnybwlCwBQDD2iY0gybVDCIgBRCkWeZ8m8VNYAUgw9omNIMm1QMlsAUws9omfJ1FVLFgBUCT2iY5DCngBVCT2iI/MtWQBWDD2iI7MlpSQLIwBXCj2iI3NJlOQWWAs9oiPTklqlpgVZCj2iI7MltbAEWgo9omMQs46DAFsISp9j6YsAXAzVmiNMwzRMwzQMXQjKnkPpywBeCB2yK0tqAV8GDprjAGAGkrojCmEJLaJn0EyKEmIMPaIjDIcksw0KAGMJLaJnycR0CGQKPaKzMmi2ZAhlCi2iZ8mGIR0CZgm8okuJpqwJZww9mmfQbMkQJgsAaAo9oiMMhyRzC2kIu6InlFoGaglLmiuUOi0Aaws9oiMsJaWpkgVsB7uiQ+plbQwtomNIKkqiJEoBbgktoiMxabYAbwktomfJbMkCcAw9mmNIMtughCEAcQo9mmfQbMkQFnIJLaIjMYlFAHMJLaJnUA8KAHQJvKIni6asKHUJLaIjc1KUAHYLLaIj05JSkkUAdwwtoiNJlERJlC4AeAotoiNLapVaAHkLPZojc0uGMFkAegktomPQ2gYBewrbmiuJWrKoLXwGSZ/jAX0L25oji9qSqCUCfgYVrscFfwUAogMAAAAE//8A";
export { u8g2_font_profont11_tr };
export default u8g2_font_profont11_tr;
