/* u8g2 official font: u8g2_font_torussansbold8_8u (767 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_torussansbold8_8u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_torussansbold8_8u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_torussansbold8_8u', font)
 */
const u8g2_font_torussansbold8_8u = "QAMEAwQEAQEFCAcA/wf/BwABewAAAuMgB4jhxxEAIQmI4RHTuSwAIguI4RDRJiQeMQAjEYhhkRA5kZCRkJEQOZGQBCQMiOGRKpGjE6mSBSUNiOGQCVGlE5EYSQAmEojhGZKQkRCSipCIEJGZEAQnCYjhEROLRw4oCohhklKmTikAKQqIYZFTpkoxACoOiGGKikg0FJEqHhgAKwuIYY6LqoqLBwIsCYjhRyUmFgwtCIjhB7VHAy4IiOFHLSYLLwqIYQuT0lk4ADAKiGGhEdG/IQUxCojhkRrTkSUAMg2IYaGJERMakhKzBDMOiGGhiRETmhOJkSEFNA+I4RmKkJGQkZCxkqIENQ2I4TARqxMTiZEhBTYOiGGhkQkRqxHRhhQANwqI4TCTUqYtADgNiGGhEdGGRkQbUgA5DohhoRHRpkwkRoYUADoKiOEVExeTBwI7CojhFRMXEwsGPAiI4dKdlgA9CYjhBzG1BwU+CYhhkdNKYwA/DIhhoYkRE5oSlwVAE4hhoQmKCFEREiEREiFCEkgCQQuIYaER0cREXwJCDYjhqBHRpEZEk1IAQw2IYaGRCRHTJoYUAEQKiOGoEdE/KQVFDIjhMBETIxITswRGC4jhMBETIxJTDUcOiGGhkQkRkxjRDSkASAqI4RDRExN9CUkKiGGhEtMVKQBKC4jhEtNJjAwpAEsOiOEQ0YUMkYSMiJYATAmI4RDTM0sATQ6IYYiisahYEjI1JQhOE4hhEIqYiSCJiJhIQhEzESQJTwqIYaER0b8hBVAMiOGoEdGTGjFpAFELiGGhEdG/oZMAUgyI4agR0aRGRC8BUw6IYaGRCZGjE4mRIQVUCYjhMBLTWwBVCojhENH/hhQAVgqI4RDRfxJDC1cTiGGQiFARoSJCRYSKCBVJagFYC4jhENEbGhG9BFkLiOEQ0RsqMbUAWgqI4TCT0pklAFsKiGEhEtMZKQBcCYjhiNO7SABdCYhhIdMjUgBeDIhhChuSkEmPBgBfCIjhx/YgAAAAAAT//wA=";
export { u8g2_font_torussansbold8_8u };
export default u8g2_font_torussansbold8_8u;
