/* u8g2 official font: u8g2_font_tiny_gk_tr (649 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_tiny_gk_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tiny_gk_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tiny_gk_tr', font)
 */
const u8g2_font_tiny_gk_tr = "XwACAgMDAQMEBQYA/gT+BAAAzwGoAm0gBEAuIQVhKioiBlMzSQUjCWV61YgjVQAkB2NyI44EJQZkNrEHJghkNjOpmAInBVErAigGYm4qBikHYi4xKQAqBtsyqQMrB1tyaSUALAXSbQotBcsyAy4FSSoBLwZk9rENMAdjcpWqADEGYzKyGjIGYi5RCTMHYzIrLwA0CGQ2qTViAjUHYzJDLwA2B2MyI64ENwdiLkolADgGYzKrCzkHY3JpLgA6BWEqMTsH6m0ZKgA8BVtyWz0FWzJ7PgZbMnoBPwdiLkkmAEAHZHYqqjhBB2Ny1VABQgdjMkOlBUMHYzIjxgFEB2MyKqkFRQdjMkPFAUYHYzIjqghHB2NyMyUBSAdjMmkoFUkHYzIrpgFKB2NyUlUASwdjMmklFUwGYzKxHE0IZTp5raQDTgdkNnGpGU8IZHYqyqQAUAdjMiqtCFEHZHYqKjVSB2MyKq0CUwZiblIBVAdjMitWAFUHZDbRTApWB2MySZUJVwdlOtnqAlgHYzKppQJZB2MyqawAWgZiLsoAWwZiLisJXAlkNhlllFEAXQZiLioNXgVTcw1fBUsyA2AFUi8xYQZbcisJYgdjMlGlBWMFWm4yZAdjsmklAWUGW3IjCmYHW3IjJgBnB2txK8kFaAdjMjGqAmkFWSopagdybTklBWsGWzJpFWwFWSoDbQddOhmpDm4HWzIqqQBvBltyXQBwCGsxKq0YAXEHa3EryQJyBlouKwFzBlouSgF0BltySQd1B1sySSUBdgddOjnVEXcHXTpZdQF4BlsyqQN5CGsxSSW5AHoGWzIyCnsHY3IjSQF8BWEqI30HYzJSjQR+B9R2SSUAAAAABP//AA==";
export { u8g2_font_tiny_gk_tr };
export default u8g2_font_tiny_gk_tr;
