/* u8g2 official font: u8g2_font_chikita_tr (826 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_chikita_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_chikita_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_chikita_tr', font)
 */
const u8g2_font_chikita_tr = "XwACAgMDAgQFBwgA/gX+Bv8BDwIoAx4gBYAoASEGuScZKiIGk0xJKiMKrWirhqqGqgAkC71nzUPlnYaOACUIrWiRK1dTJgqtaM0pKhlVACcFkSwRKAe7R01lXSkIu0fJZVUCKgbbWUkdKwqtaM0oDplRBCwGkjdTAC0GjWoZAi4FiSgJLwfrWK3KCDAIrFhT0UwKMQaqOFsNMgmtaFs5yjwEMwqtaBkZpg2HAjQKrWiVqUxDJwA1Cq1oudHIcCgANgqtaBsajZTTAjcJrWgZGuU2ADgKrWhbOa2cFgA5Cq1oWzmNjIYCOgaZKUkBOwahKEkCPAmtaFcyQw0FPQidaRkaDgE+Cq1o0VDDqDQAPwq9Z1u5jTIdAUAOv4cbKkNLVWpsaigAQQmtaFtZj5EDQgqtaBkpD5WHAkMKrWhbWaOcFgBECa1oGSnbQwFFCq1oudFIGQ0BRgqtaLnRSBllBEcKrWhbGaWR0wJICa1oyXqMrANJB6tIWbEaSgqtaEcZZaTTAksJrWjJMs0qB0wLrWjJKKOMMhoCTQmtaMlrJa0DTgmtaMlTJbkDTwitaFvZTgtQCq1oGSnroTICUQitaFvZVCNSCq1oGSnroXIAUwqtaBsabjgUAFQLrWgZMqOMMooAVQitaMnutABWCa1oyXaqIwBXCq1oySqppLoAWAmtaMmpruoAWQqtaMk61RlFAFoIrWgZuj0EWweyN1ktAVwHq0iJuQxdB7I3Ua0BXgWTTGtfBo1nGQJgBpI8iQFhCKRYG1EOAWIJrFjJK8qRAGMIpFgbOaMBZAisWE8jyjRlCKRYU3HEAWYJrFhVcaQcAWcKtFYbUQ49EgBoCKxYySuaAWkGqShJA2oIujbLqVIAawmsWMlRpRUDbAapKBkCbQqmeEmVSjLJFG4IpFhJyZQBbwikWFNRJgVwCrRWWVGOlDMAcQi0VhtRpl1yCKRYSSPmDHMIpFgbGg0FdAmsWIsj5YwEdQekWIlmGnYIpWjJOtURdwilaMlWFwB4CKRYiUmqGHkJtFaJZtojAXoIpFgZsRwBewizR1NljgJ8BbEnOX0Js0eROaakAH4InWnLqU4AAAAABP//AA==";
export { u8g2_font_chikita_tr };
export default u8g2_font_chikita_tr;
