/* u8g2 official font: u8g2_font_tiny5_tr (717 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_tiny5_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tiny5_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tiny5_tr', font)
 */
const u8g2_font_tiny5_tr = "XwACAgMDAQQEBQcA/wX/BQAA2wHXArEgBEBUIQZpVFYAIgbTZZIKIwpt9KqhqqEqACQI8+PiyDMBJQZkbGIPJgls7GKKVUwBJwXRVQQoBmrcVBkpB2pcYkoKKgbj5NJqKwfb5NJKACwF0VMELQVLZQYuBUlUAi8HatySqgAwB2vkKqsCMQZq5FYDMgdrZHQqBzMHa2R0ygs0B2tk0xEDNQdrZEbUCzYHa+SmagE3CGtkZooVADgGa+T6BTkHa+RacgE6BmFUYgA7BulTogA8BmtkU109Bttk9gA+B2tkclUCPwhrZHTKMAFACWzsVFQbKQBBCGzsVBxTBkIJbGxWHCmOBEMJbOxU1DEpAEQIbGxWNEcCRQhsbIZeeQRGCGxshl45A0cIbOxGTjMNSAhsbKIcUwZJBmlUhgBKB2tkS1UBSwlsbKJKMpUBTAdsbHJ7BE0JbXTyWknrAE4IbGziUlMGTwhs7FQ0kwJQCWxsVhwpZwBRCfTrVDSTRgFSCWxsVhwpygBTCWzsRkYajQRUB2tkVmwBVQhsbKIzKQBWCm10cipTzigCVwptdFJSSXWmBFgIbXRyqqs6WQptdHKqM8ooAloIbGxGbI8AWwZqXFYlXAdqXFJMBV0GalxUNV4F0+UaXwVLZAZgBlJeYgBhB2PklkoCYghrZKJKagFjBmPkZhZkB2tk01JJZQdj5NLIAmYHatzUSgBnCOvjlkojAWgIa2SiSlYAaQZxVNIIagj623KqFABrCGtkYlpJBWwGaVSGAG0JZXRGqlRSBW4HY2RUsgJvB2PkKlUBcAjrY1RSKwJxB+vjlkoycgZiXFYFcwdj5EZeAHQHalzSigF1B2NkkpUEdghjZJIqEwB3CWV0UlKdKQF4B2NkUksFeQfrY5LVBHoGY2RWOXsHa+RUHQV8BmlUhgB9CGtkZE5JAX4H1OySSgAAAAAE//8A";
export { u8g2_font_tiny5_tr };
export default u8g2_font_tiny5_tr;
