/* u8g2 official font: u8g2_font_open_iconic_check_8x_t (830 bytes, 5 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_check_8x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_check_8x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_check_8x_t', font)
 */
const u8g2_font_open_iconic_check_8x_t = "BQAGBgcHAQUIQEAAAEAAQAAAaQAAAyJAaT5ZCzwH+IFewA92gl7IDfjhRtiJWkEt58W85gSuizOoLk5hujiH6OIknouzaC5OY7k4j+TiRI6LMykuTmW4OJfgArWkFZWyTlhJG3Eh7wN2xA2ZMS9oRZ2wEfcBN+QFnbAPeEEflABBmEBgCKwxYIqKKT0hyCNtJkxVsSZXBHtkjqyhLTZFJSgSFaE4VIbCSCEJA6UgCtSSIE6LYjgtDMG0NITS4hBIyyMgLSTBsZAIxkIyFAsJQSwkxbCUFsJyWgRLylpRLekFcQKKwxEqTEewKB7hgnyGi/EhMASowAggQ+/AJTbFttAamSN7YJFrYlUqzLSRPFDoKTEqBWZoAEK5QGAIrDFgioopPSHII20mTFWxJlcEe2SOrKEtNsUhWARH4iAohONwGBLDYTQQCNIwGIpDYRSNhbE0CMeiWBwDZEEsECGyGJaIIFkIi0SYLIJlElSsFdWSXlDMmTE0ZubEoJfUolZWJZgsgmUiSBbCIhEii2GJCJAFsUAGx6JYHERjYSyNgqE4FIbRQCBIw3AYEsNxOAgK4UgcgkVwKLaF1sgc2QOLXBOrUmGmjeSBQk+JUSkwQwMAQ74/XAwMsKYVIzBUDKFIMQYCxSCGE6MQTAwjKDEW9HI+AoT5EBDlY0CQDwIxPgqE+DAQ4eNAgA8E8QicR4JwCMxDQTQG5bEgGATyYBCLwng0CIVBPBxE4hAeDyLxQAiFEyEWjYRgMBOisTCBA+FQGMGBeCTM4EBAEIZwICIHUzgQEoMxHIhJwRwOBIVgEAeiMjSIA2ERHMSBuAQP4kCgiAOBIg4EijgQKOJAoIgDgSIOBIo4ECjiQKCIA/87AESoPl8JvATOADUoB1JhLECH8OAkvgSz6BZKY2sgj+xhRK4IMakmQmViRZbg8lyES3MhLsvFuCQX5HJclEtxYS7DxbkEF6glraiUdcJK2ogLeR+wI27IjHkxM+RG7IAfL8SNtBJ2slLUSmpBl+DiXIYLcykuyuW4IJfkYlyWC3FpLsLlcUWWoDJVhEk1ISJXxHhkD6SxNZRFt2ASX8I5hAeoMBakQTlIAAAAAAT//wA=";
export { u8g2_font_open_iconic_check_8x_t };
export default u8g2_font_open_iconic_check_8x_t;
