/* u8g2 official font: u8g2_font_tom_thumb_4x6_tr (710 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_tom_thumb_4x6_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tom_thumb_4x6_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tom_thumb_4x6_tr', font)
 */
const u8g2_font_tom_thumb_4x6_tr = "XwACAgIDAwQEAwYA/wX/BQAA4wHNAqogBeDNACEGtcisACIGi8skFSMIl8ikoYYKJAiXyI04YgIlCJfIZNRGASYIl8goNVISJwWpywgoBrbIqTIpCJbIxJQUACoGj8qkDisHj8mllQAsBorIKQAtBYfKDC4FpcgELweXyFZlBDAHl8gtawExBpbIrQYyB5fI6FQOMwiXyOiUFwA0CJfIJDViATUIl8iMqBcANgiXyM2RRgA3CJfIzFRGADgIl8iMNNQIOQiXyIw04gI6Bq3JpAA7BpLIZQU8B5fIproAPQaPyewBPgeXyOSqBD8Il8jMlGECQAeXyFVDC0EIl8hVQ6kAQgiXyKi00gJDBpfIzVpECJfIqGQtAEUIl8iMOOIARgiXyIw4YgRHCJfIzZGSAEgIl8gkNZQKSQeXyKxYDUoHl8iWqgJLCJfIJLWSCkwHl8jE5gBNCJfIpDGUCk4Il8ikcagATweXyFVWBVAIl8iotGIEUQiXyFVqJAFSCJfIqDRWAVMHl8jtvABUB5fIrNgCVQeXyCRXElYIl8gkq0wAVwiXyCQ1hgpYCJfIJNVSAVkIl8gkVVYAWgeXyMxUDlsHl8iMWA5cBo/J5AJdB5fIzHIEXgWLyzVfBYfIDGAGisvEAGEHk8jINQJiCJfIRJXUAmMGk8jNLGQIl8impZIAZQaTyJ0CZgiXyKa0YgJnCJfHHTElAGgIl8hElawAaQa1yKQBagibx2YYVQVrCJfIxLRUAWwHl8jI1gBtB5PIPFIAbgeTyKhkBW8Hk8hVqgJwCJfHqKRWBHEIl8ctlWQAcgaTyM0ScwiTyI04EgB0CJfIpRWjAHUHk8gkKwl2CJPIJDVSAncHk8ikcQR4B5PIpDIVeQmXxySVZEoAegeTyKyRBnsHl8ipOgp8BrXIKAF9CJfIyJySAn4Gi8uNBAAAAAT//wA=";
export { u8g2_font_tom_thumb_4x6_tr };
export default u8g2_font_tom_thumb_4x6_tr;
