/* u8g2 official font: u8g2_font_threepix_tr (653 bytes, 94 glyphs)
 * Converted verbatim from u8g2_font_threepix_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_threepix_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_threepix_tr', font)
 */
const u8g2_font_threepix_tr = "XgACAgMDAQMEBQcA/gT+Bf8AyQGiAnEgBEA2IQVhKioiBlMzSQUjCu151VDVUBUAJAhkdmoMpQAlBmQ2sQcnBVErAigG8m2qGSkH8i0xVQoqBttyXQArB1tyaSUALAXRKQItBcouAi4FSSoBLwjzsVVMMQIwB2MyI6kRMQZibqsAMgZjMnMNMwdjMjMNATQGY3JHDDUHYzIjDwE2B2MyI44BNwdjMjPFBDgHYzIjjRE5BmMy5wg6BVkqKTsF4SlJPAbrsakuPQVaLlI+B+sxuSoBPwdjMkujBEAHWzJqKABBB2MyIw0VQgdjMkqlEUMHYzIjxgFEB2MyKqkRRQdjMiOqAUYHYzIjqghHB2MyI6YRSAdjMkkNFUkHYzIrpgFKBmJu1QBLB2MyaSUVTAZjMrEcTQhlOnmtpANOB2Q2cakZTwhkdirKpABQB2MyIw0JUQnsdSrKpFEAUgdjMiOtAlMHYzIjoxFUB2MyK1YAVQdjMskaAVYHYzLJqgBXB2U62eoCWAZjMkl1WQdjMkmVCVoGYzJTDlsG8i2rJVwI8zExxxwDXQbyLao1XgVTcw1fBUsyA2AFUSsCYQdcNqsaAWIHYzJxpBFjBlsyIw5kB2OyQ40AZQZbMkMNZgdjciqtBGcIazEjjTgCaAdjMnEkFWkFYSpJagbqbTkNawdrMrFaBWwFYSojbQddOldSBW4HWzIjqQBvB1syI40AcAhrMSMNGQFxB2sxI41YcgZaLisBcwdbciopAHQHY3JpRQF1B1sySY0AdgdbMklVAHcHXTpZdQF4BlsyqQN5CGsxSY24AHoG4zFTDnsI83EqphwFfAVpKkN9CPMxsk5JAX4JZTpqjLQjAAAAAAT//wA=";
export { u8g2_font_threepix_tr };
export default u8g2_font_threepix_tr;
