/* u8g2 official font: u8g2_font_streamline_photography_t (721 bytes, 11 glyphs)
 * Converted verbatim from u8g2_font_streamline_photography_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_photography_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_photography_t', font)
 */
const u8g2_font_streamline_photography_t = "CwADAgUFAwMGFRUAABUAFQAAAAAAArUwMvTxdbdhiLMkz4ZBnJIczBJJhyZ9yIfjcI2kVE2UqpoMSapGUiqHsT7kSU7Khg8RADFMs5Y1lBxMlDqYJEoOJkodTBIlBxMlGg5SolOUnJJIw0FS6mCSKDmYKOUkShIlBxOlmiUVJZ4SpQ4miTQcJCWnJDpFiYaDlCg5mAgyP7GaNb7mmJhjW44NUTRMg1JHhiFJdExJdCRRcjBRMjlRooqUKMUoScyRogwPiZKDiZKDiTQcJJ2iU3TK8AMzM4++dbRNSmpJqRrVwSgHoxyMcjDKwSyHUjsy6GiO58iWLckULZfkoCiJcmnZpmiHcgA0QzXSdXSKEg2fdGqSDF+iJIeTKInKSpS0SUkpibIoaUriTCklWWlIoiRKsimJkiwakiVK0ixZomT4UqdKw6dEpygANUC1kvWRQcdVHdMhPYfTfAjLg5jFgxylg56kgw6Jw6CLw1kdBllHhjyJhzyKdyQLdyQMdSjN4VyHdEzV8UFHADYyNdK1hg9aTktyqk7VqTqc6lBW0bE0EtdR0qRBWvLhsmODpqN2TNcRHUpSHcuGDxIAN0iUsnWGD1lOKg1PiZKjSaLkiJQkSj4kFSUfkoqSmZJEicpJohSzJTEnUZIoOZIliZJDlUQanhKdlOikRCclyfAhyqnR8EEBOEO1kvWRQcdVHdNSPZzTOMzCnJJFxThK1qmSpYOqI4OsD2IkJ+OiZnGUZKU4qkVLlmlhGmY5mCY5mOuQjqk6PugIADlAtZL1kUHHVR3TIb1aC7MoLGf1HKoPcZJpQ6TJw64nQywnOqQmtTTJkjyLKmmcKXEaJjmc6miuQzqm6vigIwA6Q7WS9ZFBx1Ud0yE9h9OcEsZzFmdxlK1bkuVgpoVTkmmZlGVatmSZlg1aJQrHqB2Msmg4SGFOSXM41yEdU3V80BEAAAAABP//AA==";
export { u8g2_font_streamline_photography_t };
export default u8g2_font_streamline_photography_t;
