/* u8g2 official font: u8g2_font_tinypixie2_tr (691 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_tinypixie2_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_tinypixie2_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_tinypixie2_tr', font)
 */
const u8g2_font_tinypixie2_tr = "XwACAgMDAQMEBgcA/wX/BQAA4wHKApcgBEAuIQVpKisiBtMzSQUjCm161VDVUBUAJAnzcWnIoRIAJQhtOnLlagomCW5+OmZprgAnBdErAigGam6qDCkHai4xJQUqCeW6caiZEgArB9tyaSUALAXRKQItBUszAy4FSSoBLwdrslUZATAHa3KVVQExB2tySVYDMgdrMjqVAzMHazIz5QU0B2syMY1YNQdrMiPqBTYHa3JzpCQ3CGsyM8UUATgIazIjDTUCOQhrMiqNuAA6BVkqKTsF4SlJPAZrsqkuPQXbMns+B2syuSoBPwhrMjplmABAC3Z+I2XkGhqPBEEIazIqqaECQghrMiqttABDCGtylUwVAEQHazIqWQtFBmouawlGB2ouayUARwdrcjOpJEgIazJJDaUCSQdrMitWA0oH8i2qpQBLCGsySa2kAkwGai6pJU0JbTp5raR1AE4IbDZRLjUDTwdrMiNZI1AIazIqqRUBUQjzcZWVZABSB2syKqlVUwZqLksNVAdrMiu2AFUHazLJNQJWCGsyySoTAFcKbTopqaQ6UwJYCGsySbVUAFkIazJJJbkAWgdrMjOVA1sGai6rElwHazIxlwFdBmouqhpeB127OdUBXwXLMQNgBdErAmEHYzJyjQBiCGsyUSW1AGMGY3IzC2QHa7JpqSRlBmNypwBmB2puaiUAZwfrcSvJBWgHazJRJStpBWkqaWoG8SlpBGsHazIxLVVsBWkqQ20JZTojVSqpAm4HYzIqWQFvB2NylaoAcAjrMSqpFQFxB+txlUoycgZiLqsCcwViLnN0B2ouaSUBdQdjMslKAnYHYzLJqgB3CGU6WSXVBXgHYzKpTAV5B2MyKckFegZiLsoAewdrcirJKHwF8SkHfQhrMjKqpAB+B9R2SSUAAAAABP//AA==";
export { u8g2_font_tinypixie2_tr };
export default u8g2_font_tinypixie2_tr;
