/* u8g2 official font: u8g2_font_nerhoe_tr (890 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_nerhoe_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_nerhoe_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_nerhoe_tr', font)
 */
const u8g2_font_nerhoe_tr = "XwACAgMEAgQFCAv//gj+Cf4BMgJTA14gBQCxAiEGwXFyBSIHG5uSrAAjDDbzFtNYsTVWTAAkC0XRmldLI9XaESULxNGiVswxx7QEJg1F0ZZTTDmjnJKMKicFmXsyKAjbrZrKvgspCVuNksu+SgAqBhuZkjorCi3TmlEcMqMILAcab5YUAC0FC5UyLgUJURIvCkSxXuaYY84AMAlEsTaiz6QAMQdCcTZUDzIKRLGmYo451iMzDESxpmKOUSOZFAA0DUXRnmWKqUxDZ5QANQtEsbJy3ijnkQA2C0SxpqKWqZRJATcNxbA2dI0yyhllFAE4C0SxpqJMKppJATkLRLGmokw7y6QAOgYpUZIDOwgyb5ZhUgA8CSyznlRGGgU9CBy1MjIaAT4KLLOSkUZJZQA/C0SxpmKOdaYiAEAQRw87YkZSqUpVcmZqJABBCkSxpqJcapoBQgtEsbKiXKqUIwFDCUSxpqLuHAlECUSxsqLPkQBFCkSxMnSWqc4jRgpEsTJ0lqmuAUcKRLGmoq6mHAlICUSxEs2lphlJBkFRcghKCMSQ3vdIAEsJRLESzaVKM0wIRLGS+x4BTQhEsaLG9BlOCkSxEuVa6pQBTwlEsaaiz6QAUApEsbKiXKquAVEJRLGmoq+YAlIKRLGyolyqNANTDESxpqJGGWUkkwJUCESxMlLuE1UIRLES/UwKVglEsRJ9NSMAVwlEsRI915gBWApEsRLNJFU0A1kJRLESXVHmEloLRLEycswxxzwCWwfajbL6S1wMRLGSM8oZ5YxyAF0HWm2i+mteCSXZmlNMdQBfBgyvMgJgBxp7ElMAYQo0saZRGlGmAWIKRLGS84rOkQBjCTSxpqIuRwJkCUSxXo3oTANlCjSxpqIaMaMBZghCcaZWFwBnCkStNqIz7aQAaAlEsZLzip4BaQdBUZLGAGoISm+WU5cCawpEsZJLlWTqDGwGQVFyCG0INLGixnQGbgg0sbKiZwBvCTSxpqIzKQBwCkStsqJzpJwBcQlErTaiM+0Ccgm0kKKSzE0Acwo0saZiyqhMCnQJw3AW04rtAHUINLESPZMCdgg0sRJdzQh3CTSxEs01ZgB4CjSxEmWSKsoAeQpErRJdUeaYAXoJNLEycmyPAHsKW42aYivHdgB8BllN8hB9CluNkmM7xVYEfgeW2CYtAAAAAAT//wA=";
export { u8g2_font_nerhoe_tr };
export default u8g2_font_nerhoe_tr;
