/* u8g2 official font: u8g2_font_streamline_interface_essential_loading_t (734 bytes, 14 glyphs)
 * Converted verbatim from u8g2_font_streamline_interface_essential_loading_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_interface_essential_loading_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_interface_essential_loading_t', font)
 */
const u8g2_font_streamline_interface_essential_loading_t = "DgAEAwUFAwQGFRUAABUAFQAAAAAAAsIwM3M26yuWEpSUig6KjokPiY+ImpSKSBIkFRETJRUREiY1ERIUER8SHxMdFB0lKSglXAcxLbUSaw2PSpkem3iQmPh4+HmYiCRhUhExUXIRIfETIfHg8THxIPHYRKZKHgoyPLUSayw/ED2ws7GqK5qdoYhYQTISkZMJkoic3ETkxiZijf1RSBTFWNgIURjNTEjQUF2Vjd2B6YF4IQAzL7USaw2PSpkeUUTKsLKYqKp48IjFETkTisiRWMR6VCGxcWniIpOER6YNj4cKBTQxtRJrDY9KmR6beJCY+HjgiXmITBKJTCSKEYqJiAmdGEkPHB8TDxIPHJk2PB4qFAA1NZQy65y/FbkTswotCp4JmhghCYuImoiamKlKRDUxRA8SERYSFxKXJiwwKElU6jBJVdKFADY7tBLrnL8VuROzCi0KngmaGCEJiomImYiaSFMXkYhqYogegiwkiiIubCQsjCYoJGgotErMUOT2fhAANzC1EmsNj0qZHpt4kJj4eOCJ8ZiIkEQiE4lixCLShE6MpAeOj4kHiQeOTBseDxUKODu1EmudhzgWORQzC60KHgqaGKEJi4gaiYuYoYiLCTKLGLI/ComiGAsbIQqjmQkJGqqrsrE7MD0QLwQ5MLUSaw2PSpkem3iQmPh44InxiEwSiUwkihGKyCZ0YiQ9cHxMPEg8cGTa8HioUAA6JZI2a6uOiY6JqIuJiElTERMdE12PHXlE/DymkzOTETFbzg8CO0C1EuucB6kdKZkKkagQCYoYWRFUVzU5Dzo9ESIrolbEtmJ6HnRyKkROJChEZEQkKEQiJkIkaiQmZDYmHmQSADwodbFrOTiYiQeJCDkQlDigkzgokzgokzgokzigEzkQjIgHiTk4GAE9LI8+a3gQEhkUGRQZFBkVFxYXd1k7PBuRMiRdTLKYVEGZSIgETQ1FhhwcBAAAAAT//wA=";
export { u8g2_font_streamline_interface_essential_loading_t };
export default u8g2_font_streamline_interface_essential_loading_t;
