/* u8g2 official font: u8g2_font_logisoso58_tn (973 bytes, 18 glyphs)
 * Converted verbatim from u8g2_font_logisoso58_tn.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_logisoso58_tn.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_logisoso58_tn', font)
 */
const u8g2_font_logisoso58_tn = "EgAFBQUGBQcHIUcA/DrxOgEAAAAAA7EgBgCAwDIqOVmz6bIqaFkLTGGCMpSiDKQYpYGEIiAhCxeZ0LMa1qwHTeQKWUBCEZBRRoZSlKEEpjBBK2iZAgArE9bCS/M53vmhD/wB7xzvfAgALBFnubxqKAIXDFEQoYhKIAAtCfbAUjP4BzwuDee4wGooAhcMMQgAL0Jcr8AyRSZCUROhqIlQhB4UNRGKmghFTYSiJkJRE6EIPSiKHhQ1EYqaCEVNhKImQlEToQg9KIoeFDURipoIRVEAMD1dp8DyOmbjojWl6lwlI8tYhnIUgSxEIAsJSIPa89z////vPQ1qSEDYIZCFCOUoY0Wycp0qTStyzTwWADEeT+fAMjo7KJMqymDCBz4wBWYcITAHOv//////ADJZXafA8jpm86A1pepcJSOMWIZyFIEsRCALCUiD2vNc72mwhgSjIYJwyRAeQpOZUIQmM6EITWZCEZpQhCYzoQhNZkIRmsyEIjShCE1mQhGazIQiNKEf+A9EM0tdp78y+B+IaEIRmsyEIjSZCUVoMhOK0GQmFKHJTOgiG+i8x0ENokpNKsoiFbHnX0UVwSGDaIg4VhIUlAwmNCMr16nSxKDH0KIBNEddp8CyQuphj4qqhz0qqh4VrR4VrR4VrR4VVQ97VFQ9KlKOhJQjIeVIhzkQYg6EmAMh5kDHOQ5yjoOc43zgPxA5xJ7/HQA1RF2nwDL4H8jqYc//CKIqdBmsZEQbm3DE6ighWUhAGBKQ9rjnOe+w5886z+WgBjFEIAsRylEGIxaSletUaVqRa+axADZVXafA8jpm46I1pepcJSOLYIZyFIEsRBztCEiDnPMce/6GkqxzGaxkRBubYIoilJSEZCEBaVB73PPcv/c0qCEBWYhAFiKUo4wVycp1qjStyDXzWAA3TV2nwDL4H8gY1KCGhKMh4WhIOFgSDoaIgyE0RZGK0IQiFUUTilQUTShSUTShSEVoiiIVoSmKVIQmFKkomlCkomhCkYrQFEUqQpMGADhgXafA8jpm46I1pepcJSPLWIZyFIEsRCALCUiD2vPc954GNSQgCxHIQoRylLEiWblOlaZUnatkRCnKSFIikIUEpEHtee57T4MaEpCFCGQhQjnKWJGsXKdK04pcM48FADlUXafA8jpm46I1pepcJSPLWIZyFIEsRCALCUiD2vPcfw5qUEMCspKQJEUohRHb0JHMXMdKyjjs+azzXA5qEEMEshChHGUwYiFZuU6VphW5Zh4LADoUJ7zHqhjGB4ZQfHCrCFwwBBEAAAAABP//AA==";
export { u8g2_font_logisoso58_tn };
export default u8g2_font_logisoso58_tn;
