/* u8g2 official font: u8g2_font_osr29_tn (739 bytes, 18 glyphs)
 * Converted verbatim from u8g2_font_osr29_tn.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_osr29_tn.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_osr29_tn', font)
 */
const u8g2_font_osr29_tn = "EgAEBAYGBAUHJSYA+B33HvkAAAAAAscgBgCAcAkqKE+0u2qDyQ4bJOZMmCRByowIQZAswREhxhQJkibMITHDBpMdHQ4AK1mjqOr8IMRDIx4a8dCIh0Y8NOKhEQ+NeGjEQyMeGvHQiIdGPDTioREPjXggD36gHoR4aMRDIx4a8dCIh0Y8NOKhEQ+NeGjEQyMeGvHQiIdGPDTioREPBAAsEQWzaRkjSCiKTaAwgcKEAS0IiqDZCQ8KLgpFsXAZI16MAC8ljqlIyjIOLHFgiQNLHFjiwBIHljiwxIElDixxYIkDSxxYMAAwNFSnD3uGB40UN+EwoaKGDho6ZvCQwUMGjyCMf0xi8JDBQwaPGTpo6Cih4gSKFCYWfVAAMRAO1xB7gsUOJZWU/v+/cjIwEbcQWyZFkQpIJigJoSTEmkWpTh2JcmTEkZ6vhUsaRmwQwUHEihgr4kGIByEeBDM0UbcPSweFjRI4SOQQgiTKkShHhBxp0sNHDxs0Dj0I4pQPJ02CYA5HCCUhdIzAYSQIhwQ0LhOnEMvigYgHMZ7y0haLICuErBCiYkgKIimIoChywsiFIyaOlEBSD4iSp08dNTaRxw8rYcOQE8RqmQiD4uWJORGhCI0jI3KMSCJCh5OmJiQJgurUpSMxksTIMQJHCRuHWCQANjxRtw97RgWJk2rcIHFkhpURV2TgmOGjqSlFQtAYY0MKjig4giQuSYwkMZLEyDEDxwwUJW6YqIEjCAcENyRQxw8LPyg8OkToEIFFBA4uPLho4cFFCxctemLaGrXb0gEBOD5Upw9rZ0eNGzhq6KCxQ8gOITuE7BCyQ4oKMjcIlTCmatcJSiTwyNASg1FfPWL0iNFDxg4SK2zcwBLkgwI5PVG3D1tGBQ0bJ2rcmIFjRo4gOYLkCJK4JDGwxMAiw0SMGSRkVBnSpIePGTik3JBiY8iNGShKnDAJEQcFOg/FtHAZI16Mh8mIFyMAAAAABP//AA==";
export { u8g2_font_osr29_tn };
export default u8g2_font_osr29_tn;
