/* u8g2 official font: u8g2_font_pcsenior_8u (813 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_pcsenior_8u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_pcsenior_8u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_pcsenior_8u', font)
 */
const u8g2_font_pcsenior_8u = "QAMDAwQEAQIFCAcA/gb+Bv8BfwAAAxEgB4jBx78AIQyIwZISqWI5XA4FIgqIwVGTyCRyfCMQiMFRk4hOEtFJIpPIYQAkDIjBkpbkdFFVDgUlDojBh8gkIqkmiUwOAiYOiMEaSoQrKiO1iRwEJwmIwRFL5fgIKAqIwZMqq6sDASkKiMGRK6uqgwEqDYjBB6mRDiGaSI4GKwyIwYeJhUaxHBkALAmIwce7WCoFLQmIwcdmxxkALgmIwce7WA4FLwmIwdXnOAoAMBCIwSnJJKKJhEUyEtVhADEKiMGSjnW0wwAyDojBoYnEwqFUJLLDADMNiMGhicTCuUiNDgQ0DYjBG9IkIqWrlA4CNQyIwTCJ62KRGh0INg2IwRpKxTWRNjoQADcLiMEwKUuV1aEAOA2IwaGJtNFE2uhAADkNiMGhibSVpcI5FAA6DIjBh4nlWMRyKAA7DIjBh4nlWMRSKQA8CYjBk2rXDgQ9CojBR7Ij2hEBPgmIwZFr1Q4GPwyIwaGJxFJ1uBwKQBCIwSnJJBKKhCKhyOlAAEEMiMGS0kSaTLrDAEINiMGwiTTVRFrsMABDDYjBookkYnWRjA4DRA2IwShKZCJ9EdWBAEUQiME4yUKSIFESlEXuIABGD4jBOMlCkiBREpTSoQBHDYjBookkYqWRWh0ESAuIwRDpyaTvMABJCojBoYp1pQMBSguIwaOKlXSjAwFLD4jBGOkiI0pkIslIDgJMDIjBoIq1hVTuIABND4jBkElWXiQRNYlMDgJOEojBkElGEooKRTSRSWRyEABPEYjBGkpEMolMIhNJhHMgAFANiMGwiTTVxFI6FABRDIjBoYn0ZUaewwBSD4jBsIk01SQykWQkBwFTDYjBoYlE4/lIjQ4EVA2IwTBFJEGxVjoQAFUKiMEQ6X+ywwBWC4jBEOnfqHIoAFcSiMGQSWQSmUQSkVxWZHIQAFgRiMGQSWQiiXA6lIhkchAAWQyIwRDpjSqW0oEAWg6IwbjIJDGpUkjlDgJbCojBIYp1pgMBXAmIwZDrPQ4CXQmIwSHrkQ4EXgyIwQsPJSKZHFcAXwiIwcfvhwAAAAAE//8A";
export { u8g2_font_pcsenior_8u };
export default u8g2_font_pcsenior_8u;
