/* u8g2 official font: u8g2_font_mildras_tr (988 bytes, 94 glyphs)
 * Converted verbatim from u8g2_font_mildras_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_mildras_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_mildras_tr', font)
 */
const u8g2_font_mildras_tr = "XgACAgMEAgUEBQ0A/gv+CwABPAKUA8AgBQBhAyEH2eFyKAEiBxsxk6wAIxJdoVemmNJQZYopDVWmmBIAJA9doZtXpWLKO6mkqh0BJQxcYaNWjrnMMaclJhBdoSermOqMcoopVjGqACcHIu9WKQAoClshm2KK3TEHKQtbIZNjjl0xRQAqByMvl1YDKwotpZtRHDKjCCwHIt1WKQAtBgxpMwIuBYnhEi8JWyHbFVuxBDALXGGnomsk6UwKMQda4bb6BzINXGGnoswxxxxzHgEzDVxhp6LMlUZZyqQANAtcYSdVf42YWwA1DFxhM3S9Yq5lUgA2C1xhp6K9omdSADcKXGEzcjOXuQk4C1xhp6IzqehMCjkLXGGnomfaUiYFOgap5ZIDOwgy35ZhUgA8CS2lr2SGGgo9CCWnMzRrCD4KLaWjoYZRaQA/DV2ht7LdRhllOqMIQQpcYaeic0zPAEILXGGzonOk6BwJQwpcYaeiu2kmBUQJXGGzon+OBEUKXGEzdHvl9ghGClxhM3R75W4ARwpcYaeiu5pmGkgJXGETPcf0DEkGWaHyEEoJXGHfbymTAksLXGETrV4y9SkDTAhcYZP79whNEV2hV6aWSiqppJJKKqmkCk4OXaGT9ZwqqaSSvHUATwlcYaeifyYFUApcYbOic6TcDVEQXaEnq5hiiimmmGIqSxVSClxhs6JzpKYzUw1cYaeinZFGWcqkAFQSXaEzZEYZZZRRRhlllFFGEVUJXGET/WdSAFYOXaGTvVOZYoopZxQBVwxdoZP9SiqpzpQAWBBdoZN1KlPOKKOcYqp1AFkQXaGT7VSmmHJGGWWUUQRaDFxhM3LMZS5zHgFbCFshM2J/DlwJWyET27EdC10IWyEz+3MEXgcdsZtTHV8GDaEzBGAHGvESUwBhC0Rhp2JOI1qqAGILXGGTW8l0LpUAYwpEYaeiXcqkAGQKXGHfSmp6qQJlC0Rhp6IcO8qkAGYKXGGrcnOk3AlnC1Rdl9T0UvVIAGgJXGGTW8n0GWkHWaGixhBqCWsdW8P+XABrC1xhk5sqydSnDGwGWaHyEG0NRaFXppZKKqmkkipuCERhk5LpM28JRGGnos+kAHALVF2Tkulcqs4AcQpUXZfU9FJ1AXIIQyGTVuwJcwxEYaeiRhpJmRQAdApcYZfLkXJvJHUIRGET/VIFdgxFoZPtVKaYckYRdwpFoZO9kupMCXgLRaGTdaqrmGodeQ1Nn5PtVKaYckZRA3oLRGEzcswxxzwCewtcYSvrMqNcoyx8Bund8hF9DFxhozPKNYq5jBJ+BxWrF5UCAAAABP//AA==";
export { u8g2_font_mildras_tr };
export default u8g2_font_mildras_tr;
