/* u8g2 official font: u8g2_font_resoledmedium_tr (950 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_resoledmedium_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_resoledmedium_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_resoledmedium_tr', font)
 */
const u8g2_font_resoledmedium_tr = "XwADAgMEAwQEBQoA/gf+B/4BOgJ1A5ogBQCiAyEHOaNjUAIiB5O2I1ECIw49oqeUJINSGZRSkgAkCj2iKxvUgxYBJQo9okOTsk6aACYMPaJHqkSRFE2REicFEbdDKAvLmiuJkqgWZQEpDMuaI4uyqBIlEQAqCi2mq1JZmiIAKwotpiuMBimMACwHGponUQAtBYuuYy4FiaIjLwvEnq+URVmUZQAwDD2iZ8mkJZm0ZAExCLuiK1miDjILPaJnycJIysJBMws9omPQaquWLAA0DD2iL5OSUjJoYQI1DD2iY0jCIQ21ZAE2DD2iZwmHJLMlCwA3Cj2iYxCzYhMAOAw9omfJtGTJtGQBOQw9omfJbMkQJgsAOgYpoyMLOwi6midPFAA8BzyiL2psPQgcqmMIhwA+CLyiI2xqAz8LPaJnycKsDkUAQA09omfJlCFJlCFdAEEMPaIrS2raMGRaAEINPaJjSDJtUDJtUABDCj2iZ8nEtmQBRAo9omNIMm+DAkULPaLjGA5JGA4CRgo9ouMYDklYBEcMPaJnycRkyLRkCEgKPaIjsw1DZgtJCLuiY4m6DEoJPaKzUdOSBUsMPaIjk5KSlkSVLEwIPaIj7HEQTQo9oiNblkRzC04LPaIjm5RE2mwBTwo9omfJvCULAFAMPaJjSDLboIQhAFEKRZ5nybwlowBSDD2iY0gybVAyWwBTCz2iZ8nUVUsWAFQJPaJjkMKeAFUJPaIj8y1ZAFYKPaIj85bUIgBXCj2iI/OSKF0AWAs9oiPTklqlpgVZCj2iI7MltbAEWgo9omMQs46DAFsISptj6YsAXAtEniMLszALswBdCMqaQ+nLAF4Gk7qnAV8GDZ5jEGAGkrYjCmEKLaJnTQYtGQJiDD2iIwyHJLMNCgBjCS2iZ8nEdAhkCj2iszJotmQIZQotomfJhiEdAmYKPaJryYYobANnDD2aZ9BsyRAmCwBoCj2iIwyHJHMLaQi7oieUmgRqCcuaK5Q6LQBrCz2iQywlJS2JCmwHvKJD61FtDC2iY0gqSqIkSgFuCS2iY0gytwBvCS2iZ8lsyQJwDD2aY0gy26CEIQBxCj2aZ9BsyRAWcgktoiMxiUUAcwktomdJDwoAdAo9oifMhiisDnUJLaIjc0uGAHYJLaIjsyW1CHcKLaIjsyRKFwB4Ci2iI0tqlVoAeQs9miNzS4YwWQB6CS2iY9DaBgF7CsuaK4kqWVQLfAZJm+MBfQvLmiOLaklUiQB+CJSuJ1ESAAAAAAT//wA=";
export { u8g2_font_resoledmedium_tr };
export default u8g2_font_resoledmedium_tr;
