/* u8g2 official font: u8g2_font_04b_03b_tr (689 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_04b_03b_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_04b_03b_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_04b_03b_tr', font)
 */
const u8g2_font_04b_03b_tr = "XwACAwMDAQMEBQYA/wX/BQAA4QHPApUgBEAuIQZpKlMAIgbTM5EUIwlteqkqVaUAJAlsdlRERRQAJQltOuIUp0YBJgltOmMMmREFJwXRKwIoB2puUjIAKQhqLmEUSQAqBlszUQ4rB9ty0RQBLAbSbRIALQVLMwMuBUkqAS8IbfpQnBsCMAdsNqWyADEGai5SDjIGbDa0TTMGbDZ0AzQHbDahsg41Bmw2NV02B2w2U1wWNwhsNnSYDgE4Bmw2pVk5B2w2ZR0NOgbZKlEAOwZhKpEAPAdrslE6AT0G2zLzAD4HazJxKgk/CWw2dDSDIQBACW06tkRFFQBBB2w2pSkGQgdsNlOqLEMHbDZ1mgBECGw2U6ikAEUGbDZ1TUYHbDZ1HQNHB2w2dTQWSAhsNqFoigFJB2syU5gaSgdstnIsFksJbDahSIViAEwHbDZxNgFNCm06ViRFUiQlTglsNuEkjWIATwdsNqWyAFAHbDalaANRB2w2pcoAUgdsNqWVElMGbDY1XVQHazJTmAVVB2w2oWYBVghsNqEqMwRXC206USRFUiRFBlgJbDahGEmhGFkHbDahWBdaCGw2dCTFBFsHai5TSgBcC206MRiDMRiDAV0Hai5SagBeBdNzGV8FTDYEYAbSL2EAYQZcdmQBYgZkNnFZYwZbMuQAZAZk9mYBZQZcNlU4ZghkdlNIhQBnB+Q1ZRkBaAdkNnEpBmkGYSqRAGoG6SnRAGsIZDZxSIUBbAVhKgRtB106ViQlbgZcNqUYbwZcNmUBcAbkNaUNcQbkNWUdcgZbMmQIcwZcNlRIdAdjctEUCnUGXDahWHYIXDahGEkAdwhdOlEkRQZ4BlsyUQ55B+Q1oVgHegZcNmREewdrclI6FHwFaSoFfQlrMmIcRRIAfgfUd5EUAQAAAAT//wA=";
export { u8g2_font_04b_03b_tr };
export default u8g2_font_04b_03b_tr;
