/* u8g2 official font: u8g2_font_PixelTheatre_te (918 bytes, 117 glyphs)
 * Converted verbatim from u8g2_font_PixelTheatre_te.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_PixelTheatre_te.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_PixelTheatre_te', font)
 */
const u8g2_font_PixelTheatre_te = "dQACAgMEAQQFCAn//gb+Bv4BAwIBA28gBYBYASEGsSgZKSIGk0xJKiMKrWirhqqGqgAkCLtHizvPBCUMtniZqlIZJVXJASYKtFiLKY7UVAAnBZEsESgHwjZTPQMpCMI2ialLASoGm0tJHSsHm0lLKwEsBZkmGS0FijoRLgWJKAkvCLNIrWKKETAJtFhT0ZkUADEGsjhRPTIJtFhTUTZHADMKtFibUSOZFAA0CbRYjaprxAQ1CrRYW1kjmRQANgm0WK1VlEkBNwq0WBk55pgjADgKtFhTMakokwI5CrRYU1EmHSMAOgaZKEkBOwapJkkDPAerSE11AT0Gm0nZAz4Hq0jJVQk/CLNI0XGjCEAOx4bdVVSqUpWcmRoJQQizSFFpKCtCCrRYkSmtKEcCQwq0WFUxZ5SRAEQJtFiRqbSSBEUHsjhZKwlGB7I4WasCRwm0WFUxylQKSAizSElqKCtJBbEoOUoHsjhRLQVLCbRYiSrJ1BlMB7I4SV0CTQm1aMlrJW0HTgi0WIlLTTNPDLZ41TFlpFGZJQBQCLNIUclaEVEMtnjVMWUkU5lVAFIIs0hRyVoFUwiyOFMxKQBUB7NIWbELVQizSEleFQBWCLNISa4VAVcItWjJrnQHWAizSEmqZQVZCLNISapsAVoIs0iZKaY4WwfCNlm9BFwIs0iJOeYYXQfCNlG9Bl4Fk0xrXwWLRhlgBpI8iQFhBptIOwJiCLNIiaVKI2MGm0ibA2QHs0htHQFlBptIG2lmCLI4U2klAGcIq0Y7YkoAaAizSImlSippBqkoSQNqCDomy6lSAGsHs0iJrVVsBbEoOW0HnWhRLVVuB5tIUUkFbwebSBlpBHAIq0ZRacgIcQerRjtiAXIGmjhZCXMHm0hTSQF0B6o4SWkGdQebSEkqCXYHm0hJagF3CZ1oSUmllQB4BptISR15CatGSWrElAB6BptIkVF7CbtHTTHlmAN8BsEmOQR9CrtHyTGnmCIAfgaTTBsJoAWAWAGhBrEmSSOiCLNHizOrBKMJtFhVcaScB6UJs0hJqloxAaYGwSaZA6cJw0bbKal6AagGi01JAakKtWhb6khDqQWqBptLOwKuCrVoW3EluaoFrwWLThmwB5tLGWkEsQirSEsrowGyB6NK0SkNswejSll5AbQGkjxTALcFiSoJuQaiOlENugebSxlpBL8Is0bNaGYBAAAABP//IKwLtWgdI+YRMxwA";
export { u8g2_font_PixelTheatre_te };
export default u8g2_font_PixelTheatre_te;
