/* u8g2 official font: u8g2_font_open_iconic_www_2x_t (584 bytes, 20 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_www_2x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_www_2x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_www_2x_t', font)
 */
const u8g2_font_open_iconic_www_2x_t = "FAAEBAUFBAMGEBAAABAAEAAAFAAAAixAFOhxYSFj4sEDEWbIgyJEoyBBAEEM6HFh+A+SFBoWAEIUkKFhMGqclTLNEqKHVJBAQUIAQxsQIuEjihCdIjZNkJQ4tCzhQNFkTaIVLgwARBsPImEQYkqIKSGdqBCSRAgaIUmEmRCWWl4DRSgQImESREyMGSKTEBEkXPQgYYNGDRo1aJig0cIFCSEyCRkzwggJAkYWzmVhFkqw3ClEShapM1l07FjRwQBHG+xpYSKGZtAQYSIE0lCEMCGDxiBCZY6kKABIIxAiYSB8Mp1KtIYGmSlj5EgRJGXMkCpCQgwRJEWQEEFCAUkazqFhFCx2rNihpITwJIWQFEJSCEEiBAkASicQIuEyqIoQmXFExJUYNqLYGFKDCI0iM6zEsBHlhJAbQ4iUQlMASxQQImH4gIhAIgIfPDBMP37wgABMHPBh4SOKEJ0iNk0OkTCmRIgSIQSFCzZLWhgATRoQImEgtQzlheiGEBs0apgoccJlTPjBAwJOIhAi4TKoikw1RkiJEEFMhLl06NKtK0FQSLExhEgpNAUATyAQImEla1TIcKnKDDIyaNSgUYOGGBpTSrjwIULNEgVQHxAiYfiAMDWkiBgiIhERiYgYIkOKkBCEiAk/eEAAUSgQImEhbLr4uEHDygwkMnKIIGnEkBEiaoiQUWKEiBAjRIgRSUyLBlIbzqFhEIJECBIhKYSkEJJCCCeqyA4WPFgiAFMV0KFhDi/kxWvh4SEMLvrFE/GBAQAAAAT//wA=";
export { u8g2_font_open_iconic_www_2x_t };
export default u8g2_font_open_iconic_www_2x_t;
