/* u8g2 official font: u8g2_font_pxplusibmcgathin_8u (852 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_pxplusibmcgathin_8u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_pxplusibmcgathin_8u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_pxplusibmcgathin_8u', font)
 */
const u8g2_font_pxplusibmcgathin_8u = "QAMEAgQEAQEFCAcA/wf/BwABiQAAAzggBojh5wghCojhia1muXwYIguIYSmKhCJ5YgAjEYhhKYpkBptIZrCJhCJRACQOiOFRDSTBQTAyUGkBJQyI4dREJLEmkowSJg+IYVFFUqpEQpFptFACJwiI4cnF8gwoCYjhidUVFgMpCYhhCdaVVQMqDojhzIQ2g0FmlMljACsLiOHNpQaqXB4FLAmI4afOxVIALQmI4YcO9jQALgiI4afOhQEvB4hhj/UcMBKIYRlkQpGMpCKSiEQ0mUEUMQyI4YmpErlWAykAMg+IYRlkQrmUSBWKDJYAMw+IYRlkQrnQMBLKDKIANA+IYYqpEqFIZjBIxaYANQ+I4RhMcgNhLhLKDKIANg+I4RnFcgNNKBLKDKIANwuI4RhMQrF2xQA4EYhhGWRCkVBmkAlFQplBFDkPiGEZZEKRUGagi4W2ADoKiOHN5YG5MAA7CojhzeWBuVgKPAiIYYo1bAs9C4jhhwz2mMEeAj4IiOEJNmsMPwuIYRlkQrlYfRZAEohhGWRCkcQgkohUDCLBQRRBEYjhUUUyoUgoMpiEIqEkAEIOiOEYiDJtBqFMk4EUQwyI4RllIrnCTGgKRA6I4RikIqFMn2QGWQBFD4jhGGxapFaJVCYyWAJGDYjhGGxapFaJVGwMRw2I4RllIrmSTdEgCUgRiOEIRUKRUGQwCUVCkVASSQmIYZnlOtsCSgqIYZrlajraAksPiOHQlIQSKVkiFckYAkwLiOGY5bqJDJYATRCI4dAoelKRSqQSqUQqCE4SiOHQRBKRFpGMJBQJRUJJAE8QiOFRRTKhSCgSykRSWgBQDYjhGIgybQahXGwMURGIYRlkQpFQJBSpyAyCQgBSEIjhGIgybQahRCqSmSQBUxCIYRlkQpHgIBgJZQZRAFQNiOEYDBKRolyzKQBVEYjhCEVCkVAkFAlFQplBFFYRiOFIJVKJVCIVyYQSsSwAVxKI4UglUolUIlIRqYiUKJQAWBCI4UhFMqFErCKUiaSCAFkNiOFIRTKhRCxXNgVaDojhGAwSoVhHicEgCFsLiOEYhHLdDbIAXAiIYQj2JQBdCojhGOR6NMgCXgyI4YklQplIKk8DXwiI4Wc7GAgAAAAE//8A";
export { u8g2_font_pxplusibmcgathin_8u };
export default u8g2_font_pxplusibmcgathin_8u;
