/* u8g2 official font: u8g2_font_kibibyte_te (905 bytes, 122 glyphs)
 * Converted verbatim from u8g2_font_kibibyte_te.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_kibibyte_te.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_kibibyte_te', font)
 */
const u8g2_font_kibibyte_te = "egACAgMDAQQFBwkA/QX+BQAA3gHOA2QgBUCsACEGaZSsACIG06UkFSMJbbRVNlSqAiQJ+6OlEY+UACUIa6SkOGQKJgn7o6WZ5EgJJwXRlQgoBmqcrEopBmqcqGoqBlulpA4rB1ukpZUALAXRkwgtBcukDC4FSZQELwhrpKZYRQAwCGukjGSNADEGaZQMATIHapyokQQzBmqcqAM0CGukJDViATUGapwsNTYIa6SMONIINwZqnKgOOAhrpIw01Ag5CGukjDTiCDoGWZSkADsG4ZMkATwGWpzJAD0GW6TsAT4GWpxEBT8HapyomQBACWysqag2UgBBCGukjKSGCkIIa6SotNIIQwhrpIwk0whECGukqGQtAEUIa6SMqOIARghrpIyoYgRHCGukjJjUCEgIa6QkNZQKSQZplAwBSgdrpMxyBEsIa6QktZIKTAdrpMTmAE0KbbRcSSWVVAFOB2ukjOQKTwhrpIxkjQBQCGukjDRkBFEIbKysvkYAUghsrAw5VhlTB2ukjHgEVAdrpKzYAlUHa6Qk1whWB2ukJNcCVwtttKSkkkoqjQFYCGukJNVSAVkJa6QkNVJMAFoHa6TMVA5bBmqcrEpcB2uk5FgHXQZqnKhqXgXTpTVfBkysjABgBtKdxABhB1ukqDQCYghrpMQ40ghjBlukjDhkCGukxqFGAGUGW6QkOWYIa6RNFSMAZwhro4w04ghoCGukxDiSCmkFWZQMagZqm6hqawZbpKRVbAZanKQkbQddtFxJFW4HW6SMpAJvB1ukjDQCcAhro4w0ZARxCGujjDRiAXIHW6SMGAFzB1ukqaQAdAhrpMW0ogB1B1ukJDUCdgdbpCS1AHcIXbSkpNIYeAZbpKQOeQhroyQ14gh6BlukyCh7B2qcJZkCfAZ5kxwBfQhqnKSoEgB+CN205VQnAKAFQKwAoQbpkqQBogjro6URVwKjCGysrSzjCKQJbbTkNFNcOaUJa6SkkdJKAKYGeZOsAacKe6OpNNJISQGoBkumpACpDH/DbjotldXK9ASrCFysJRVTAKwG06TMAK4Mf8NuOkklVZueAK8GTK6MALAHW6WMNAKxB2OkpZUGsgbqnKhkswbqnKgDtAbSnSkAtQhroyQ1ZAS2B2ysXKsHtwXJlAS5B+ukyNYAugjrpIxkjQC7CFyspJhUAr8GapvFJQAAAAT//yCsCWysrTjzAAA=";
export { u8g2_font_kibibyte_te };
export default u8g2_font_kibibyte_te;
