/* u8g2 official font: u8g2_font_streamline_pet_animals_t (756 bytes, 12 glyphs)
 * Converted verbatim from u8g2_font_streamline_pet_animals_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_pet_animals_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_pet_animals_t', font)
 */
const u8g2_font_streamline_pet_animals_t = "DAADAgUFAwMGFRUAABUAFQAAAAAAAtgwMTXSdYZoGKIhCXVR0WHFDis6NRHTUMzh4iCm8RzmxRxKw1xOc7gO5zmYQ7qODkMOMUW1knV2eClqYqJEUhJJiaSmkg7lkI7UkUTURG3QBy3KwSjJcjBTbsupGkViDuY5nIbDELYsYcsSVgc11UEd0XV0GHIAMjpV0nVzKIeSPMmRKI3ycBDjLKqlYVSsU7KcFqVhHOW0ZAiHdEiyTMySIYeHJEuzZj3N4VyHdGw4AzNBtZL1dFBOcihJszwLkyiNkjCRBkkJk30Jc0qYU8KckoV5GMWDnGRDcsgUOVZ22g7mSY7oUU6rU9Iczu/gMOQANDx1svUGdVBraRZNSTRVLBVLlAxSNChRMqiDEkX7lMVJnOW0JAdzHdIRnapTdWqS06KcVqekOqgjw0EFNUG1kvXmHcnCLE6kipQmUkVKY7mOp2GOlXYwy2lJTkxy1A7myiDmyJrliB7liB7lSDnLIzVLIyVdo3CYs0EdhhA2OnO29QcdXPccTHM4jLYpi7ItqlOibLglmTIommVQNG04aNqQJEMmDkdxOKrDkCY5JcvhVId0ZLgCN0W1knV2eEtyMMmiHIySKBzEyKIqkphDYZLTMh3WclqS42Ey5OCQRmmUI1k7lEM5lkM5llxycLiDU7RjQzbk4HCHhyEHODdV0nUGZRiSQUnzVKdKORwpOaWdFuW0KM7iJKfKwxCrw9UUqUkoRWKUDkOa5ZQ0h/M7OAw5ADlCtZJ1hhwckjCHwkHKo+GURoMyKGkyiEua7Nmg5UgO5kgO5jlcyqM0p4TxnEVbNtVpUaZrUU6rU9IcznVIx4YzADo7sZo1VT3KojRMwopSUcJEqShholSUMFEqSpgoFSVMlIoSVsJqLYejLM2SeNZzHUp1WafU4UyH5OEIOzX18fWxQUc2Nc6SIQ3TQdySLBkGJQuzYcukbNjSKNmUNVqnNBpOeQ7mWRTmWaKE+ZzltA0AAAAE//8A";
export { u8g2_font_streamline_pet_animals_t };
export default u8g2_font_streamline_pet_animals_t;
