/* u8g2 official font: u8g2_font_sandyforest_tu (733 bytes, 63 glyphs)
 * Converted verbatim from u8g2_font_sandyforest_tu.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_sandyforest_tu.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_sandyforest_tu', font)
 */
const u8g2_font_sandyforest_tu = "PwADAgQEAQQFCAv//gf9CP8BRwAAAsEgBQCxAiEJgm+mRckSACIHI5siUQIjDmbQKokGKcmSZFhKACQOlc8qzJbSICXJUowAJRKoDDeLsqQYxXmURUmUlWMAJgxl0UZKskhJpEgJJwUhWUIoC5NuKomSqBZlASkMk48ii7KoEiURACoJVLUqKS1KFCsKVbAqjAYpjAAsBzJtQlEALQUTlWIuBRFRIi8MpawyC2thFtZCADEIgm9m6aIAMguFz0qKNClrMQUzDobvTouSLJO1JMo0ADQOhu8y1JKoEkXDlkYANQyFz26QwsQUZskENgyFz07KkkjRTJEENwuFzzIalDAr1gA4DobvasqSLJoyUYsmADkMhdFKijSLlGSRBjoGQnFCFDsIYm1CVBQAPAdTkSqpFT0INLNiCIcAPghTkSKrlAA/C3SxSqklSo5EAEAQdw9riEJJUSpSEoXRkABBD4WuTkqipJQMSZREIgBCDobvaqqYpCRLomhKAUMLddFKqmRhLVkARAuGzk6yRH3JtBBFDYWucpDCJNKipCQBRgyFrjJSxCTSwiwERw2W7U4La6O0KGkYAUgOhc8yiTRlkKQkyiIASQmDbqqXKIkASg2VrDLLpCQNQymZAEsPhs4mS7IkqmRKlIkVAEwLdbAmDWthMkgATRCIDkuNkiFSSpU0SdU4Ak4Ohs5Oi7YkS7Ik08IITwp10UqKNKdIAlAOhc9qkJIoiZIpzEIAUQ2W7WrKREuklNZMA1IPl+xukpJSloRjlEW1PFMLdbBOCtNUSxYAVAqGznJYw7Q5AlUOdtAyyrYkS7IkyiQAVg+Fri7JkiiJkigpaRkAVxB4ECvdilESJVGllCUSAFgNha4yiZIo0rRKKQFZDIbOMsqiWpKJNRFaC4bObpjCTsoWAlsIsm1i6S8CXAulrCINq2EaVgNdCLJtQukvA14INdkqS2oBXwYW7+IAAAAABP//AA==";
export { u8g2_font_sandyforest_tu };
export default u8g2_font_sandyforest_tu;
