/* u8g2 official font: u8g2_font_new3x9pixelfont_tr (776 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_new3x9pixelfont_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_new3x9pixelfont_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_new3x9pixelfont_tr', font)
 */
const u8g2_font_new3x9pixelfont_tr = "XwACAwMEAQQEBgoA/gf+CP8BAgIBAuwgBYDYACEGuahUASIHm8xEqgAjCa3ppapUlQIkCsvHRZU0SVUEJQmryURhlIwCJgvLx0WUHIURFQEnBZmsDCgHyrdJ+QwpCcq3hFFeEgAqBpvNRDkrCq3pxlBYxlAILAaSt0kALQWN6xQuBYmoBC8Ju8imwlQYAjAIu8hNuiYAMQi7yEVirgEyCLvIUGEZDjMJu8hQYRRLBDQIu8hEKjIDNQi7yJDhKBE2CLvIUCIlETcKu8hQYSSFKQA4CLvIUFIlETkIu8hQEikROgahqYQBOwapqIQCPAeryUbpBD0HnerUYAE+CKvJxKkkAD8Ku8hQYSTFYARADL74UeKkK6JBCgBBCLvIUFKlCkIJu8hQ0hRJBEMIu8hQYhYBRAm7yEiRrgkARQm7yJChFIYDRgm7yJChFCYBRwi7yJApFQFICLvIRKpKFUkIu8hMYa4BSge7yOaUCEsJu8hEqilSBUwHu8iEeQ5NCLvIRAelCk4Hu8hQegVPB7vIULoIUAi7yFBSmQRRCMPHULrmAFIJu8hQ0hSpAlMIu8hQ4igRVAi7yExhXgBVB7vIRHoRVgm7yES6qAgAVwi7yESqgwpYCbvIRKosVQBZCbvIRCoqTAFaCLvIjKlkOFsHyrdM+RJcCbvIhHGYDgNdB8q3SPkaXgid7cZROgBfBY3oFGAHmrxEYQBhB6vIjBUBYgi7yIQhpSJjB6vIUGJEZAi7yIaVigBlB6vIUOUAZgm7yEnRFGYBZwi7xlAqkgBoCLvIhCGlFWkGuahEBWoJy8bGYE6JAGsKu8iEKWmKpABsBbmoHG0Hq8hIxxRuB6vIUFoBbweryFAqAnAIu8ZQqjIEcQi7xlAqMgFyCKvIUGISAHMHq8iQIwF0CbvIhdEUJgV1B6vIRFoEdgiryEQqKgJ3CKvIRNIRBXgIq8hEUpYUeQi7xkRaJAF6CKvIjFFyAHsKy8dGYSoO0wF8BsmnHAJ9C8vHxGE6ClMhAH4GlexpAQAAAAT//wA=";
export { u8g2_font_new3x9pixelfont_tr };
export default u8g2_font_new3x9pixelfont_tr;
