/* u8g2 official font: u8g2_font_open_iconic_gui_2x_t (771 bytes, 30 glyphs)
 * Converted verbatim from u8g2_font_open_iconic_gui_2x_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_open_iconic_gui_2x_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_open_iconic_gui_2x_t', font)
 */
const u8g2_font_open_iconic_gui_2x_t = "HgAEBAUFAwQGEBAAABAAEAAAFgAAAudAFtBRYdNcwlACBbVpI1CQwFDCJdMAQRbPVeHSWpKgIoQ2aSJCqJCgoqXSAEISbXlhMYYoUFGSJWlokKgQAEMTbXXhMoaoUBCCBUlSaJCoSABEEhASYfgD8tCZJS0eHj94IABFGBASYRBq74IYE2JqiKkhxoSYC2LUTglGGBASYSBqT8IZEWZklJFRRoQZCWfUTgVHEhASYfhAPDwWTdY8dA9+QABIKBASYREuNIQTR+IGCQshSFQQQYLCCBITSJJQgkQEEzROkBPHwoUASSoQEuEyqIoQmYFDBEkxSFARQUKIjBFChhQhQmXIjBAkycAxhEgpNAUAShPKPWESR8oMCvWQqkBjipwgAEsSEBJh+EA8dGZJi4fHD35AAEwYEBJhEGpPwhkRZmSUkVFGhBkJZ9ROCU0YEBJhIGrvghgTYmqIqSHGhJgLYtROBU4SEBJh+APy8Fg0WfPQPXggAE8aEBJhOGm0bFmjQkYGEg8rQSGHCDVbqckDUBnONWEQFG6IQJMVmjt+zmDJkgaFjAskAFEbEBJhQIgngpAIQiIIiXAhQoUIQiIIiXAJMVIX0FFhEOKEPSRCnLCHRIgT9pAIccIAUxLQUWEw4qkltofIiKeW2AQAVBHQEWH4QDwcPXggHo4ePBBVGIx14RJJUqiwMGJCPEgRRkwwoSJJigJWFhASYUKIe8gePCBMCRIiSAQhxBEAVx0QEuE8arZSk0MEDgo3LNS4QAOFjDRatqzRkwBYFMo5YRJHygwKRQJlpAKNKXKCAFkaTpVhik6QqEFjCJF40IIQmUGjBIkLFAgAWh0PFuERQk4IOdGSmBJiSrQkaISgES0UoVHCQgFbHQ8W4RGCRgga0ZKYEmJKtCTkhJATLRShUcJCAVwnEBJhMolu0CiBYsaIGSJIEiFGJDEikSRjJBIoalApViYKkxYBAF0lEBJhMolu0CiBYgYOESpEiBFJjEgqZKAggaIGlWJlojBpEQAAAAAE//8A";
export { u8g2_font_open_iconic_gui_2x_t };
export default u8g2_font_open_iconic_gui_2x_t;
