/* u8g2 official font: u8g2_font_victoriabold8_8u (756 bytes, 64 glyphs)
 * Converted verbatim from u8g2_font_victoriabold8_8u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_victoriabold8_8u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_victoriabold8_8u', font)
 */
const u8g2_font_victoriabold8_8u = "QAMEAwQEAQEFCAcA/wf/BwABcAAAAtggB4jhxxEAIQmI4RHTuSwAIgmI4RDRe7QAIxGIYZEQOZGQkZCREDmRkAQkDIjhkSqRoxOpkgUlDYjhkAlRpRORGEkAJhCI4RmSkJEQGpKYEJExBCcJiOERU48aACgKiGGSUqZOKQApCohhkVOmSjEAKgyI4VA0czMkIQ8LKwuIYY6LqoqLBwIsCYjhRyUmJQwtCIjhB7VHAy4IiOFHLSYLLwqIYQuT0lk4ADAKiGGhEdG/IQUxCojhkRrTkSUAMg2IYaERERMakhKzBDMNiGGhERETmhNRQwo0DojhGaKRkJGQsZKiBDUMiOEwEasTE1FDCjYNiGGhEVFWI6INKQA3CojhMJNSpi0AOA2IYaER0YZGRBtSADkNiGGhEdGmTEQNKQA6CojhFRMXkwcCOwqI4RUTFxMLBjwIiOHSnZYAPQmI4QcxtQcFPgmIYZHTSmMAPwyIYaGJEROaEpcFQBOIYaEJighRERIhERIhQhJIAkELiGGhEdHERF8CQg2I4agR0aRGRJNSAEMMiGGhEVGmiQwpAEQKiOGoEdE/KQVFDIjhMBETIxITswRGC4jhMBETIxJTDUcNiGGhEVEmMaIbUgBICojhENETE30JSQqIYaES0xUpAEoKiOES04kaUgBLD4jhEFEhQzRFJCEjIglMCYjhENMzSwBNEohhkJFYcSERoUZCRkJGEgBODojhENFkQsREYkSXAE8KiGGhEdG/IQVQDIjhqBHRpEZMNQBRC4hhoRHRv6GTAFIPiOGoEdGkhkhCRkQSAFMNiGGhEVFHJ6KGFABUCYjhMBLTWwBVCojhENH/hhQAVgqI4RDRv6GSBVcSiGGQkZCRkJGQiJC4WCEjCVgNiOEQ0YZKikZESwBZC4jhENEbKjG1AFoKiOEwk9KZJQBbCohhIRLTGSkAXAmI4YjTu0gAXQmIYSHTI1IAXgyIYQobkpBJjwYAXwiI4cf2IAAAAAAE//8A";
export { u8g2_font_victoriabold8_8u };
export default u8g2_font_victoriabold8_8u;
