/* u8g2 official font: u8g2_font_lucasfont_alternate_tr (900 bytes, 93 glyphs)
 * Converted verbatim from u8g2_font_lucasfont_alternate_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_lucasfont_alternate_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_lucasfont_alternate_tr', font)
 */
const u8g2_font_lucasfont_alternate_tr = "XQADAwMDAQQFBwgA/wf/BwABLwJSA2ggBUCkACEGeZQgBSIHW6aIqAQjDn20SYpEKimVpEgEACQJfbSKFdtCACULf8SOxKK5RcIAJg1+vJGFsslCEVloEicFWZYYKAh7pIokpSUpCXukiCWlJAEqDO/EiaWETpFYCgArCu20CoZKwRAALAfam4lIAC0Fzr0wLgVRlBAvCH/EjuYzADAKfbSZxHSLTAAxCH20iglzKjIKfbSZxIKxbAUzC320oAYjxGAFADQMfbSLiSJJkVowAjULfbSwToOyyAQANgx9tJnEhJSYLDIBNwl9tCjGEjMBOA19tJnEZJFJTBaZADkMfbSZxGQRoiwyAToG4ZQIBTsI8puJRiQAPAh8rAtlzAA9Bl21qBY+CHysCGbKBj8MfbSZxIKxdFAIAEANf8SpREUSSYrEXgFBCn20mcRkN7UAQgt9tKDEZJWYrAJDB320KeZKRAl9tKDEdKsARQp9tDAGKcFgAUYKfbQwBinBRABHDH20mcSEEZosMgFICX20iKnd1AJJBXmUOEoJfbTMURaZAEsNfbSIiSJJskgoJRZMCH20COaxAE0Nf8SIziYpopBUNQBODX68CM4kIVFENhQGTwp9tJnEdItMAFALfbSgxGSVYCIAUQx9tJnEtEREIUkAUgx9tKDEZJWklFgAUwt9tJnEpFNZZAJUCH20KAXzBFUJfbSI6S0yAVYKfbSI6RZJCwFXDH/EiGoKSVJm0wBYDH20iMkiaSlpsgBZC320iKlF0oJJAFoIfbQoxnIsWwd7pCDlNFwHf8SI5wNdB3ukGOVEXwVPxDhhCW20mUZqEQJiC3W0CAYpMVkFAGMHbKyhJQ5kCXW0TKnJIgRlCW20mcQqUQJmCnSskoQosSQAZwv1s5nEZBFiZAJoCnW0CAYpMbUAaQZxlIgQagn7o4qGkiYAawl0rIglUTIFbAdynJDkAW0Mb8SwhEKikCgkSm4IbbSgxLQFbwpttJnE1CITAHAL9bOgxGSVYBAAcQn1s6nJIsQEcglttKDEhIkAcwhttKlOKwB0CnW0CpWCqREAdQhttIhpixB2Cm20iKlF0kIAdwxvxAiFRCFRSJRieApttIhF0lLSAnkL9bOIqUWIkQkAegdttKhlK3sLfKySxELBWFAAfAV5lDh9C3ysEMaCoVhEBH4H1r0RqQAAAAAE//8A";
export { u8g2_font_lucasfont_alternate_tr };
export default u8g2_font_lucasfont_alternate_tr;
