/* u8g2 official font: u8g2_font_streamline_interface_essential_cursor_t (568 bytes, 10 glyphs)
 * Converted verbatim from u8g2_font_streamline_interface_essential_cursor_t.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_streamline_interface_essential_cursor_t.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_streamline_interface_essential_cursor_t', font)
 */
const u8g2_font_streamline_interface_essential_cursor_t = "CgAEAwUFBAQGFRUAABQAFAAAAAAAAhwwQa8u1mMYloQkKCQoJCYiRCQiJiKCIk1EBEWaiJCYiJiQmEQhEoJBEYETIbExoUGRUYFhcUFzESGREiGBIYlFADEsbHLWECsaERkSGBMXFBaVLCguJjAkMiJUzCYkKCQiJCYiJI1QSGBIpAwAMju1ItYQDyUPNA9DD1IXaBURd5Ns7Eo0MCwopVCQXERkRFQIDUlURGREnFCQZFD6eJD7mHiQiHigQAAzQbUi1hoPFBEPEhMfFR0XfZsuIjIiKiRmJiQmSUlMRFBISVBETEhJTJKYmZCoiMiIuNjY67joqPiYeJCIeKBQADQ+tSLWdiAcFxyTOGQkOKIiOC7s7iAeSCY2RkQmjYjE7ISITBoRmaChGHmgg7izuOCIiuCQkeCYxHHBB2IANTK1ItZ3TUE8MywlfCB9SEtheSAhKVEiKTIjKTMiKVIhKXEgaUFLeH0gLCU8M0xBfQc2L7Ui1hoPNA9Sfw8SDxUPFR2WSlpmeuIg6iBiekZaKix1PFQ8VDzIfT3IPFAoADcwdWHXFZkiLiIuJC4kKiZkJCZRREVQRFRERVREUERFUEySkZiokLiQuIi4iMhUADglqzbWFRkRFxOVJi4iMuJAHmKurN08xIFEZERcTFSauIjIKAA5PZRi1lYtJRoZGBsWExUTFTIzEhQ0MRQTVRUTNhYTVRUTNDGUZGYkKiYqJix2LLJMqkKuhEKcIr4eYgIAAAAABP//AA==";
export { u8g2_font_streamline_interface_essential_cursor_t };
export default u8g2_font_streamline_interface_essential_cursor_t;
