/* u8g2 official font: u8g2_font_mystery_quest_42_tn (829 bytes, 18 glyphs)
 * Converted verbatim from u8g2_font_mystery_quest_42_tn.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_mystery_quest_42_tn.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_mystery_quest_42_tn', font)
 */
const u8g2_font_mystery_quest_42_tn = "EgAEAwUGAwUGFyX//CDvH/0AAAAAAyEgBgAgbAEqJ1Cqly0eYpp4MGgmZkbNjAhFSUiNxdGtNOmIXMkY0dhQVZh4FAArEnFytS8eRF6/O/hBmLw+nwMsDuUoO2OCooImRiQGAC0Jb3Cf4QfjAC4LhehDY+JgYgIALyfy23udmnycfP28/Lz8vPy8/Lz8vDyEvDyEvDyE/Lz8vPzy+XkAMEUU9Mux+kB0anBujG6KcohyhpSEdoR2ZPgg+CD4IPgg+CD4IPgg+CD4IPgg+CB4ZHhkloSUZnRokmpwbI5uivJg2A4AMR7NI2xNlJKwMGJOYi5kTGRKZihqdP9/WWh1MCEKMk4zrKvL+GBwqEyQSJJIlGSkhkQmKIREJkIkgkQmJAXJjIgEjZwEzZgE0YHIXA09/Tz9eoj59RDyEPIQ8hDzELJBsjITBzUHBzGERPEAM0gy7Ksf5OAvTylkR0RnRGdCh0Ll1UPEQ8ifHkxGzUPMT1mNHAhNjMlMCIXI1JDE1ETExNQEydTIxEzMEI2IzgwSEZUdUJ4BNEZ0rLuVvnPXE9MTwyPDI7MzszOjNKNDk0RTMVNTIVRDElVDZwcfRByEzEwIDslOxRLF0kPQQ9BD0EPQQ9BD0JsfH0xOAjVUM6yzm+TgYOYgpoZyZnRmVmZWZlZmOGY4Zh5iHmIeYuYgaoJoyG6mcmR2HmRObuhqZkhoRC5oREYkaEImIiRoQiaViEzRiNDUjOjQIBW7g1k7ADZCEuyr1fRAcCxuZiJsJkIiaijVkEjU2NT88iGrkQMhkZmSCTGSQopCCtKD0NtvKWQpRkdGZ0RnBqfmxqYGD2TLADctMOyLIf7ggwlKiVEJURFRkViR0JFQmVDpaXHp1dKLpxczHua26UHYwVg4ADhHVKSrNf5AdExwUGxUaFZIeEZ4RnhGeEZ4ZpRmdGqQbKryQPKAsGqMcqZyhnaEdmRagvoxxfDI8AgpzSgNIRUZ3UHpgRQAOT4xLKTN8kCOSopOhnCEcIJygnKC8iDyIPIg8iBQQmJQQmJuQmRqYqSCZOggZE5KfPX4NPVqYpYHobbkogA6EMXpQ+NAgiQezcTBxAQAAAAABP//AA==";
export { u8g2_font_mystery_quest_42_tn };
export default u8g2_font_mystery_quest_42_tn;
