/* u8g2 official font: u8g2_font_boutique_bitmap_7x7_tr (769 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_boutique_bitmap_7x7_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_boutique_bitmap_7x7_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_boutique_bitmap_7x7_tr', font)
 */
const u8g2_font_boutique_bitmap_7x7_tr = "XwACAgMDAgQEBgcA/wb/Bv8A+AIBAuUgBYC4ACEG8ciMFCIGk8wkFSMLtehVQ5UpDVUBJAmzyKUhh0oAJQq16MiVM8ppCiYLtvhlVKOYOrMSJwaSvCkAKAf6x6nOACkIusfE1FIAKgejyqXVACsIq8jFtGICLAaStykALQWLygwuBYmoBC8Is8hWMcUIMAezyFWuCjEGssitDjIIs8jomMoBMwizyOiU4wI0CLPIpqVGDDUIs8iMqOMCNgizyJUqqQo3CLPIzCpWADgIs8j1UhUAOQmzyFUqyZQAOgbhyMQAOweqx2WoADwHq8imugA9BpvJ7AE+B6vI5KoEPwizyDVThglAC7XorayGGqlSAEEItNhWckwZQgq02Kw4UpQjAUMItNhWukwKRAm02MhUmiMBRQm02Ay9ch4BRgi02Ay9cg1HCbTYVjrNpABICLTYRDmmGUkFsagcSgi02M1clRFLCrTYRJVkKmUATAe02OTuEU0KtejktZJKWgdOCLTYxKWmGU8ItNhW0kwKUAm02KwoR8oZUQq16MqoVZJRBVIJtNisKEeKMlMKtNipjDSSSQFUDLXoDJlRRhllFAFVCLTYRM+kAFYItNhErxgBVwq16GQrqaS6AFgJtNhEmVQ0A1kJtNhEmXZMEloItNiMHNsjWwf6x6wuAVwIs8jEHHMMXQe6x6iuAV4Fk8w1XwWLxwxgBtLMxABhB6PILZUEYgmzyMSokloAYwajyM0sZAizyFZLJQFlBqPIjS1mCLPIqbRiBWcIq8etJBcAaAizyMSokhVpBrGopBFqCLq35VQpAGsIs8jEaiUVbAWxqBxtCKXoqJZKOm4Ho8ioZAVvB6PIVaoCcAirx6ikVgRxCKvHLZVkAHIIo8ikFSMAcwijyI04EgB0CKvIpRWjAHUHo8gkKwl2CKPIJLUiAHcJpehklYYqAXgHo8ikMhV5CKvHJJXkAnoHo8jMlAZ7CbvHpphyzAF8BvnHHAF9CbvH5JhTTBF+B5TaJZUAAAAABP//AA==";
export { u8g2_font_boutique_bitmap_7x7_tr };
export default u8g2_font_boutique_bitmap_7x7_tr;
