/* u8g2 official font: u8g2_font_micropixel_tr (735 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_micropixel_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_micropixel_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_micropixel_tr', font)
 */
const u8g2_font_micropixel_tr = "XwACAgMDAgQEBgn//gX+Bv8A7wHqAsMgBYDYACEGqaisACIGk8wkFSMKrehVQ1VDVQAkCrzXxpGiHjoBJQak2MQeJgmt6OUUl4wqJwWRrQgoB7q3qc4AKQi6t8TUUgAqBpvMpA4rB5vJpZUALAWRpwgtBYq6CC4FiagELweryFZlBDAJrNipOGZSADEG6sitBjIIrNip2BwBMwms2KlYxaQANAis2EQ5dAE1CazYDL3RSAA2CazYqbxiUgA3CKzYjBzrCDgJrNipmFRMCjkJrNipmHZSADoGqajkADsGsadkATwGmrnJAD0Gm8nsAT4GmrlEBT8IrNipWFMJQAqt6K2sRqoWAEEIrNipOKYMQgms2Kw4UhwJQwis2I1cowFECKzYrGiOBEUIrNgMvfIIRgis2Ay9cgZHCKzYjZxmGkgIrNhEOaYMSQeryKxYDUoHq8jJcgFLCazYRJVkKgNMB6vIxOYATQmt6OS1ktYBTgis2MSlpgxPCKzYqWgmBVAJrNisOFLOAFEIrNipaKkBUgms2Kw4UpQBUwms2I2MNBoJVAeryKzYAlUIrNhEZ1IAVgis2ERXjABXCa3oZCupLgBYCazYRJlUlAFZCKvIJFVWAFoJrNiMnFQeAVsHuresLgFcB6vIxFwGXQe6t6iuAV4Fk8w1XwaM2IwAYAaSvMQAYQabyK0kYgiryMSo0gJjBpvIbQFkB6vIVisJZQaauCwBZgiryKa0YgJnCKvGrSQXAGgIq8jEqJIKaQapqKQBagh6puVUKQBrCKPIpJVUAGwGqagMAW0IneiMVKkCbgebyKikAm8Hm8iMNAJwCKvGqLRiBHEHq8atJAtyB5vIjCQBcwebyKmkAHQHqrikFQN1B5vIJJUEdgebyCRVAXcIneikpLoAeAabyKQOeQirxiSV5AJ6BpvIrDR7CbvHpphyzAF8BbGoHH0Ju8fkmFNMEX4HlNollQAAAAAE//8A";
export { u8g2_font_micropixel_tr };
export default u8g2_font_micropixel_tr;
