/* u8g2 official font: u8g2_font_miranda_nbp_tr (967 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_miranda_nbp_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_miranda_nbp_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_miranda_nbp_tr', font)
 */
const u8g2_font_miranda_nbp_tr = "XwACAgQEAQQFCgz//Qn9CQABSAKPA6sgBQBRAiEGkVFyCSIHM52SrAAjEolRj2KG5Rg6ZhTzGLKGNQIkDZXRmoeKKe8U09ARJROJUydzTDmmjFQmk0ZlTjFHBSYPlvGmY5VRRnVMMum4AicHMn2WFAAoCJORmsruAikIk5GSy64SKgpV2ZpRVDKnBCsKVdWaURwyowgsBTFNMi0GFLkyAi4FEVESLw+V0Y5yRjmjnFHOKCMAMAmEsaaiz6QAMQeCcaL6ATIKhLGmYo7tPAIzDISxpmJOGmWZFAA0CYSxlpMcugM1C4SxMnTeKMukADYKhLGmcl7RTAo3CoSxMnKZYy4BOAuEsaaiTCqaSQE5CoSxpqJMu6UAOgdxU5JhADsHkU+S4QA8CnSzHtsoo4wCPQg0tzIyGgE+C3SzklFGGcU2AD8LlLGmYi5rKkcAQBKYMTtyRqWNklwqJjliJscAQQyV0ZpRTjHFld0BQguUsbKiOVI0RwJDCpSxpqLumRQARAmUsbKinyMBRQqUsTJ0vXI9AkYJlLEydL1yG0cKlLGmoq6mmQZICZSxEp1jOgNJBpFR8gBKCLNs2j8XAEsKlLESXUmm0gxMCJSxkvs9Ak0MldGS9RppJZW0HU4MldGS9ZwqqSTvAE8JlLGmop9JAVAKlLGyojlSbgNRCaSvpqKfSQtSCpSxsqI5UnQGUwyUsaaizkijLJMCVBCV0TJkRhlllFFGGWUUAVUJlLES/ZkUAFYNldGS3alMMeWMIgBXDZXRkl1JJdWZYkoAWA6V0ZJTmXJGOcVU6wBZD5XRknUqU84oo4wyigBaDJSxMnLMMcecRwBbCJORMmKfA1wPldGSYUYZZpRhRhlmFF0Ik5Ey+xwBXgc13ZpTHV8FFvFyYAYjn6IDYQp0saZRTiPKNGIKlLGS84qeIwFjCXSxpqJuJgVkCZSxXo3omQZlCnSxpqIcO6MBZgmTkTbjiJ0AZwykqzaiM2kkZVIAaAmUsZLzij4DaQeRURLHAGoJw2qayX4uAGsLlLGSS5Vk6pQBbAeScZL6GW0NddGiWiqppJJKqgBuCHSxsqLPAG8JdLGmomdSAHAKpKuyoudIuQZxCaSrNqJn2g1yB3ORNnsCcwt0saaiRhrJpAB0CZOREuOI3QJ1CHSxEn2mAXYLddGS7VSmnFEEdw110ZJVUkl1ppgSAHgLddGSU5lyFVMdeQqkqxI9024pAHoJdLEycmznEXsJk5GmYpVjKXwGkVGyB30Jk5Ei2ylWCn4INdcWVZIJAAAABP//AA==";
export { u8g2_font_miranda_nbp_tr };
export default u8g2_font_miranda_nbp_tr;
