/* u8g2 official font: u8g2_font_resoledbold_tr (931 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_resoledbold_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_resoledbold_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_resoledbold_tr', font)
 */
const u8g2_font_resoledbold_tr = "XwACAwMEAwQEBgoA/gf+B/4BOwJxA4cgBQCiAyEHuqJzjAIiBx2yI7EEIw4+oieFUmRJkSWFUgQkCz2iK9rQDJkiACUJNaYjTqLWKCYMPaInSpEUqqhQCicFmrJjKAtMmiuJkqgWZQEpDMyaI4uyqBIlEQAqCi2mG0rSpAwBKwsupitDoilDIgAsBxuaJ1EALQaUqnMELgUSokMvC0Wer5RFWZRlADALPaI3idMxjdEEMQe7ondEOjIJPaI3qUXtAjMLPaJTi+IMUdIENAs9oh+LUySVsgQ1Cz2iQ8k0JFPSBDYLPaI3yZTEkiYANwk9olOLak0AOAw9ojdJlDRJlDQBOQs9ojdJLImWJgA6BzKjQ0MEOwm7mqdGSRQAPAs9oi9qQzIkQwI9CCymc8TQET4MPaIjQzIkQ6I2AD8LPaI3qUU5RocAQAs9ojeJh3TE0ARBCz2iG08SdUiUAEILPaJDSZQlURYAQwo9ojdJtJY0AUQJPaIzSrwsAEUJPaJzy5QsF0YJPaJzy5SsBkcKPaI3SfRFqQJICT2iI7EOiSVJCLyiQ4m6CEoJPaKvTVHSBEsMPaIjURE1UlKkAEwHPaIj611NCT2iE0/HxRJOCj2iE4/URC4DTwo9ojdJvKQJAFAKPaJDSSxLlgFRCkWeN0m8pBkSUgo9okNJlCWxBFMMPaI3STQ0Q5Q0AVQOPqJjypAMyZAMyZAIVQk9oiPxJU0AVgo9oiPxkuYQAFcKPaIjcR1VCgBYCz2iI47RHE/hKFkOPqIjU+EMyZAMyZAIWgk9olOL2nIBWwjLmlPpawBcDUWeI8uQLEOyDMkCXQjLmjPpqwBeBx22G08KXwYVnnMMYAaTtiMKYQktojdDkiURYgo9oiPLlMSyAGMJLaI3SbQMEWQJPaKvslgSAWUJLaI3SYcMEWYJPaI7iZWsCWcKPZpnsSRamgBoCT2iI8uUxCVpCbyiJ4Oj5gBqCsyaK4OjzgoAaw0+ojNDMiSF80xKAmwIPaIz6w0NbQotokNZkRRJCW4ILaJDSVwCbwktojdJLGkCcAo9mkNJLEuWAXEJPZpnsSRaAXIJLaJDSbQaAHMILaK3ni8AdAo9oieLlayGBnUILaIjcUkEdgktoiOxpDkEdwktoiNRR5UCeAotoiNJo0iFAnkKPZojcUm0NAF6CC2iU07LAnsKzJoriSpZVAt8Bkqb8yB9C0yaI4tqSVSJAH4IFa4XTRIAAAAABP//AA==";
export { u8g2_font_resoledbold_tr };
export default u8g2_font_resoledbold_tr;
