/* u8g2 official font: u8g2_font_lastapprenticethin_tr (883 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_lastapprenticethin_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_lastapprenticethin_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_lastapprenticethin_tr', font)
 */
const u8g2_font_lastapprenticethin_tr = "XwACAgMFAQUEBRAA/Az8DAABHgJEA1cgBQBhAyEHYaFy6AAiBxM1k1QAIw5FoVcNVaaYYkpDVQAkDGMhF1OSuYyqTAAlCmMhk2JXTLErJhFloZdTTDHFlKuYklXulAAnBRG1IigKYyGbYoq9Yw4pC2Mhk2OOvWKKACoGGzOTOisHGymXVgIsBRGfIi0FCyszLgUJoRIvCWMh2yum2AkwCGMhV/mvCjEIYyGXZP8aMgljIaNjq+wcMwpjIaNjK8fmAjQJYyGTfI3YAzUKYyEzYrtsLgA2CmMhV8lSJa8KNwpjITObU8UuADgKYyFXuVpeFQA5CmMhV3klWaoKOgdBoZJxADsHSZ+SsQA8Bysnm+oCPQYbKbMHPgcrJ5OrEj8KYyHX7IqZmQBADUWht7IaaqSlMlwAQQljIVd5DeUVQgpjIaOSayWvBUMJYyFXyf6qAEQJYyGjkv9aAEUKYyEzYlPFzgFGCmMhM2Knip0ARwljIbdkl1cSSAljIZO8hvIVSQhjIbNi/xpKCGMhM/vnAksJYyGTvFbyFUwIYyET+88BTRNloTNSpZJKKqmkkkoqqaSSKk4IYyGjkv8VTwhjIVf5rwpQCmMho5LXip0AUQhrH1f5rzpSCmMho5LXSl4BUwljITfbZXMBVAhjIbNi/wVVCGMhk/yvJFYJYyGT/FeZAFcTZaGTkkoqqaSSSiqppJJKqgtYCmMhk7yqkbwCWQpjIZN8JdlcAFoIYyEzm2dzWwhjITNi/xxcCWMhE7tjjh1dCGMhM/vnCF4GEzXXAF8FCyEzYAYS9RIDYQlDIddMy0oCYgpjIRObKvlaAGMIQyFXya4KZAljIdu1fCUBZQlDIVdZQ6YKZgpjIVfJqGKfAGcKYxlX+UoyqgpoCWMhE5sq+RVpB2GhkscQagmC2Zap/ksBawpjIRO7rJVcAWwIYyET+68KbQ5FoTNSpZJKKqmkkipuCEMho5JfAW8IQyFX+aoAcAljGVf5WrEJcQljGVf5SrIDcghDIVfJngBzCUMhV+lSVQB0CWMhF1sr9g51CEMhk/xKAnYIQyGTfJUJdw1FoZOtpJJKKqkuAHgJQyGTrGokK3kKYxmT/Eoyqgp6CUMhM6uYYhx7CmMhm2Irx+4AfAZhofIBfQpjIZNjO8WuCH4IHamXU50AAAAABP//AA==";
export { u8g2_font_lastapprenticethin_tr };
export default u8g2_font_lastapprenticethin_tr;
