/* u8g2 official font: u8g2_font_stylishcharm_tr (753 bytes, 95 glyphs)
 * Converted verbatim from u8g2_font_stylishcharm_tr.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8g2_font_stylishcharm_tr.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8g2_font_stylishcharm_tr', font)
 */
const u8g2_font_stylishcharm_tr = "XwACAgMEAQQEBQkA/gf+BwAA8gHrAtUgBYDYACEGuagMFSIGk80kFSMJu8jFtNKKCSQJu8hZaaWVACUJs8ikmGKKKSYJu8hVqqWSACcFka0IKAe6uKnOACkIurjE1FIAKgabzKQOKwebyqWVACwFkacILQWLywwuBYmoBC8Iu8hWsYoRMAi7yFVeFQAxB7vIJdk1Mgi7yDVTGQczCbvINVNWFQA0CLvILTViAzUJu8iMGLWqADYJu8hVUiVVATcIu8jMKrYAOAm7yFWqpSoAOQm7yFUqSVUBOgapqOQAOwaxp2QBPAeryaa6AD0Gm8rsAT4Hq8nkqgQ/CbvINVPMMAFACLzYqajeaEEIu8hVaigrQgm7yKikVlILQwi7yFWyVQFECLvIqOS1AEUJu8iMGFWMA0YJu8iMGFUsAUcJu8hVciSVBEgIu8gkaygrSQa5qBwBSge7yHaqCksJu8gktaJKKkwHu8jEngNNCLvIpKG8Ak4Ju8gkNYayAk8Iu8hVXhUAUAm7yKhkrRgBUQjDx1VedQBSCbvIqGStpAJTCLvIVTqrClQHu8is2AtVCLvIJF8VAFYIu8gkrzIBVwi7yCSvoQJYCLvIJKtlBVkIu8gkq2wBWgi7yMyqjANbB7q4rC4BXAi7yMQc6xhdB7q4qK4BXgWTzTVfBYvHDGAGkr3EAGEIq8jotJIAYgm7yMSokrUAYwaryM1aZAi7yFbLSgJlB6vIVSsLZgi6uKm0KgBnCbvGLSvJlABoCLvIxKiSK2kGuaikIWoIyrbl1KUAawm7yMRKraQCbAa5qBwBbQqt6KiWSiqpAm4Hq8io5ApvB6vIVVYFcAm7xqhkrRgBcQi7xi0ryQJyB6q4qRYAcweryO28AHQIuriktMoAdQeryCRXEnYHq8gkVwV3CKvIJGuoAHgIq8gk1VIBeQm7xiRXkikBegeryMxUDnsJu8immHLMAXwGuagcAX0Ju8jkmFNMEX4HlNsllQAAAAAE//8A";
export { u8g2_font_stylishcharm_tr };
export default u8g2_font_stylishcharm_tr;
