/* u8g2 official font: u8x8_font_victoriamedium8_u (516 bytes, 32 glyphs)
 * Converted verbatim from u8x8_font_victoriamedium8_u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8x8_font_victoriamedium8_u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8x8_font_victoriamedium8_u', font)
 */
const u8x8_font_victoriamedium8_u = "IF8BAQAAAAAAAAAAAAAAXwAAAAAABwAAAAcAAAAifyIifyIAACQqayoSAAAAIhAIBCIAACBWSUlWIFAAAAAABwAAAAAAABwiQQAAAAAAQSIcAAAAACocfxwqAAAACAg+CAgAAAAAQDAAAAAAAAgICAgICAAAAABgYAAAAABAIBAIBAIAAD5RSUU+AAAAQEJ/QEAAAABiUUlJRgAAACJBSUk2AAAAHBJRf1AAAAAnRUVFOQAAADxKSUkwAAAAAQF5BQMAAAA2SUlJNgAAAAZJSSkeAAAAAAASAAAAAAAAQDIAAAAAAAAIFCJBAAAAFBQUFBQUAAAAQSIUCAAAAAIBWQkGAAA8QpmlpbkiHAB+CQkJfgAAAH9JSUk2AAAAPkFBQSIAAAB/QUFBPgAAAH9JSUFBAAAAfwkJCQEAAAA+QUFJOgAAAH8ICAh/AAAAAEF/QQAAAAAgQEBAPwAAAH8IFCJBAAAAf0BAQEAAAAB/AgQCfwAAAH8ECBB/AAAAPkFBQT4AAAB/CQkJBgAAAD5BYUG+AAAAfwkZKUYAAAAmSUlJMgAAAAEBfwEBAAAAP0BAQD8AAAAfIEAgHwAAAH8gECB/AAAAYxQIFGMAAAAHCHAIBwAAAGFRSUVDAAAAAH9BQQAAAAACBAgQIEAAAAAAQUF/AAAAAAQCAQIEAICAgICAgICA";
export { u8x8_font_victoriamedium8_u };
export default u8x8_font_victoriamedium8_u;
