/* u8g2 official font: u8x8_font_7x14_1x2_n (435 bytes, 32 glyphs)
 * Converted verbatim from u8x8_font_7x14_1x2_n.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8x8_font_7x14_1x2_n.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8x8_font_7x14_1x2_n', font)
 */
const u8x8_font_7x14_1x2_n = "IDoBAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAECA4IBAAAAABAIPAgQAAAAAAOAAAAAAAAEBDwEBAAAAAAAAAAAAAAAASDgAAAAAAAAAAAAAAAAAAQEBAQEAAAAAAAAAAAAAAAAQOBAAAAAAAADAMAwAAGAYBgEAAAAA4BAICBDgAAAHCBAQCAcAAAAgEPgAAAAAABAQHxAQAAAwCAgIiHAAABAYFBIREAAACAiIyKgYAAAMEBAQEA8AAACAYBD4AAAABgUEBB8EAAD4SEhISIgAAAwQEBAQDwAA4BCIiIgAAAAPERAQEA8AAAgICIhoGAAAABgGAQAAAAAwSIiISDAAAA4REBARDgAA8AgICIjwAAAMERERCAcAAAAAQOBAAAAAAAAIHAgA";
export { u8x8_font_7x14_1x2_n };
export default u8x8_font_7x14_1x2_n;
