/* u8g2 official font: u8x8_font_8x13B_1x2_n (435 bytes, 32 glyphs)
 * Converted verbatim from u8x8_font_8x13B_1x2_n.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8x8_font_8x13B_1x2_n.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8x8_font_8x13B_1x2_n', font)
 */
const u8x8_font_8x13B_1x2_n = "IDoBAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAgIDggICAAAAMBwMHDAAAAICA4OCAgAAAAQEHBwEBAAAAAAAAAAAAAAAiPh4OAAAAAAAAAAAAAAABAQEBAQEAAAAAAAAAAAAAAAgcHAgAAAAAAIDAcDgAHA4DAQAAAADg8BgIGPDgAAcPGBAYDwcAACAw+PgAAAAAEBAfHxAQADA4CAiI+HAAGBwWExEQEAAICIjI6LgYAAgYEBAQHw8AgMBgMPj4AAADAwICHx8CAPj4yEhIyIgACBgQEBAfDwDg8JiIiIgAAA8fGRAQHw8ACAgIiMh4OAAAAB4fAQAAAHD4iIiI+HAADx8QEBAfDwDw+AgImPjwAAAREREZDwcAAABA4OBAAAAAAAgcHAgA";
export { u8x8_font_8x13B_1x2_n };
export default u8x8_font_8x13B_1x2_n;
