/* u8g2 official font: u8x8_font_artosserif8_u (516 bytes, 32 glyphs)
 * Converted verbatim from u8x8_font_artosserif8_u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8x8_font_artosserif8_u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8x8_font_artosserif8_u', font)
 */
const u8x8_font_artosserif8_u = "IF8BAQAAAAAAAAAAAAAAXwAAAAAAAwAAAAMAAAAifyIifyIAACQqayoSAABCJRIIJFIhAAAgVklJVSJQAAAAAAMAAAAAABwiQQAAAAAAAEEiHAAAAAAKBB8ECgAACAg+CAgAAAAAAEAwAAAAAAgICAgICAAAAABAAAAAAEAgEAgEAgEAAD5BQUE+AAAAQEJ/QEAAAABiUUlJRgAAACJBSUk2AAAAHBJRf1AAAAAnRUVFOQAAAD5JSUkyAAAAAQF5BQMAAAA2SUlJNgAAACZJSUk+AAAAAAASAAAAAAAAACASAAAAAAAIFCJBAAAAFBQUFBQUAAAAAEEiFAgAAAIBWQkGAAA8QpmlpbkiHEB4VhFWeEAAQX9JSUlJNgAcIkFBQUEiAEF/QUFBQT4AQX9JSUlBYwBBf0kJCQEDABwiQUFJSToAQX9JCEl/QQAAAEF/QQAAACBAQEBBPwEAQX9JCFVjQQBBf0FAQEBgAEF/RQhFf0EAQX9FCFF/QQAAPkFBQUE+AEF/UREREQ4AAD5BQWFBvgBBf0kJCUl2QCZJSUlJSTIAAwFBf0EBAwABP0FAQT8BAAEPMUAxDwEAAX8hHCF/AQBBY1UIVWNBAAEHSXBJBwEAQ2FRSUVDYQAAAH9BQQAAAAECBAgQIEAAAAAAQUF/AAAABAIBAgQAAICAgICAgICA";
export { u8x8_font_artosserif8_u };
export default u8x8_font_artosserif8_u;
