/* u8g2 official font: u8x8_font_open_iconic_arrow_2x2 (899 bytes, 64 glyphs)
 * Converted verbatim from u8x8_font_open_iconic_arrow_2x2.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8x8_font_open_iconic_arrow_2x2.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8x8_font_open_iconic_arrow_2x2', font)
 */
const u8x8_font_open_iconic_arrow_2x2 = "QFsCAgAAAAAAAP//AAAAAAAAAAAAAAQMHDx/fzwcDAQAAAAAAMDg8Pj8wMDAwMDAwMDAwAAAAQMHDwAAAAAAAAAAAADAwMDAwMDAwMDA/Pjw4MAAAAAAAAAAAAAAAA8HAwEAAAAAIDA4PP7+PDgwIAAAAAAAAAAAAAD//wAAAAAAAAAA4Pj8/v7/AwMDA//+/vz44AcfPnx48ODAwODweHw+Hwfg+Hw+Hg8HAz8/Pz4+PPjgBx8+fHjw4MD8/Px8fDwfB+D4PD4+Pz8/AwcPHj58+OAHHzx8fPz8/MDg8Hh8Ph8H4Ph8Ph4PBwMDBw8ePnz44AcfP39//8DAwMD/f38/HwcAAAAAAAD/////AAAAAAAAAAAABAwcP3//fzwcDAAAAACAwODw+MDAwMDAwMDAwMABAwcPHx8DAwMDAwMDAwMDwMDAwMDAwMDAwPj48ODAgAMDAwMDAwMDAwMfDwcDAQAAAAAwODz+//78ODAgAAAAAAAAAAAA/////wAAAAAAAAAQMHDw8PDw8PDw8HAwEAAAAAAAAAEDBwcDAQAAAAAAAAAAAACAwODw+Pz+AAAAAAAAAAAAAQMHDx8/fwAAAAAAAAAA/vz48ODAgAAAAAAAAAAAAH8/Hw8HAwEAAAAAAAAAAAAAgMDg4MCAAAAAAAAACAwODw8PDw8PDw8ODAgAADB4+PDgwICAwODw+HgwAAAAAAABAwcPDwcDAQAAAAAAAACAwODw+Hw+HgwAAAAAAAAAAQMHDx8+fHgwAAAAAAAAAAwePnz48ODAgAAAAAAAAAAweHw+Hw8HAwEAAAAAAAAAgMDg8Pj48ODAgAAAAAAGDw8HAwEAAAEDBw8PBgAAAABAwMD/////wMBAAAAAwMDAwMDBw8fHw8HAwMDAwAMDAwMDg8Pj48ODAwMDAwMAAAACAwP/////AwMCAAAAODwMDAwMDAwMDAwMPx4MAAAMHj8MDAwMDAwMDAwMDwcAAMDwOBgMDAAAgMDg4MCAAQMHBwMBAAAwMBgcDwMAAAAAz88DAwMDAwNDw///wEACA///w8LAwMDAwMDz8wAADAwcOHDgwOBwOBwMPx4MADAwOBwOBwMDDxw4MPx4MAAAgMDA4ODw8PDw//78+HAgDAcDAQEAAAAAAAcDAQAAAP//AwMDYzA4ODw8PH48HAg/PzAwMDAwMDAwPDwAAAA=";
export { u8x8_font_open_iconic_arrow_2x2 };
export default u8x8_font_open_iconic_arrow_2x2;
