/* u8g2 official font: u8x8_font_7x14B_1x2_n (435 bytes, 32 glyphs)
 * Converted verbatim from u8x8_font_7x14B_1x2_n.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8x8_font_7x14B_1x2_n.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8x8_font_7x14B_1x2_n', font)
 */
const u8x8_font_7x14B_1x2_n = "IDoBAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGKD4+KAYAAADAAMDAAMAAAAA4OAAAAAAAQEPDwEBAAAAAAAAAAAAAAAASHg4AAAAAAAAAAAAAAABAQEBAQEAAAAAAAAAAAAAAAAYGAAAAAAAAIDgfBwAAHB8DwMAAAAA8PgICPjwAAAPHxAQHw8AACAw+PgAAAAAEBAfHxAQAAAwOAiI+HAAABgcFhMREAAAMDiIiPhwAAAMHBAQHw8AAACAwPD4AAAABwcEHx8EAAD4+EhIyIgAAAwcEBAfDwAA4PCYiLgwAAAPHxAQHw8AADg4iOh4GAAAAAAfHwAAAABw+IiI+HAAAA4fEREfDgAA8PgICPjwAAAMHREZDwcAAAAAYGAAAAAAAAAMDAAA";
export { u8x8_font_7x14B_1x2_n };
export default u8x8_font_7x14B_1x2_n;
