/* u8g2 official font: u8x8_font_artossans8_u (516 bytes, 32 glyphs)
 * Converted verbatim from u8x8_font_artossans8_u.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8x8_font_artossans8_u.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8x8_font_artossans8_u', font)
 */
const u8x8_font_artossans8_u = "IF8BAQAAAAAAAAAAAAAAXwAAAAAAAwAAAAMAAAAifyIifyIAACQqayoSAABCJRIIJFIhAAAgVklJVSJQAAAAAAMAAAAAABwiQQAAAAAAAEEiHAAAAAAKBB8ECgAACAg+CAgAAAAAAEAwAAAAAAgICAgICAAAAABAAAAAAEAgEAgEAgEAAD5BQUE+AAAAQEJ/QEAAAABiUUlJRgAAACJBSUk2AAAAHBIRfxAAAAAnRUVFOQAAAD5JSUkyAAAAAQF5BQMAAAA2SUlJNgAAACZJSUk+AAAAAAASAAAAAAAAACASAAAAAAAIFCJBAAAAFBQUFBQUAAAAAEEiFAgAAAIBWQkGAAA8QpmlpbkiHGAYFhEWGGAAf0lJSUlJNgA+QUFBQUEiAH9BQUFBQT4Af0lJSUlBQQB/CQkJCQEBAD5BQUFJSToAfwgICAgIfwAAQUF/QUEAACBAQEBAQD8AfwgICBQiQQB/QEBAQEBAAH8CBAgEAn8AfwIECBAgfwA+QUFBQUE+AH8REREREQ4APkFBQWFBvgB/CQkJCRlmACZJSUlJSTIAAQEBfwEBAQA/QEBAQEA/AA8QIEAgEA8AH2AgHCBgHwBBIhQIFCJBAAMECHAIBAMAQWFRSUVDQQAAAH9BQQAAAAECBAgQIEAAAAAAQUF/AAAABAIBAgQAAICAgICAgICA";
export { u8x8_font_artossans8_u };
export default u8x8_font_artossans8_u;
