/* u8g2 official font: u8x8_font_8x13_1x2_n (435 bytes, 32 glyphs)
 * Converted verbatim from u8x8_font_8x13_1x2_n.c; byte-for-byte identical to the device build.
 * Usage:
 *   import b64 from 'u8g2-js/fonts/u8x8_font_8x13_1x2_n.js';
 *   const font = U8g2Font.fromBase64(b64);   // or U8g2Font.register('u8x8_font_8x13_1x2_n', font)
 */
const u8x8_font_8x13_1x2_n = "IDoBAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQFDg4FBAAAAAAQAAAQAAAAAAwAAAAAAAAQEHAQEAAAAAAAAAAAAAACAYGAgAAAAAAAAAAAAAAAABAQEBAQAAAAAAAAAAAAAAABA4EAAAAAAAAACAQDAAGAQCAQAAAAAAwCAQECDAAAAHCBAQCAcAAEAg8AAAAAAAEBAfEBAAAABgEBAQEOAAABgUEhIREAAAEBAQkFAwAAAIEBEREQ4AAACAQCDwAAAABwQEBB8EAADwEJCQkBAAAAkREBAQDwAAwCAQEBAAAAAPEhEREQ4AABAQEJBQMAAAABgGAQAAAADgEBAQEOAAAA4RERERDgAA4BAQEJDgAAAAERERCAcAAACAwIAAAAAAABA5EAAA";
export { u8x8_font_8x13_1x2_n };
export default u8x8_font_8x13_1x2_n;
