#!/usr/bin/env node
/**
 * build-demo.js
 *
 * Bundle demo/demo.html + demo.js + the whole src/ library + the bundled
 * fonts into ONE self-contained HTML file (demo/demo-standalone.html) that
 * opens straight from file:// — no server, no fetch, no CORS.
 *
 * ES modules are concatenated in dependency-first order with their
 * import/export statements stripped, so a single inline <script type=module>
 * (which browsers DO allow from file://) contains everything.
 *
 *   node tools/build-demo.js
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DEMO = join(ROOT, 'demo');
const SRC = join(ROOT, 'src');

/* ------------------------------------------------------------------ */
/* resolve the import graph, dependency-first                          */

function parseImportSpecs(code) {
  const specs = [];
  /* both `import ... from 'x'` and `export { ... } from 'x'` re-exports */
  const re = /^(?:import\s+[^;]+?\s+from|export\s*\{[^}]*\}\s*from)\s*['"]([^'"]+)['"];/gm;
  let m;
  while ((m = re.exec(code))) specs.push(m[1]);
  return specs;
}

function collect(file, seen, order) {
  file = resolve(file);
  if (seen.has(file)) return;
  seen.add(file);
  const code = readFileSync(file, 'utf8');
  for (const spec of parseImportSpecs(code)) {
    const target = resolve(dirname(file), spec);
    if (extname(target).toLowerCase() !== '.js') continue;
    if (!seen.has(target)) collect(target, seen, order);
  }
  order.push(file);
}

/* ------------------------------------------------------------------ */
/* strip module syntax so the files share one scope                    */

function stripModule(code, file) {
  let out = code
    .replace(/^import\s+[^;]+?\s+from\s+['"][^'"]+['"];\s*/gm, '')
    .replace(/^export\s*\{[^}]*\}\s*from\s*['"][^'"]+['"];\s*/gm, '')
    .replace(/^export\s*\{[^}]*\};\s*/gm, '')
    .replace(/^export\s+default\s+/gm, '')
    .replace(/^export\s+(const|let|var|function|class|async\s+function)\s+/gm, '$1 ');
  return `/* ---- ${file.replace(ROOT + '\\\\', '').replace(ROOT + '/', '')} ---- */\n${out}\n`;
}

/* ------------------------------------------------------------------ */

function main() {
  const seen = new Set();
  const order = [];
  collect(join(DEMO, 'demo.js'), seen, order);

  let bundle = '/* u8g2-js bundled (generated by tools/build-demo.js) */\n';
  for (const file of order) {
    bundle += stripModule(readFileSync(file, 'utf8'), file);
  }

  let html = readFileSync(join(DEMO, 'demo.html'), 'utf8');
  html = html.replace(
    '<script type="module" src="demo.js"></script>',
    '<script type="module">\n' + bundle + '\n</script>',
  );
  html = html.replace('<title>u8g2-js · U8G2 Browser Simulator</title>',
    '<title>u8g2-js · U8G2 Browser Simulator (standalone)</title>');

  const outFile = join(DEMO, 'demo-standalone.html');
  writeFileSync(outFile, html);
  console.log(`wrote ${outFile} (${(html.length / 1024).toFixed(0)} KB, ${order.length} modules)`);
}

main();
